sudo: false
dist: trusty
group: deprecated-2017Q4 # To fix NPM timeout errors
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/NetAppDocs/jekyll dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
- cp -rl dependencies/jekyll/search.html ./docs/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ docs\/search\.html/g' ./docs/search.html
- cp -rl dependencies/jekyll/search.html ./solutions/search.html
- sed -i 's/permalink\:\s*\/search\.html/permalink\:\ solutions\/search\.html/g' ./solutions/search.html
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
script:
- bundle exec rake deploy
