---
sidebar: sidebar
permalink: concept_cluster_types.html
summary: NetApp HCI with NetApp Kubernetes Service shows you different types of clusters.
keywords: netapp, hci, on premise, cloud services, cluster
---

= Cluster types
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You'll encounter different types of clusters when using NetApp HCI in the cloud with NetApp Kubernetes Service.


Types of clusters you'll encounter:

*	Bootstrap agent: Establishes an initial tunnel to the NetApp Kubernetes Service Controller, builds a temporary bootstrap cluster, and creates a service cluster.
*	Service cluster: Deploys services. The service cluster connects to NetApp Kubernetes Service and takes care of itself.
* User clusters:

[discrete]
== Top Links
* link:cloud_volumes_service/snapshot_cloud_volumes.html[Durability, Availability, Encryption and Snapshots on Cloud Volumes Service]
* link:cloud_volumes_ontap/networking_cloud_volumes_ontap.html[NetApp Cloud Volumes ONTAP And Enhanced Networking Support]
* link:NPS/gdpr_and_hybrid_cloud.html[GDPR and Hybrid Cloud: A More Perfect Union]

[discrete]
== Find more information

* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://www.netapp.com/us/forms/campaign/register-for-netapp-cloud-volumes-for-aws.aspx?hsCtaTracking=4f67614a-8c97-4c15-bd01-afa38bd31696%7C5e536b53-9371-4ce1-8e38-efda436e592e[Get a first look at the new NetApp Cloud Volumes Service for AWS^]
