---
sidebar: sidebar
permalink: concept_behind_the_scenes.html
summary: What happens behind the scenes when you enable cloud services on NetApp HCI
keywords: netapp, hci, on premise, cloud services, cluster
---

= What happens behind the scenes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Behind the scenes, NetApp HCI creates a bootstrap agent that establishes an encrypted communication tunnel to the NetApp Kubernetes Service control plane and creates a service cluster.

The _service cluster_, connected to NetApp Kubernetes Service, acts as a service orchestrator to deploy services and update itself. The NetApp Kubernetes Service agent maintains the tunnel, maintains deployed service clusters, and enables you to create _workload clusters_ on which you can place applications or solutions.

After a service cluster is deployed on your system, NetApp HCI is able to push requested software along with updates to your NetApp HCI systems.




[discrete]
== Top Links
* link:task_deploying_overview.html[Deploying cloud services on NetApp HCI overview]
* link:concept_architecture_cloudinsights.html[Real-time analytics with NetApp Cloud Insights]


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* https://docs.netapp.com/us-en/hybridcloudsolutions/[Hybrid Cloud Solutions documentation^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
