---
sidebar: sidebar
permalink: index.html
summary: With cloud services technology on NetApp HCI along with NetApp HCI Solutions, you can deploy cloud services across multiple public cloud providers and on premise.
keywords: netapp, hci, on premise, kubernetes, cloud services
---

= NetApp HCI Documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

With NetApp® HCI, hybrid cloud infrastructure is a reality.
It starts with the combination of NetApp HCI and cloud services on NetApp HCI along with NetApp HCI Solutions.

With the technology and the team behind you, you can deploy and operate hybrid clouds on-premise and off-premise.

== Get started with NetApp HCI

* Identify prerequisites needed for NetApp HCI and for cloud services on NetApp HCI.
* Get started with access to NetApp Hybrid Cloud Control, which helps you enable cloud services or monitor, expand, or upgrade your NetApp HCI system.
* Learn about NetApp HCI Solutions that provide you with the information needed to deploy and operate private clouds, supporting a wide variety of use cases spanning both on-premise and off-premise.  NetApp HCI Solutions deliver value-add capabilities across public, private, hybrid and multi-cloud in technology areas such as DevOps, end user computing, enterprise applications, artificial intelligence, data protection and Data Fabric management.


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
