---
sidebar: sidebar
permalink: index.html
summary: hci, cloud, onpremise, on prem
---

= NetApp HCI in the Cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:keywords: hci, cloud, onprem, documentation, help

[.lead]
NetApp Hybrid Cloud Infrastructure (HCI) in the cloud uses Kubernetes containers to stand up a system quickly and easily. NetApp HCI deploys across multiple public cloud providers and on premise. You can use NetApp HCI to deploy your services similar to what you might do with a cloud provider—all in a self-service mode without IT involvement.​

== What you can do with NetApp HCI

*	Deploy services across cloud providers and maybe retain some on premise. 
*	Work with multiple cloud providers and avoid getting locked into one provider.
*	Spin services up yourself without the need to involve DevOps and IT. 
*	Spin up prepared applications on demand. Maybe even your own app. 
*	Deploy services on premise as easily as you can with cloud providers. 
*	Monitor data across cloud providers and on premise with one app or service. 

== NetApp HCI architecture overview
NetApp HCI uses the following NetApp cloud services: 
* NetApp Kubernetes Service: Provides a Kubernetes application marketplace, Compute as a Service, and application orchestration from NetApp HCI
* NetApp Cloud Volumes Service: Provides ONTAP on-premise or private cloud as a service 
* NetApp Cloud Insights: Provides analytics for the compute, network, and storage stack for cloud services, including NetApp HCI. 


== Getting started

Deploying NetApp HCI involves the following: 

*	NetApp Deployment Engine: Deploys NetApp HCI.
* NetApp Hybrid Cloud Controller: Deploys and configures HCI Element and enables NetApp Cloud Services for NetApp HCI. 
*	NetApp HCI management node: Establishes a connection to NetApp Cloud Central and authenticates and registers the NetApp HCI installation to a Cloud Central account. 
*	NetApp Kubernetes Service Agent: Maintains the communication tunnel, creates user clusters, and maintains deployed services such as NetApp Cloud Services.

Types of clusters you'll encounter: 
*	Bootstrap agent: Establishes an initial tunnel to the NetApp Kubernetes Service Controller, builds a temporary bootstrap cluster, and creates a service cluster. 
*	Service cluster: Deploys services. The service cluster connects to NetApp Kubernetes Service and takes care of itself.
* User clusters: 

[discrete]
== Top Links
* link:cloud_volumes_service/snapshot_cloud_volumes.html[Durability, Availability, Encryption and Snapshots on Cloud Volumes Service]
* link:cloud_volumes_ontap/networking_cloud_volumes_ontap.html[NetApp Cloud Volumes ONTAP And Enhanced Networking Support]
* link:NPS/gdpr_and_hybrid_cloud.html[GDPR and Hybrid Cloud: A More Perfect Union]

[discrete]
== Find more information

* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://www.netapp.com/us/forms/campaign/register-for-netapp-cloud-volumes-for-aws.aspx?hsCtaTracking=4f67614a-8c97-4c15-bd01-afa38bd31696%7C5e536b53-9371-4ce1-8e38-efda436e592e[Get a first look at the new NetApp Cloud Volumes Service for AWS^]
