---
sidebar: sidebar
permalink: index.html
summary: NetApp HCI enables you to deploy cloud services across multiple public cloud providers and on premise. You can use NetApp HCI to deploy services similar to what you might do with a cloud provider--all in a self-service mode without IT involvement.
keywords: netapp, hci, on premise, kubernetes, cloud services
---

= Cloud services on NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Hybrid Cloud Infrastructure (HCI) in the cloud uses Kubernetes containers to stand up a system quickly and easily. NetApp HCI deploys across multiple public cloud providers and on premise. You can use NetApp HCI to deploy your services similar to what you might do with a cloud provider—all in a self-service mode without IT involvement.​

== What you can do with cloud services on NetApp HCI

*	Deploy services across cloud providers and maybe retain some on premise.
*	Work with multiple cloud providers and avoid getting locked into one provider.
*	Spin services up yourself without the need to involve DevOps and IT.
*	Spin up prepared applications on demand. Maybe even your own app.
*	Deploy services on premise as easily as you can with cloud providers.
*	Monitor data across cloud providers and on premise with one app or service.




[discrete]
== Top Links
* link:task_deploying_overview.html[Deploying cloud services on NetApp HCI overview]
* link:concept_architecture_cloudinsights.html[Real-time analytics with NetApp Cloud Insights]


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* https://docs.netapp.com/us-en/hybridcloudsolutions/[Hybrid Cloud Solutions documentation^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
