---
sidebar: sidebar
permalink: task_deploying_overview.html
summary: Deploying NetApp HCI involves using NetApp Kubernetes Service.
keywords: netapp, hci, on premise, cloud services
---

= Deploying cloud services on NetApp HCI overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp HCI​ installations connect to, register with, and become a deployable region with NetApp Cloud Central. Then, you can centrally manage Cloud Services for NetApp HCI on prem systems in the same way that you do in public clouds.

== Deployment overview

Deploying and configuring a NetApp HCI solution in the cloud involves these steps.  And, our updated user interfaces help you every step of the way:

* Deploy and configure NetApp HCI using the quick and easy NetApp Deployment Engine that you’ve used previously. [Link to NDE Guide in Doc Center]
* link:task_enabling_cloud_services.html[Enable cloud services] using the updated management node along with a new NetApp Hybrid Cloud Control wizard. You establish a connection to NetApp Cloud Central and authenticate and register your NetApp HCI installation to your Cloud Central account.
* link:task_NKS_create_cluster.html[Create a Kubernetes cluster] using the NetApp Kubernetes Service, one of many services located on NetApp Cloud Central.
* link:task_cvs_create_cloud_volumes.html[Create cloud volumes] using NetApp Cloud Volumes Service, another service on NetApp Cloud Central.

== What happens behind the scenes?

Behind the scenes, NetApp HCI creates a bootstrap agent that establishes the initial communication tunnel to the NetApp Kubernetes Service Controller, builds a temporary bootstrap cluster, and creates a service cluster. The service cluster, connected to NetApp Kubernetes Service, acts as a service orchestrator to deploy services and update itself.

The NetApp Kubernetes Service agent maintains the tunnel, creates user clusters, and maintains previously deployed services.


*	nnn
*	nnn
*	nnn
*	nnn
*	nnn
*	nnn




[discrete]
== Top Links
* link:cloud_volumes_service/snapshot_cloud_volumes.html[Durability, Availability, Encryption and Snapshots on Cloud Volumes Service]
* link:cloud_volumes_ontap/networking_cloud_volumes_ontap.html[NetApp Cloud Volumes ONTAP And Enhanced Networking Support]
* link:NPS/gdpr_and_hybrid_cloud.html[GDPR and Hybrid Cloud: A More Perfect Union]

[discrete]
== Find more information

* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://www.netapp.com/us/forms/campaign/register-for-netapp-cloud-volumes-for-aws.aspx?hsCtaTracking=4f67614a-8c97-4c15-bd01-afa38bd31696%7C5e536b53-9371-4ce1-8e38-efda436e592e[Get a first look at the new NetApp Cloud Volumes Service for AWS^]
