---
sidebar: sidebar
permalink: task_deploying_overview.html
summary: Deploying NetApp HCI involves using NetApp Kubernetes Service.
keywords: netapp, hci, on premise, cloud services
---

= Deploying NetApp HCI in the cloud
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp HCI​ installations connect to, register with, and become a deployable region with NetApp Cloud Central. Then, you can centrally manage Cloud Services for NetApp HCI on prem systems in the same way that you do in public clouds.

== Deployment overview

Deploying and configuring a NetApp HCI solution in the cloud involves these steps.  And, our updated user interfaces help you every step of the way:

* Deploy and configure NetApp HCI using the quick and easy NetApp Deployment Engine that you’ve used previously.
* Using the updated management node along with a new NetApp Hybrid Cloud Control wizard, you enable cloud services, establish a connection to NetApp Cloud Central, and then authenticate and register your NetApp HCI installation to your Cloud Central account.
* Manage your NetApp HCI clusters using NetApp Cloud Volumes Service, one of many services located in NetApp Cloud Central.

== What happens behind the scenes?

Behind the scenes, NetApp HCI creates a bootstrap agent that establishes the initial communication tunnel to the NetApp Kubernetes Service Controller, builds a temporary bootstrap cluster, and creates a service cluster. The service cluster, connected to NetApp Kubernetes Service, acts as a service orchestrator to deploy services and update itself.

The NetApp Kubernetes Service agent maintains the tunnel, creates user clusters, and maintains previously deployed services.

== Deploying NetApp HCI with the NetApp Deployment Engine.
(brief description and then link to doc)

== Enabling cloud services with the management networking_cloud_volumes_ontap
(brief description and then link to our NKS wizard > enable cloud services doc)

== Viewing new clusters in NetApp Cloud Volumes Services
(brief description of how HCI shows in CVS. Or, describe steps you have to do in CVS to have HCI clusters show up.
  Link to CVS docs)

*	nnn
*	mmm
*	nnn
*	nnn
*	abc
*	nnn




[discrete]
== Top Links
* link:cloud_volumes_service/snapshot_cloud_volumes.html[Durability, Availability, Encryption and Snapshots on Cloud Volumes Service]
* link:cloud_volumes_ontap/networking_cloud_volumes_ontap.html[NetApp Cloud Volumes ONTAP And Enhanced Networking Support]
* link:NPS/gdpr_and_hybrid_cloud.html[GDPR and Hybrid Cloud: A More Perfect Union]

[discrete]
== Find more information

* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://www.netapp.com/us/forms/campaign/register-for-netapp-cloud-volumes-for-aws.aspx?hsCtaTracking=4f67614a-8c97-4c15-bd01-afa38bd31696%7C5e536b53-9371-4ce1-8e38-efda436e592e[Get a first look at the new NetApp Cloud Volumes Service for AWS^]
