---
sidebar: sidebar
permalink: task_getting_a_netapp_kubernetes_service_api_token.html
summary: Enabling cloud services for NetApp HCI requires a NetApp Kubernetes Service API token that is associated with your NetApp Cloud Central account.
keywords: netapp, hci, on premise, cloud services
---

= Getting a NetApp Kubernetes Service API token
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Enabling cloud services for NetApp HCI requires a NetApp Kubernetes Service API token that is associated with your NetApp Cloud Central account.

You can complete these steps before enabling cloud services or during the process, when a wizard displays a link to get the API token.

== Steps

. Open a web browser and browse to NetApp Cloud Central for NetApp Kubernetes Service. https://nks.netapp.io
. Log in to the NetApp Kubernetes Service by providing the NetApp HCI storage cluster administrator credentials.
+
If you do not have an account, click *Sign Up* and provide the required information.
. Click *Go to Cloud Data Services* and select *NetApp HCI*.
. Click the user icon at the top right of the screen.
. In the resulting menu, click *Edit Profile*.
. In the API Tokens section, click *Add Token*, enter a token name, and click *Create*.
+
A new token is created; the cURL command changes to include the new token string.
. Run the displayed cURL command in a Unix or Mac command terminal.
+
A response of [] indicates that the token registration was a success.
. Copy the token and save it in a file so that you can later paste it when needed.




[discrete]
== Top Links
* link:task_deploying_overview.html[Deploying cloud services on NetApp HCI overview]
* link:concept_architecture_cloudinsights.html[Real-time analytics with NetApp Cloud Insights]


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* https://docs.netapp.com/us-en/hybridcloudsolutions/[Hybrid Cloud Solutions documentation^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
