---
sidebar: sidebar
permalink: task_mnode_updating_management_services.html
summary: Here's how you can update NetApp HCI management services using the management node.
keywords: netapp, hci, on premise, cloud services, mnode, management services
---

= Updating management services with the management node
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Element 11.3 management node is based on a new modular architecture that provides individual services. You can manually update management services using the REST API UI from the management node. Management services updates are available as service bundles from an online software repository.

.About this task

These modular services provide central and extended management functionality for NetApp HCI and SolidFire all-flash storage systems. Services include system telemetry, logging, and update services, the QoSSIOC service for Element Plug-in for vCenter Server, as well as capabilities relevant to on-premises cloud solutions, such as NetApp Hybrid Cloud Control and the NetApp Kubernetes Service, provided by NetApp HCI.

You should perform management services updates from the NetApp Deployment Engine monitoring page.

Management services include the SIOC service for the Element Plug-in for vCenter, the Active IQ collector service, the NetApp HCI monitoring service (for NetApp HCI installations only) and additional services. Updates to non-service-based components of the management node are provided as updated images (OVA or ISO) and cannot be updated using this procedure.

.Steps

. Open the REST API UI on the management node: 'https://[management node IP]/mnode'
. Click *Authorize* and complete the following:
.. Enter the cluster user name and password.
.. Enter the client ID as mnode-client if the value is not already populated.
.. Copy the token URL string and paste it into another browser tab to initiate a token request.
.. Click *Authorize* to begin a session.
.	(Optional) Confirm available versions of management node services: 'GET /services/versions'
. (Optional) Get detailed information about the latest version: 'GET /services/versions/latest'
.	(Optional) Get detailed information about a specific version: 'GET /services/versions/{version}/info'
. Perform one of the following management services update options:
.. Update to the most recent version of management node services: 'PUT /services/update/latest'
.. Update to a specific version of management node services: 'PUT /services/update/{version}''
. Monitor the status of the update: 'GET/services/update/status'

.Results
A successful update returns a result similar to the following example:
''{
    "current_version": "2.0.442",
    "details": "Updated to version 2.0.442",
    "status": "success"
}''

[discrete]
== Top Links
* link:task_deploying_overview.html[Deploying cloud services on NetApp HCI overview]
* link:concept_architecture_cloudinsights.html[Real-time analytics with NetApp Cloud Insights]


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* https://docs.netapp.com/us-en/hybridcloudsolutions/[Hybrid Cloud Solutions documentation^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
