---
sidebar: docs_sidebar
permalink: docs/concept_licensing.html
summary: Before you begin using Cloud Volumes on NetApp HCI, you will need to obtain licenses..
keywords: netapp, hci, kubernetes, on premise, cloud services, cluster
---

= Licensing requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you begin using Cloud Volumes on NetApp HCI, you will need to obtain licenses. You can obtain the licenses before or during the use of the Cloud Services wizard.

The Cloud Services wizard provides a link to obtain the licenses; however, you will need your software license serial numbers. You can get the serial numbers from the NetApp Support Site at mysupport.netapp.com.



== Licensing requirements for Cloud Volumes on NetApp HCI
Because Cloud Volumes on NetApp HCI is supported by NetApp ONTAP HA clusters and each requires a license, Cloud Volumes on NetApp HCI requires two “ONTAP Select Premium” licenses.

The NetApp licensing files use the following format:

NLF<serialnumber>.txt

NOTE: Fabric Orchestrator is in Preview mode. When you enable Cloud Volumes on NetApp HCI, you automatically have access to the Preview environment.

== Licensing requirements for NetApp Kubernetes Service
NetApp Kubernetes Service does not require an additional license.

NetApp Kubernetes Service is metered and billed by the number of worker nodes in the managed Kubernetes clusters. While these Kubernetes worker nodes are virtual machines that are running on a cluster and NetApp HCI compute nodes, the number of physical compute nodes in the NetApp HCI environment are an unrelated entity for metering and billing purposes.

[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
