---
sidebar: docs_sidebar
permalink: docs/concept_hci_product_overview.html
summary:
keywords: netapp, hci, on premise, cloud,
---

= NetApp HCI product overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help

[.lead]
NetApp HCI is an enterprise-scale hybrid cloud infrastructure design that combines storage, compute, networking, and hypervisor—and adds capabilities that span public and private clouds.

NetApp’s disaggregated hybrid cloud infrastructure allows independent scaling of compute and storage, adapting to workloads with guaranteed performance.

* Meets hybrid multicloud demand
* Scales compute and storage independently
* Simplifies data services orchestration across hybrid multiclouds

== NetApp HCI architecture
The following illustration shows the various components of the NetApp HCI environment:

INSERT IMAGE HERE.
INCLUDE DESCRIPTIONS FOR WHAT IS IN THE IMAGE.

== NetApp HCI URLs
The following table includes the descriptions for the URLs that you use in NetApp HCI:

[%header,cols=2*]
|===
|URL
|Description

|https://<ManagementNodeIP>
|Access NetApp Hybrid Cloud Control to upgrade, expand, and monitor your NetApp HCI installation, and update management services.

|https://[IP address]:442
|From the per-node UI, access network and cluster settings and utilize system tests and utilities.

|https://[management node IP]:9443
|Register the vCenter Plug-in package in the vSphere Web Client.
|===

[discrete]
== Find more information
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
