---
sidebar: docs_sidebar
permalink: docs/concept_types_cloudservices.html
summary: NetApp HCI supports several cloud services.
keywords: netapp, hci, on premise, cloud services
---

= Types of cloud services on NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The following NetApp cloud services are supported on NetApp HCI.

* *NetApp Kubernetes Service*: You must use NetApp Kubernetes Service (NKS), a SaaS platform that enables you to deploy a Kubernetes cluster in the cloud with the major cloud providers and also with NetApp private cloud. This is required to enable cloud services on NetApp HCI. This service is installed as VMs on a NetApp HCI compute node or nodes.
+
See link:task_nks_overview.html[Managing Kubernetes clusters on NetApp HCI overview] information.
* *NetApp Cloud Insights*: This service will enable you to monitor cloud services on NetApp HCI. _Coming soon_.


*NetApp Fabric Orchestrator* provides a centralized storage and data management control plane for fabric-wide, multi-cloud visibility, monitoring, policies, administration and workflow orchestration for NetApp storage systems on-premises and in the cloud.
Using NetApp Fabric Orchestrator, you can discover, manage, and govern your storage assets and data estate, anywhere. Use Fabric Orchestrator to create and manage Cloud Volumes on NetApp HCI.


== Notice of functional preview

Some cloud services might be available as a functional preview. While in preview, the services are only for non-production environments and noncommercial use. By participating in the preview, participants agree to be bound by the cloud services link:https://www.netapp.com/us/media/cloud-data-services-terms.pdf[terms of service].

== Differences between preview and production modes
Some cloud services are provided in a preview mode. While in preview, the services are only for non-production environments and noncommercial use.


=== NetApp Kubernetes Service preview and production modes

.Load balancing
* *Preview mode*: Does not provide load balancing, which impacts Helm charts. Many Kubernetes applications and Helm charts require load balancing for resiliency and scalability.
* *Production mode*: Provides load balancing for Kubernetes pods. The load balancing provides basic resiliency and scalability and enables application management and Helm chart features.

.Multiple master Kubernetes cluster support
* *Preview mode*: Supports only single master Kubernetes clusters, which in turn does not enable resiliency.
* *Production mode*: Supports multiple master clusters that provide resiliency for both the service cluster and user clusters.


[discrete]
== Top Links
* link:task_deploying_overview.html[Deploying cloud services on NetApp HCI overview]
* https://www.netapp.com/us/media/cloud-data-services-terms.pdf[Functional Preview Terms of Service^]

[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/kubernetes-service/[NetApp Kubernetes Service Documentation^]
