---
sidebar: sidebar
permalink: docs/concept_hci_volume_access_groups.html
summary: Learn about volume access groups and how you can use them to access and manage volumes.
keywords: netapp, hci, storage volume, solidfire volume, element volume, persistent volume, access group
---

= Volume access groups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
A volume access group is a collection of volumes that users can access using either iSCSI or Fibre Channel initiators.

By creating and using volume access groups, you can control access to a set of volumes. When you associate a set of volumes and a set of initiators with a volume access group, the access group grants those initiators access to that set of volumes.

Volume access groups have the following limits:

* A maximum of 128 initiators per volume access group.
* A maximum of 64 access groups per volume.
* An access group can be made up of a maximum of 2000 volumes.
* An IQN or WWPN can belong to only one volume access group.

== Find more information
* link:task_hcc_manage_vol_access_groups.html[Manage volume access groups^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* http://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element Software Documentation Center^]
