---
sidebar: docs_sidebar
permalink: docs/concept_cluster_types.html
summary: NetApp HCI with NetApp Kubernetes Service shows you different types of clusters.
keywords: netapp, hci, on premise, kubernetes, cloud services, cluster
---

= Cluster types in cloud services on NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You'll encounter different types of clusters when using cloud services on NetApp HCI.


* *Service cluster*: Connected to NetApp Kubernetes Service (NKS), a service cluster acts as an orchestrator to deploy services and update itself. The service cluster is a set of compute nodes and storage resources that form a Kubernetes environment. Each cluster has at least one master node, which is responsible for overall management of the cluster, and three worker nodes, on which containers are scheduled to execute. Service clusters are for internal NKS use and are not available for running your applications. Service clusters are not listed in the NKS UI. Service clusters should not be modified or deleted. 

* *User cluster*: These are workload clusters on which you add any number of applications. These clusters are maintained in NetApp Kubernetes Service.

[discrete]
== Find more information
* https://docs.netapp.com/us-en/kubernetes-service/[NetApp Kubernetes Service documentation^]
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
