---
sidebar: sidebar
permalink: docs/concept_hcc_expandoverview.html
summary: You can expand your NetApp HCI system using NetApp Hybrid Cloud Control.
keywords: NetApp, HCI, on premise, expand, hcc, hybrid cloud control
---

= Expansion overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help

[.lead]
You can expand your NetApp HCI system by using NetApp Hybrid Cloud Control. You can expand storage or compute resources separately or expand them at the same time.

NOTE: New and spare H610S storage nodes might have additional installation requirements based on the existing Element software version of the storage cluster. Contact NetApp Support for more information.

After installing the node in the NetApp HCI chassis, you use NetApp Hybrid Cloud Control to configure NetApp HCI to use the new resources. NetApp HCI detects the existing network configuration and offers you configuration options within the existing networks and VLANs, if any.

NOTE: If you recently expanded your installation and the new assets were not added automatically to your configuration, you might need to add the assets manually.
See link:task_mnode_work_overview.html[Management node overview].

NetApp HCI uses VMware Enhanced vMotion Compatibility (EVC) to ensure vMotion functionality when there are compute nodes with different CPU generations in the vSphere cluster. When EVC is required for expansion, NetApp HCI enables it automatically whenever possible.

In the following situations, you might need to manually change EVC settings in the vSphere client to complete expansion:

* The existing compute nodes have a newer CPU generation than the compute nodes you are trying to add.
* The controlling vCenter instance does not support the required EVC level.
* The compute nodes you are trying to add have an older CPU generation than the EVC setting of the controlling vCenter instance.

NOTE: When expanding NetApp HCI compute or storage resources in the NetApp Deployment Engine, you should connect to the vCenter instance that manages your existing NetApp HCI compute nodes.

[discrete]
== Find more information
* link:task_hcc_expand_compute.html[Expand NetApp HCI compute resources]
* link:task_hcc_expand_storage.html[Expand NetApp HCI storage resources]
* link:task_hcc_expand_compute_and_storage.html[Expand NetApp HCI storage and compute resources at the same time]
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
*	https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
