---
sidebar: docs_sidebar
permalink: docs/concept_cg_hci_security.html
summary: When you use NetApp HCI, your data is protected by industry-standard security protocols.
keywords: netapp, hci, security
---

= NetApp HCI security
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
When you use NetApp HCI, your data is protected by industry-standard security protocols.

== Encryption at Rest for storage nodes

NetApp HCI enables you to encrypt all data stored on the storage cluster.

All drives in storage nodes that are capable of encryption use AES 256-bit encryption at the drive level. Each drive has its own encryption key, which is created when the drive is first initialized. When you enable the encryption feature, a storage-cluster-wide password is created, and chunks of the password are then distributed to all nodes in the cluster. No single node stores the entire password. The password is then used to password-protect all access to the drives. You need the password to unlock the drive, and since the drive is encrypting all data, your data is secure at all times.

When you enable Encryption at Rest, performance and efficiency of the cluster is not affected. Additionally, if you remove an encryption-enabled drive or node from the storage cluster with the Element API or Element UI, Encryption at Rest is disabled on the drives and the drives are securely erased, protecting the data that was previously stored on those drives. After you remove the drive, you can securely erase the drive with the `+SecureEraseDrives+` API method. If you forcibly remove a drive or node from the storage cluster, the data remains protected by the cluster-wide password and the drive’s individual encryption keys.

For information on enabling and disabling Encryption at Rest, see http://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-ug/GUID-EE404D52-B621-4DE5-B141-2559768FB1D0.html[Enabling and disabling encryption for a cluster] in the SolidFire and Element Documentation Center.

== External key management

You can configure Element software to use a third-party KMIP-compliant key management service (KMS) to manage storage cluster encryption keys. When you enable this feature, the storage cluster's cluster-wide drive access password encryption key is managed by a KMS that you specify.
NetApp EExternal Key Management can use the following key management services:

* Gemalto SafeNet KeySecure
* SafeNet AT KeySecure
* HyTrust KeyControl
* Vormetric Data Security Manager
* IBM Security Key Lifecycle Manager

For more information on External Key Management, see http://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-ug/GUID-057D852C-9C1C-458A-9161-328EDA349B00.html[Getting started with External Key Management] in the SolidFire and Element Documentation Center.

== Multi-factor authentication

Multi-factor authentication (MFA) enables you to require users to present multiple types of evidence to authenticate with the NetApp Element web UI or storage node UI upon login. You can configure Element to accept only multi-factor authentication for logins integrating with your existing user management system and identity provider.
You can configure Element to integrate with an existing SAML 2.0 identity provider which can enforce multiple authentication schemes, such as password and text message, password and email message, or other methods.

You can pair multi-factor authentication with common SAML 2.0 compatible identity providers (IdPs), such as Microsoft Active Directory Federation Services (ADFS) and Shibboleth.

To configure MFA, see http://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-ug/GUID-B1C8D8E2-CE95-41FD-9A3E-A0C424EC84F3.html[Enabling multi-factor authentication] in the SolidFire and Element Documentation Center.
