---
sidebar: docs_sidebar
permalink: docs/concept_kubernetes_pods_volumes_projects.html
summary: Cloud services on NetApp HCI involves pods, volumes, and projects that you create and manage by using the NetApp Kubernetes Service.
keywords: netapp, hci, on premise, kubernetes, cloud services, cluster
---

= Kubernetes terminology
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Cloud services on NetApp HCI involves pods, volumes, and projects that you create and manage by using the NetApp Kubernetes Service (NKS). Persistent volumes are managed by Trident software.



* *NKS workspace*: The NKS _workspace_ enables you to group together projects, teams, and members. This lets you tailor access to the exact needs of a group of users. For example, you may want to allow a certain team access to build and manage clusters at one particular provider. This can be accomplished by creating a workspace for that team (or teams). Then assign specific Provider Credentials to that workspace.
* *NKS clusters*: NKS enables you to create and manage _clusters_ at the provider of your choice. You can customize defaults, such as the region, size, and number of nodes. And, you can add packaged Helm charts.
* *NKS pod*: A _pod_ is the NKS atomic unit. It is the smallest unit that can be deployed. A pod consists of one or more containers that share the same namespace, IP addresses, and volume. It can exist only on a single node.
* *NKS project*: An NKS _project_ is a construct for grouping applications, for example, Wordspace or MySQL. A project is a namespace with RBAC on the Kubernetes cluster. Projects are the heart of application lifecycle management. Clusters can have many projects, and each project can have many solutions, including applications and packages. Clusters can represent different environments, like a test, staging, and production environment. In this case, each cluster environment will be running a similar version of the same project.
* *Solutions on NKS*: With NKS, you can move workloads with predesigned solutions or applications to the cloud platform that suits your needs, with any of the major hyperscalers or an on-premises environment. This list of open-source technologies includes:
** fabric8
** GitLab
** Helm
** Istio
** Linkerd
** Prometheus

** Trident is another solution that’s preinstalled with the NetApp Kubernetes Service. With Trident, NetApp solutions such as Cloud Volumes Service can meet persistent volume claims that are made by Kubernetes clusters.
* *NKS volume*: An NKS _volume_ is storage provisioned directly to a pod. NKS supports a wide variety of volume types, including Amazon EBS, Azure Disk Storage, volumes managed by NetApp Element, NFS, and many more. Volumes enable the containers within a pod to share information and are destroyed when their parent pod is deleted.


== Trident software and persistent storage
* *Persistent storage*: With NKS, you can use a _persistent volume_, one that exists independently of any specific pod and with its own lifetime. Persistent volumes can be used to support stateful applications, such as database services, enabling all components of an enterprise solution to be deployed and managed by NKS. Using Trident to manage persistent volume claims (PVCs) insulates the developers creating pods from the lower-level implementation details of the storage that they are accessing.
* *Trident software with NKS*: The NetApp Kubernetes Service on NetApp HCI employs Trident software to provision storage automatically to containerized applications. Trident is automatically deployed and configured when new NKS clusters are created. When a containerized application issues a PVC request, Trident dynamically provisions storage per the parameters requested against the NetApp Element software storage layer in NetApp HCI.

Trident, itself a Kubernetes-native application, runs directly within a Kubernetes cluster. With Trident, Kubernetes users (such as developers, data scientists, and Kubernetes administrators) can create, manage, and interact with persistent storage volumes in the standard Kubernetes format that they are already familiar with.

With Trident, NetApp solutions such as Cloud Volumes Service can meet persistent volume claims that are made by Kubernetes clusters

For details, visit the https://netapp.io/persistent-storage-provisioner-for-kubernetes/[Trident website].

[discrete]
== Find more information
* https://docs.netapp.com/us-en/kubernetes-service/[NetApp Kubernetes Service documentation^]
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
