---
sidebar: docs_sidebar
permalink: docs/concept_rancher_general_requirements.html
summary: Learn about the general requirements your environment needs to meet before you install Rancher on NetApp HCI.
keywords: netapp, hci, Rancher, install, general, requirements
---

= General requirements for Rancher on NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you install Rancher on NetApp HCI, ensure your environment and your NetApp HCI system meet these general requirements.

* Ensure that your NetApp HCI system has at least 3 compute nodes; this is required for full resiliency. Rancher on NetApp HCI is not supported on storage-only configurations.
* Ensure that you have allocated the necessary static IP addresses for Rancher control plane (Rancher Server) and the user (k8s) clusters.
** Rancher Server requires 3 static IP addresses.
** Each user cluster requires 1 static IP address.
* Ensure that you have set up DNS records for each static IP address you need.
* Create a DNS entry for the Rancher URL that you will use to access the host from which the Rancher web UI is served once the installation is complete.
* Ensure that the VMware vSphere instance you are using is equipped with a vSphere Enterprise Plus license.
* As a best practice, ensure that the VMware vSphere instance you are using is configured to use VMware vSphere Distributed Switch (VDS) rather than vSphere Standard Switch VSS. You can use VSS, but if you do, ensure that the virtual switches and physical hosts used for Rancher VMs can access all the same port groups, in the same way that you would ensure for regular VMs.
* Ensure you deploy Rancher on NetApp HCI on a network that has management access.

NOTE: If you accidentally deploy Rancher on NetApp HCI with incorrect information (such as an incorrect Rancher URL), there is no way to correct the installation without redeploying. You will need to remove the Rancher on NetApp HCI instance using the REST API and then redeploy Rancher on NetApp HCI from NetApp Hybrid Cloud Control UI. See troubleshooting << URL NEEDED >> for more information.
