---
sidebar: docs_sidebar
permalink: docs/concept_licensing.html
summary: Before you begin using Cloud Volumes on NetApp HCI, you will need to obtain licenses..
keywords: netapp, hci, kubernetes, on premise, cloud services, cluster
---

= Licensing requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you begin using Cloud Volumes on NetApp HCI, you will need to obtain licenses. You can obtain the licenses before or during the use of the Cloud Services wizard.

The Cloud Services wizard provides a link to obtain the licenses; however, you will need your software license serial numbers. You can get the serial numbers from the NetApp Support Site at
mysupport.netapp.com.


== Licensing requirements for Cloud Volumes on NetApp HCI
Because Cloud Volumes on NetApp HCI is supported by NetApp ONTAP HA clusters and each requires a license, Cloud Volumes on NetApp HCI requires two “ONTAP Select Premium” licenses.

The NetApp licensing files use the following format:

'NLF<serialnumber>.txt'

== Licensing requirements for NetApp Kubernetes Service
NetApp Kubernetes Service does not require an additional license.


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
