---
sidebar: docs_sidebar
permalink: docs/concept_rancher_concepts.html
summary: Learn about tasks you might need to perform after installing Rancher on NetApp HCI.
keywords: netapp, hci, rancher, control plane, catalog, cluster, kubernetes
---

= Rancher on NetApp HCI concepts
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn basic concepts related to Rancher on NetApp HCI.

* *Rancher server* or *Control plane*: The Rancher control plane, sometimes called the _Rancher Server_, provisions, manages, and monitors Kubernetes clusters used by Development and Operations teams.

* *Catalogs*: Catalogs are GitHub repositories or Helm Chart repositories filled with applications that are ready-made for deployment. Rancher provides the ability to use a catalog of Helm charts that make it easy to deploy applications repeatedly. Rancher includes two types of catalogs: built-in global catalogs and custom catalogs. Trident is deployed as a catalog.  See https://rancher.com/docs/rancher/v2.x/en/helm-charts/legacy-catalogs/[Rancher documentation about catalogs].

* *Management cluster*: Rancher on NetApp HCI deploys three virtual machines on the Rancher management cluster, which you can see using Rancher, Hybrid Cloud Control, and the vCenter Plug-in. The management cluster virtual machines host the Rancher server, the Rancher Kubernetes Engine (RKE), and the Linux OS.

* *User clusters*: These downstream Kubernetes clusters run your apps and services. In Kubernetes installations of Rancher, the management cluster should be separate from the user clusters. Any cluster that a Rancher user deploys from Rancher, or imports into Rancher, would be considered a user cluster.

* *Rancher node template*: Hybrid Cloud Control uses a Rancher node template to make deployment simpler.

+
See  https://rancher.com/docs/rancher/v2.x/en/user-settings/node-templates/[Rancher documentation about node templates].

* *Management service for Kubernetes*: This NetApp HCI service enables you to manage Kubernetes clusters deployed with NetApp Hybrid Cloud Control and Rancher. The service is installed as virtual machines on a NetApp HCI compute node or nodes.

== Trident software and persistent storage concepts
Trident, itself a Kubernetes-native application, runs directly within a Kubernetes cluster. With Trident, Kubernetes users (such as developers, data scientists, and Kubernetes administrators) can create, manage, and interact with persistent storage volumes in the standard Kubernetes format that they are already familiar with. With Trident, NetApp solutions can meet persistent volume claims that are made by Kubernetes clusters.

With Rancher, you can use a persistent volume, one that exists independently of any specific pod and with its own lifetime. Using Trident to manage persistent volume claims (PVCs) insulates the developers creating pods from the lower-level implementation details of the storage that they are accessing.

A Trident catalog is available to Rancher on NetApp HCI. When a containerized application issues a persistent volume claim (PVC) request, Trident dynamically provisions storage per the parameters requested against the NetApp Element software storage layer in NetApp HCI.

For details, visit the https://netapp-trident.readthedocs.io/en/stable-v20.10/introduction.html[Trident documentation].

[discrete]
== Find more information
* https://rancher.com/docs/rancher/v2.x/en/overview/architecture/[Rancher documentation about architecture^]
* https://rancher.com/docs/rancher/v2.x/en/overview/concepts/[Kubernetes terminology for Rancher]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
