---
sidebar: sidebar
permalink: docs/hci_prereqs_deployment_restriction.html
summary: Learn about NetApp HCI Witness Node requirements.
keywords: netapp, hci, element, Witness Node
---

= Deployment configuration restrictions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, hci, element, Witness Node

[.lead]
Certain configurations are restricted in the NetApp Deployment Engine depending on the WMware vSphere version, the compute node type, and the number of storage nodes. The restricted configurations apply to VMware vSphere 7.0 with H610C or H614C compute nodes and two or three storage nodes. If you want to proceed with a restricted configuration, you must select a different vSphere version, such as vSphere 6.7, or prevent the deployment of Witness Nodes by having a minimum of four storage nodes in the configuration.

If you select a restricted configuration from the Inventory page during deployment, an error message appears that indicates alternative valid configuration options.

[discrete]
== Find more information
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
*	https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
