---
sidebar: sidebar
permalink: docs/hci_prereqs_ip_address.html
summary: Learn about NetApp HCI IP address requirements.
keywords: netapp, hci, IP address, requirements
---

= IP address requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, hci, IP address, requirements

[.lead]
NetApp HCI has specific IP address requirements that depend on the size of your deployment. Note that by default the initial IP addresses you assign to each node before using the NetApp Deployment Engine to deploy the system are temporary and cannot be reused. You need to set aside a second permanent set of unused IP addresses that you can assign during final deployment.

== Number of IP addresses needed per NetApp HCI deployment
The NetApp HCI storage network and management network should each use separate contiguous ranges of IP addresses. Use the following table to determine how many IP addresses you need for your deployment:

|===
|System component  |Management network IP addresses needed |Storage network IP addresses needed |vMotion network IP addresses needed | Total IP addresses needed per component

|Compute node
|1
|2
|1
|4

|Storage node
|1
|1
|
|2

|Storage cluster
|1
|1
|
|2

|VMware vCenter
|1
|
|
|1

|Management node
|1
|1
|
|2

|Witness Node
|1
|1
|
|2 per Witness Node (two Witness Nodes are deployed for each two-node or three-node storage cluster)
|===

== IP addresses reserved by NetApp HCI
NetApp HCI reserves the following IP address ranges for system components. When planning your network, avoid using these IP addresses:

|===
|IP address range |Description

|10.0.0.0/24
|Docker overlay network

|10.0.1.0/24
|Docker overlay network

|10.255.0.0/16
|Docker swarm ingress network

|169.254.100.1/22
|Docker bridge network

|169.254.104.0/22
|Docker bridge network
|===

[discrete]
== Find more information
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
*	https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
