---
sidebar: sidebar
permalink: docs/hci_prereqs_deployment_configuration_restriction.html
summary: Learn about deployment configuration restrictions.
keywords: netapp, hci, deployment, restriction, configuration, nde, compute, node, storage
---

= Deployment configuration restrictions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, hci, element, Witness Node

[.lead]
Certain configurations are restricted in the NetApp Deployment Engine depending on the VMware vSphere version, the compute node type, and the number of storage nodes. The restricted configurations apply to VMware vSphere 7.0 with H610C or H615C compute nodes and two or three storage nodes. If you want to proceed with a restricted configuration, you must select a different vSphere version, such as vSphere 6.7, or prevent the deployment of Witness Nodes by having a minimum of four storage nodes in the configuration.

If you link:task_nde_select_inventory.html[select a restricted configuration from the *Inventory* page] during deployment, an error message appears with alternative valid configuration options.

[discrete]
== Find more information
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
*	https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
