---
sidebar: sidebar
permalink: docs/hci_prereqs_network_cables.html
summary: Learn about NetApp HCI network cable requirements.
keywords: netapp, hci, network, cable, requirements
---

= Network cable requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use the following guidelines to ensure that you have enough of the right type of network cables for the size of your deployment. For RJ45 ports, you must use Cat 5e or Cat 6 rated cables.

* Two-cable compute node configuration: Each compute node must to be connected to a 10/25GbE network via two SFP+/SFP28 interfaces (one additional Cat 5e/6 cable is optional for out-of-band management).
* Six-cable compute node configuration: Each compute node must to be connected to a 10/25GbE network via four SFP+/SFP28 interfaces and to a 1/10GbE network via two Cat 5e/6 cables (one additional Cat 5e/6 cable is optional for out-of-band management).
* Each storage node must be connected to a 10/25GbE network via two SFP+/SFP28 interfaces and to a 1/10GbE network via two Cat 5e/6 cables (one additional Cat 5e/6 cable is optional for out-of-band management).
* Ensure the network cables you use to connect the NetApp HCI system to your network are long enough to comfortably reach your switches.

For example, a deployment containing four storage nodes and three compute nodes (using the six-cable configuration) requires the following number of network cables:

* (14) Cat 5e/6 cables with RJ45 connectors (plus seven cables for IPMI traffic, if desired)
* (20) Twinax cables with SFP28/SFP+ connectors

This is due to the following reasons:

* Four storage nodes require eight (8) Cat 5e/6 cables and eight (8) Twinax cables.
* Three compute nodes using the six-cable configuration require six (6) Cat 5e/6 cables and twelve (12) Twinax cables.

NOTE: In a six-cable configuration, two ports are reserved for VMware ESXi and set up and managed by the NetApp Deployment Engine. You cannot access or manage these ESXi-dedicated ports using the Element TUI or the Element web GUI.

[discrete]
== Find more information
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
*	https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
