---
sidebar: sidebar
permalink: docs/hci_prereqs_network_switch.html
summary: Learn what's new in this version of NetApp HCI.
keywords: netapp, hci, network, switch, requirements
---

= Network and switch requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, hci, network, switch, requirements

[.lead]
The switches you use for NetApp HCI require specific configuration to ensure a successful deployment. See your switch documentation for specific instructions on implementing each of the following requirements for your environment.

A NetApp HCI deployment requires at least three network segments, one for each of the following types of traffic:

* Management
* VMware vMotion
* Storage/Data

Depending on the NetApp H-Series compute and storage node models and the planned cabling configuration, you can physically separate these networks using separate switches or logically separate them using VLANs. For most deployments, however, you need to logically separate these networks (and any other additional virtual machine networks) using VLANs.

Compute and storage nodes need to be able to communicate before, during, and after deployment. If you are implementing separate management networks for storage and compute nodes, ensure that these management networks have network routes between them. These networks must have gateways assigned, and there must be a route between the gateways. Ensure that each new node has a gateway assigned to facilitate communication between nodes and management networks.

NetApp HCI has the following switch requirements:

* All switch ports connected to NetApp HCI nodes must be configured as spanning tree edge ports.
** On Cisco switches, depending on the switch model, software version and port type, you can do this with one of the following commands:
*** `spanning-tree port type edge`
*** `spanning-tree port type edge trunk`
*** `spanning-tree portfast`
*** `spanning-tree portfast trunk`
** On Mellanox switches, you can do this with the `spanning-tree port type edge` command.
* NetApp HCI nodes have redundant ports for all network functions except out-of-band management. For the best resiliency, divide these ports across two switches with redundant uplinks to either a traditional hierarchical architecture or a layer 2 spine-and-leaf architecture.
* The switches handling storage, virtual machine, and vMotion traffic must support speeds of at least 10GbE per port (up to 25GbE per port is supported).
* The switches handling management traffic must support speeds of at least 1GbE per port.
* You must configure jumbo frames on the switch ports handling storage and vMotion traffic. Hosts must be able to send 9000 byte packets end-to-end for a successful installation.
* You must configure the management network switch ports to allow whatever size MTU the management NIC ports on each host are configured for. For example, if the host management network ports use an MTU size of 1750 bytes, the management network switch ports must be configured to allow at least an MTU of 1750 bytes (the management network does not require an MTU of 9000 bytes). The MTU settings should be consistent end-to-end.
* Round-trip network latency between all storage and compute nodes should not exceed 2ms.

All NetApp HCI nodes provide additional out-of-band management capabilities via a dedicated management port. NetApp H300S, H300E, H500S, H500E, H700S, H700E and H410C nodes also allow for IPMI access via Port A. As a best practice, you should ease remote management of NetApp HCI by configuring out-of-band management for all nodes in your environment.

[discrete]
== Find more information
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
*	https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
