---
sidebar: docs_sidebar
permalink: docs/index.html
summary: NetApp HCI provides both storage and compute resources, combining them to build a VMware vSphere environment backed by the capabilities of NetApp Element software.
keywords: netapp, hci, on premise, hybrid cloud control, hcc, kubernetes
---

= NetApp HCI configuration and management documentation
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp HCI provides both storage and compute resources, combining them to build a VMware vSphere environment backed by the capabilities of NetApp Element software.

You can upgrade, expand, and monitor your system with the NetApp Hybrid Cloud Control interface and manage NetApp HCI resources with a vCenter plug-in.

== Discover what's new

* link:rn_whatsnew.html[What's new in NetApp HCI]
* http://docs.netapp.com/sfe-120/index.jsp[What's new in NetApp Element software^]
* https://kb.netapp.com/app/answers/answer_view/a_id/1087586[What's new in management services for Element software and NetApp HCI^]
* What's new in NetApp Element Plug-in for vCenter Server

== Get started with NetApp HCI

* link:task_hci_getstarted.html[NetApp HCI installation and deployment overview]
* link:task_hcc_access.html[Access NetApp Hybrid Cloud Control]
* link:concept_hci_product_overview.html[Review basic concepts]

[discrete]
== Find more information
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
