---
sidebar: docs_sidebar
permalink: docs/index.html
summary: NetApp HCI provides both storage and compute resources, combining them to build a VMware vSphere environment backed by the capabilities of NetApp Element software.
keywords: netapp, hci, on premise, hybrid cloud control, hcc, kubernetes, cloud services
---

= NetApp HCI Management and Cloud Services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp HCI provides both storage and compute resources, combining them to build a VMware vSphere environment backed by the capabilities of NetApp Element software.

You can manage resources with a vSphere plug-in and perform other operations with the NetApp Hybrid Cloud Control interface,

== Performing operations with NetApp Element Plug-in for vCenter Server
After deploying NetApp HCI, you manage storage and compute resources from the VMware vSphere Web Client:

* You manage _storage_ resources, including, datastores, volumes, Quality of Service, storage cluster components, and data protection by using the NetApp Element Plug-in for vCenter Server (also referred to as the vCenter Plug-in or VCP).
* You also manage _compute_ nodes in vSphere. They appear as ESXi hosts.


== Performing operations with NetApp Hybrid Cloud Control
One of the components of NetApp HCI is the NetApp Hybrid Cloud Control interface, which enables you to do the following:

* link:concept_overview.html[Enable Cloud Services on NetApp HCI]
* link:task_hcc_dashboard.html[Monitor your NetApp HCI installation]
* link:concept_hci_upgrade_overview.html[Upgrade your NetApp HCI system]
* link:concept_hcc_expandoverview.html[Expand your NetApp HCI storage or compute resources]

[discrete]
== Find more information
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* link:../../index.html[NetApp Cloud Services and Solutions^]
* https://cloud.netapp.com/home[NetApp Cloud Central^]
