---
sidebar: docs_sidebar
permalink: docs/rancher_prereqs_overview.html
summary: Learn about the requirements for a successful Rancher on NetApp HCI installation.
keywords: netapp, hci, Rancher, install, installation, requirements
---

= Requirements for Rancher on NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you install Rancher on NetApp HCI, ensure your environment and your NetApp HCI system meet these requirements.

NOTE: If you accidentally deploy Rancher on NetApp HCI with incorrect information (such as an incorrect Rancher server FQDN), there is no way to correct the deployment without removing it and redeploying. You will need to remove the Rancher on NetApp HCI instance and then redeploy Rancher on NetApp HCI from NetApp Hybrid Cloud Control UI. See link:task_rancher_remove_deployment.html[troubleshooting^] for more information.

== Node requirements

* Ensure that your NetApp HCI system has at least 3 compute nodes; this is required for full resiliency. Rancher on NetApp HCI is not supported on storage-only configurations.
* Ensure that the datastore you intend to use for the Rancher on NetApp HCI deployment has at least 60GB of free space.
* Ensure that your NetApp HCI cluster is running management services version 2.17.x or later.

=== Node details

Rancher on NetApp HCI deploys a three-node management cluster.

All nodes have the following characteristics:

[cols=3*,options="header",cols="15,15, 15"]
|===
| vCPU
| RAM (GB)
| Disk (GB)
| 2 | 8 | 20
|===

== Network requirements

* Ensure that the network that you intend to deploy the Rancher on NetApp HCI management cluster has a route to the management node management network.
* Ensure that you have allocated the necessary static IP addresses for Rancher control plane (Rancher server) and the user (k8s) clusters.
** Rancher server requires 3 static IP addresses.
** Each user cluster requires 3 static IP addresses.
* If you need to use an HTTP proxy to enable internet access for Rancher on NetApp HCI, you need to make a pre-deployment change to the management node. Log in to your management node using SSH and follow the https://docs.docker.com/config/daemon/systemd/#httphttps-proxy[instructions^] in the Docker documentation to manually update the proxy settings for Docker.
* If you enable and configure a proxy server during deployment, the following IP address ranges and domains are automatically added to the Rancher server noProxy settings:
+
----
127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, .svc, .cluster.local
----
* Ensure that your management node can use DNS to resolve the host name `<any IP address>.nip.io` to an IP address. This is the DNS provider used during deployment; if the management node cannot resolve this URL, deployment will fail.
* Ensure that you have set up DNS records for each static IP address you need.


== VMware vSphere requirements

* Ensure that the VMware vSphere instance you are using is version 6.5 or 7.0.
* Ensure that the VMware vSphere instance you are using is equipped with a vSphere Enterprise Plus license.
* As a best practice, ensure that the VMware vSphere instance you are using is configured to use VMware vSphere Distributed Switch (VDS) rather than vSphere Standard Switch VSS. You can use VSS, but if you do, ensure that the virtual switches and physical hosts used for Rancher VMs can access all the same port groups, in the same way that you would ensure for regular VMs.

== Deployment considerations
You might want to review the following considerations:

* Types of deployments
** Demo deployments
** Production deployments
* Rancher FQDN

TIP: Rancher on NetApp HCI is not resilient to node failures unless you configure some type of network load balancing. As a simple solution, create a round robin DNS entry for the three static IP addresses reserved for Rancher server. These DNS entries should resolve to the Rancher server FQDN that you will use to access the Rancher server host, which serves the Rancher web UI once deployment is complete.

=== Types of deployments
You can deploy Rancher on NetApp HCI in the following ways:

* *Demo deployments*: If DHCP is available in the targeted deployment environment and you want to demo the Rancher on NetApp HCI capability, then a DHCP deployment makes the most sense.
+
In this deployment model, the Rancher UI is accessible from each of the three nodes in the management cluster.

+
If your organization does not use DHCP, you can still try it out by using four static IP addresses allocated prior the deployment, similar to what you would do for a production deployment.

* *Production deployments*: For production deployments or when DHCP is not available in the targeted deployment environment, a little more pre-deployment work is required.  The first step is to obtain three consecutive IP addresses. You enter the first during the deployment.

+
We recommend using L4 load balancing or round-robin DNS configuration for production environments.  This requires a fourth IP address and separate entry in your DNS configuration.

** *L4 load balancing*: This is a technique where a virtual machine or container hosting an application like nginx is configured to distribute requests among the three nodes of the management cluster.
** *Round-robin DNS*: This is a technique where a single host name is configured in the DNS system that rotates requests among the three hosts that form the management cluster.

=== Rancher FQDN

The installation requires assignment of a Rancher URL, which includes the fully qualified domain name (FQDN) of the host where the Rancher UI will be served after the installation is complete.

In all cases the Rancher UI is accessible in your browser over https protocol (port 443).

Production deployments require an FQDN configured that load balances across the management cluster nodes. Without using FQDN and load balancing, the environment is not resilient and is suitable only for demo environments.

== Required ports

The following ports must be open in your firewall configuration to and from the nodes running Rancher server. In addition to this list, ensure that the list of ports in the *RKE* tab of the *Rancher Nodes* section of the official https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ports/[Rancher documentation^] are open as well.

|===
|Port |Description

|443
|Rancher web UI access
|===

== Required URLs

The following URLs should be accessible from the hosts where the Rancher control plane resides:

|===
|URL |Description

|https://charts.jetstack.io/
|No description - 404

|https://releases.rancher.com/server-charts/stable
|No description - empty XML

|https://entropy.ubuntu.com/
|Ubuntu entropy service for random number generation

|https://raw.githubusercontent.com/vmware/cloud-init-vmware-guestinfo/v1.3.1/install.sh
|VMware guest additions install script

|https://download.docker.com/linux/ubuntu/gpg
|Docker Ubuntu GPG public key

|https://download.docker.com/linux/ubuntu
|Docker download link

|https://hub.docker.com/
|Docker hub for NetApp Hybrid Cloud Control
|===
