---
sidebar: docs_sidebar
permalink: docs/rancher_prereqs_overview.html
summary: Learn about the requirements for a successful Rancher on NetApp HCI installation.
keywords: netapp, hci, Rancher, install, installation, requirements
---

= Rancher on NetApp HCI requirements overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
There are things you need to know and preparations you need to make so that you can successfully install Rancher on NetApp HCI. Ensure that you implement the following requirements and recommendations before you install Rancher on NetApp HCI.

Review the standard Rancher installation https://rancher.com/docs/rancher/v2.x/en/installation/requirements/[requirements^], and ensure that they are met alongside these Rancher on NetApp HCI requirements.

* Ensure that your NetApp HCI system has at least 3 compute nodes; this is required for full resiliency. Rancher on NetApp HCI is not supported on storage-only configurations.
* Ensure that you have allocated the necessary static IP addresses for Rancher control plane (Rancher Server) and the user (k8s) clusters.
** Rancher Server requires 3 static IP addresses.
** Each user cluster requires 1 static IP address.
* Ensure that you have set up DNS records for each static IP address you need.
* Create a DNS entry for the main Rancher URL that you will use to access the Rancher control plane.
* Ensure that the VMware vSphere instance you are using is equipped with a vSphere Enterprise Plus license.
* As a best practice, ensure that the VMware vSphere instance you are using is configured to use VMware vSphere Distributed Switch (VDS) rather than vSphere Standard Switch VSS. You can use VSS, but if you do, ensure that the virtual switches and physical hosts used for Rancher VMs can access all the same portgroups, in the same way that you would ensure for regular VMs.
* Ensure you deploy Rancher on NetApp HCI on a network that has management access.
