---
sidebar: docs_sidebar
permalink: docs/reference_nks_storageclasses.html
summary: Before you begin using cloud services on NetApp HCI, look at these prerequisites.
keywords: netapp, hci, kubernetes, nks, storage class, on premise, cloud services
---

= Storage classes with NetApp Kubernetes Service on NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
After you enable cloud services on NetApp HCI and enable NetApp Kubernetes Service (NKS), Kubernetes storage classes are created.

When you add applications in NKS, you need to know the storage class and its provisioner.


== Storage classes with NKS
The following table lists the storage classes and the associated provisioners and IOPS values.

[cols=5*,options="header",cols="25,25,15,15,15"]
|===
| Storage class
| Provisioner
| IOPS minimum
| IOPS maximum
| IOPS burst
| solidfire-bronze | netapp.io/trident | 1000 | 4000 | 6000
| solidfire-silver | netapp.io/trident | 5000 | 25,000 | 40,000
| solidfire-gold | netapp.io/trident |15,000 | 180,000 | 200,000
| vsphere (default) | kubernetes.io/vsphere-volume | NA | NA | NA
|===

== Storage class impact
Storage classes affect storage pools, QoS values, and persistent volume claims in the following ways:

* Each NetApp Element storage class uses a unique storage pool.
* Storage pools are identified by a set of unique QoS (IOPS) values.
* When a Persistent Volume Claim (PVC) uses one of the "solidfire" storage classes, a volume within the referred storage pool is created on Element.
* Trident creates the PV with the storage class and the storage pool attributes.
* Kubernetes mounts the volume to the pod.

== Example of PVC using a storage class

This example shows a volume created with the _solidfire-gold_ storage class IOPS values on Element.
When a pod uses this PVC, the new volume with the _solidfire-gold_ IOPS values is mounted to the pod.

....
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
      name: pvcclaim-gold
spec:
  accessModes:
  - ReadWriteOnce
  resources:
	requests:
	  storage: 10Gi
  storageClassName: solidfire-gold

----
....


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center]
