---
sidebar: docs_sidebar
permalink: docs/reference_requirements_beforeyoubegin.html
summary: Before you begin using cloud services on NetApp HCI, look at these prerequisites.
keywords: netapp, hci, kubernetes, on premise, cloud services
---

= Requirements before you begin with cloud services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you use cloud services on NetApp HCI, you should have completed networking and other requirements.​


== System requirements
* A NetApp HCI 1.6 or later system deployed by the NetApp Deployment Engine (NDE)
* Upgraded NetApp HCI management services. See management services information in the http://docs.netapp.com/sfe-113/topic/com.netapp.doc.sfe-ug/home.html[NetApp Element User Guide^].
* NetApp Hybrid Cloud Control available on the management node of your system
* NetApp HCI management node 2.2 or later (requires updates from the 2.0 version)
* Your version of VMware vCenter supported by the NetApp HCI Deployment Engine
* All nodes must have IP addresses assigned to them by DHCP. A DHCP server must be able to run on all NKS networks.
* The “NetApp-HCI-Datastore-02” datastore must exist in vSphere. It is a requirement for enabling NKS. If the datastore does not exist, the cloud services installation will not be successful. Before enabling cloud services, check vSphere to see that the datastore is there. If you are creating the datastore, it must meet the following conditions: 2 TiB in size, formatted as a VMware Virtual Machine File System (VMFS), shared with all compute hosts, and with the default QoS (or higher).
* Ports must be opened in the firewall as specified in NKS information. https://docs.netapp.com/us-en/kubernetes-service/whitelist-ports-and-ip-addresses.html

NOTE: Running NKS services through a proxy server is not supported.

== Networking requirements
* You must have already configured the required vSphere distributed switches (VDS). VMware standard switches (VSS) are not supported.
* You must have already configured the recommended vSphere distributed switch (VDS) port groups:
** NetApp HCI VDS 01-HCI_Internal_NKS_Management
** NetApp HCI VDS 01-HCI_Internal_NKS_Workload
** NetApp HCI VDS 01-HCI_Internal_NKS_Data
* Using VDS requires a vSphere Enterprise Plus license. You must have this license.

== System size requirements
* 2x4 systems are not supported for production use. However, you can use these for demo work.
* 3x4 systems are the minimum production system size we support.
* 4x4 systems are the recommended minimum size.

== NetApp Kubernetes Service requirements
* A NetApp Kubernetes Service (NKS) account
* A NetApp Kubernetes Service API token, which authorizes the installer to access the NKS organization. You can create this before or during the process of enabling cloud services on NetApp HCI.

== Requirements for Cloud Volumes on NetApp HCI and NetApp Fabric Orchestrator
* An NKS account. NetApp HCI installs the service cluster on NKS, which in turn installs the Kubernetes pods, which is a set of one or more containers used for Cloud Volumes on NetApp HCI.
* All requirements needed for NKS, such as the NKS API token, which authorizes the installer to access the NKS organization.
* Access to the NKS storage system
* A Cloud Central account

== Browser requirements
*	Any modern browser



[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center]
