---
sidebar: docs_sidebar
permalink: docs/task_hcc_collectlogs.html
summary: You can use NetApp Hybrid Cloud Control to collect logs from your NetApp HCI or Element installation to help with troubleshooting.
keywords: netapp, hci, logs, collection, troubleshooting, monitor
---

= NetApp Hybrid Cloud Control configuration capabilities

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

NetApp HCI includes NetApp Hybrid Cloud Control to simplify compute lifecycle and storage management. It supports Element Software upgrades on storage nodes for NetApp HCI and NetApp SolidFire storage clusters, as well as firmware upgrades for NetApp HCI compute nodes in NetApp HCI. It is available by default on the management nodes in NetApp HCI.

In addition to communicating the NetApp-provided hardware and software components in a NetApp HCI installation, Hybrid Cloud Control interacts with third-party components in the customer environment, like VMware vCenter. NetApp qualifies the functionality of Hybrid Cloud Control and its interaction with these third-party components in the customer environment up to a certain scale.  For optimal experience with Hybrid Cloud Control, NetApp recommends staying within the range of configuration capabilities.

If you exceed these tested capabilities, you might experience issues with NetApp Hybrid Cloud Control, such as a slower user interface and API responses or functionality being unavailable. If you engage NetApp for product support with Hybrid Cloud Control in environments that are configured beyond the configuration capabilities, NetApp Support will ask to alter the configuration to be within the documented configuration capabilities.

.Configuration capabilities

|===
|Functional area |Configuration item |Maximum in management services 2.17

.4+|Compute management
|Number of connected VMware vCenter instances
|5


|Sum of ESXi hosts (NetApp branded and third-party) in connected vCenter instances
|500


|Sum of NetApp compute nodes in connected vCenter instances
|500


|Sum of virtual machines in connected vCenter instances
|500

|Storage management
|Number of managed storage clusters
|20
|===
