---
sidebar: sidebar
permalink: docs/rn_firmware_12.2.109.html
summary: Get links to release notes for the firmware packages that you can download and apply to NetApp HCI nodes.
keywords: netapp, hci, compute firmware
---
////
This file isn't included in the sidebar nav system. It is only linked to from the rn_relatedrn.adoc file, and this is by design. It might be a totally poor design, but we're going to try it out. -MW, 6-3-2020
////
= Compute Firmware Bundle 12.2.109 Release Notes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware

[.lead]
The downloadable compute firmware bundle contains the latest BIOS and BMC feature enhancements, bugfixes, and hardware support for all supported NetApp HCI compute nodes.

== What's New
Version 12.2.109 introduces BMC support for the DMTF Redfish APIs, which enables future functionality for NetApp Hybrid Cloud Control. The firmware updates also contain general bugfixes and resolve memory issues. The BMC updates for H300E, H500E, and H700E compute nodes address several security vulnerabilities, including CVE-2019-16649, CVE-2019-16650, and CVE-2019-6260.

This firmware package contains the following firmware versions for hardware components, with updated versions in bold:

|===
|Component |H300E, H500E, H700E |H410C |H610C |H615C

|BIOS
|NA2.1
|*NA3.7*
|*3B01*
|3B06.CO

|BMC
|*6.84.00*
|6.71.06
|*3.96.07*
|*4.64.07*

|NIC / Mellanox
|14.21.1000
|14.21.1000
|14.22.1002
|14.23.1020
|===

To download the Compute Firmware Bundle, go to the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/Compute_Firmware_Bundle[NetApp HCI Compute Firmware Bundle^] page.

Visit link:task_hcc_upgrade_compute_node_firmware.html#use-the-baseboard-management-controller-bmc-user-interface-ui[Update compute node firmware] for instructions on updating your compute node firmware.

== Resolved issues
The following are issues that have been resolved in this release.

|===
|Issue |Description

|PE-10306
|When you upgrade the BMC software on an Element 11.8 storage node, BMC user credentials are lost.

|CSESF-26
|In some circumstances, H610C nodes can exhibit intermittent fan noise.

|CSESF-293
|When you upgrade to the version 12.2.92 compute node firmware on a H410C, H610C, H300E, H500E, or H700E node, version 14.21.1000 of the Mellanox network interface card (NIC) firmware is installed, even if it was previously at a newer version.

|CSESF-352
|TLS versions 1.0 and 1.1 suffer from security vulnerabilities. This release disables TLS 1.0 and 1.1 for H610C and H615C compute nodes.
|===

== Known issues
The following are known issues in this release that might affect daily operation in some environments.

|===
|Issue |Description |Workaround

|CSESF-295
|The compute node firmware update process fails with a BIOS update error when you update the firmware on a H410C node using the downloadable firmware package.
|Manually update the BIOS to version NA3.7 on the H410C node:
1. Browse to the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[NetApp HCI Downloads page^].
2. Enter `H410C_BIOS_3.7` in the drop down list text field.
3. Click *Go*.
Instructions for updating are available in PDF format on the download page.

After you update the BIOS and BMC, update the H410C node firmware using the compute firmware 12.2.109 package.
|===
