---
sidebar: docs_sidebar
permalink: docs/rn_firmware_12.2.81.html
summary: Get links to release notes for the firmware packages that you can download and apply to NetApp HCI nodes.
keywords: netapp, hci, compute firmware
---
////
This file isn't included in the docs_sidebar nav system. It is only linked to from the rn_relatedrn.adoc file, and this is by design. It might be a totally poor design, but we're going to try it out. -MW, 6-3-2020
////
= Compute firmware 12.2.81-2.3.0 Release Notes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware

[.lead]
The downloadable compute node firmware package contains the latest BIOS and BMC feature enhancements, bugfixes, and hardware support for all supported NetApp HCI compute nodes.

== What's New
Version 12.2.81 introduces BMC support for the DMTF Redfish APIs, which enables future functionality for NetApp Hybrid Cloud Control. The firmware updates also contain general bugfixes and resolve memory issues. The BMC updates for H300E, H500E, and H700E compute nodes address several security vulnerabilities, including CVE-2019-16649, CVE-2019-16650, and CVE-2019-6260.

This firmware package contains the following firmware versions for hardware components, with updated versions in bold:

|===
|Component |H300E, H500E, H700E |H410C |H610C |H615C

|BIOS
|NA2.1
|*NA3.7*
|*3B01*
|3B06.CO

|BMC
|*6.84.00*
|6.71.06
|*3.96.07*
|*4.64.07*

|NIC / Mellanox
|14.21.1000
|14.21.1000
|14.22.1002
|14.23.1020
|===

Download the compute node firmware package from https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/1.8/downloads[the NetApp HCI downloads page^].
