---
sidebar: sidebar
permalink: docs/rn_H610S_BMC_3.84.07.html
summary: Get links to release notes for the firmware packages that you can download and apply to NetApp HCI nodes.
keywords: netapp, hci, compute firmware
---
////
This file isn't included in the sidebar nav system. It is only linked to from the rn_relatedrn.adoc file, and this is by design. It might be a totally poor design, but we're going to try it out. -MW, 6-3-2020
////
= H610S BMC 3.84.07 Release Notes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
The downloadable BMC update contains BMC feature enhancements and bug fixes for NetApp H610S nodes.

== What's New
H610S BMC 3.84.07 contains various bug fixes and new features. This release brings to the field critical updated BMC firmware ahead of subsequent Element software and storage firmware bundle releases, which will also include this updated BMC firmware for H610S nodes.

This firmware package is supported on Element versions 11.8, 12.0, and 12.2. You can upgrade the H610S BMC firmware directly out-of-band, and upgrade instructions can be found in <<Upgrading BMC firmware on H610S nodes>>.

== New Features
The following are the new features and changes included in this release:

* Enabled INITRD support
* Updated SSL help message about X.509 certificates
* Disabled TLS 1.0 and 1.1 support
* Added Redfish remote media support
* Added the H5Viewer RKVM feature
* Added Remote syslog support

== Resolved issues
The following are issues that have been resolved in this release:

|===
|Issue |Description

|N/A
|The debug user sysadmin can log in using SSH after resetting the BMC.

|N/A
|When you use the console to ping the BMC IP address, the BMC does not respond.

|N/A
|During an AC power cycle stress test, the access permissions of the SOLSSH config file are lost.

|CSESF-116
|During an AC power cycle stress test, "PROCHOT" CPU thermal warnings appear in the BMC logs.

|CSESF-121
|The create and update service account API takes longer than expected.

|CSD-3321 / CSESF-129
|The H610S BMC can hang and become inaccessible with the error "BMC Self Test Failed".

|CSESF-197
|The BMC web UI inventory API returns the wrong memory serial number format.
|===

== Known issues
There are no known issues in this release.

== Upgrading BMC firmware on H610S nodes
Perform the following steps to upgrade the BMC firmware version on your H610S nodes. The procedure can take approximately 30 minutes to complete.

.What you'll need
* You have checked for alerts by clicking *Reporting* > *Alerts* in the NetApp Element software web UI to ensure that there are no errors.
* You have downloaded the BMC update package. Download the BMC update package https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/H610S_BMC_3.84[here^].

NOTE: This update package includes the `rom.ima_enc` file and all files needed for the firmware update.

* You have ensured that the BMC and the computer you are using to perform the update are located on the same network.
* You have contacted NetApp Support for assistance with the BMC upgrade.

.Steps
. Log in to the BMC console using your web browser: `https://<BMC_IP>/#login`, where `<BMC_IP>` is the IP address of the BMC.
. Click *Maintenance*.
. Click *Preserve Configuration*.
. Do the following:
.. Disable the *Check All* checkbox.
.. Enable the *IPMI* checkbox.
.. Enable the *Network* checkbox.
.. Enable the *Authentication* checkbox.
+
** The *IPMI* setting is used to preserve existing user accounts.
** The *Network* setting is used to preserve the DHCP assigned BMC IP address.
** The *Authentication* setting is used to preserve custom accounts configured for BMC login.
. Click *Save*.
. Click *Firmware Update*.
. Disable the *Preserve all Configuration* checkbox.
+
NOTE: Ensure that you have disabled the *Preserve all Configuration* checkbox.

+
. On the computer you are using to perform the update, extract the contents of the BMC update package.
. In the BMC web UI, under the *Select Firmware Image* section of the *Firmware Update* page, click *Choose File*.
. Browse to the `rom.ima_enc` file within the extracted package contents and select it.
. Click *Start firmware update* and click *OK* when the prompt appears asking if you want to continue.
. Click *OK* when a prompt appears indicating that a firmware reset is happening.
. After several minutes, use a new browser tab to log in to the BMC web UI.
. On the BMC dashboard, go to *Device Information* > *More info*.
. Confirm that the *Firmware Revision* is *3.84.07*.
. Perform this procedure for the remaining H610S storage nodes in your cluster.

[discrete]
== Find more Information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources Page^]
