---
sidebar: docs_sidebar
permalink: docs/rn_H610S_BMC_3.84.07.html
summary: Get links to release notes for the firmware packages that you can download and apply to NetApp HCI nodes.
keywords: netapp, hci, compute firmware
---
////
This file isn't included in the docs_sidebar nav system. It is only linked to from the rn_relatedrn.adoc file, and this is by design. It might be a totally poor design, but we're going to try it out. -MW, 6-3-2020
////
= H610S BMC 3.84.07 Release Notes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware

[.lead]
The downloadable BMC update contains BMC feature enhancements and bugfixes for NetApp H610S nodes.

== What's New
H610S 3.84.07 BMC contains various bug fixes and new features. The primary purpose of this release is to bring to the field this critical updated BMC ahead of subsequent Element OS release and storage firmware bundle release which will also include this updated BMC for H610S.

Upgrading H610S BMC directly is done out-of-band and instructions to do so can be found here (login required).

== New Features
The following are the new features and changes included in this release:

* Enable INITRD support
* Add update SSL help message about X.509 certificates
* Disable TLS 1.0 and 1.1
* Add Redfish remote media support
* Add H5Viewer RKVM feature
* Add Remote syslog support

== Resolved issues
The following are issues that have been resolved in this release:

|===
|Issue |Description

|N/A
|The debug user sysadmin can log in using SSH after resetting the BMC.

|N/A
|When you use the console to ping the BMC IP address, the BMC does not respond.

|N/A
|During an AC power cycle stress test, the access permissions of the SOLSSH config file are lost.

|CSESF-116
|During an AC power cycle stress test, "PROCHOT" CPU thermal warnings appear in the BMC logs.

|CSESF-121
|The create and update service account API takes longer than expected.

|CSD-3321 / CSESF-129
|The H610S BMC can hang and become inaccessible with the error "BMC Self Test Failed".

|CSESF-197
|The WebUI inventory API returns the wrong memory serial number format.
|===

== Known issues
There are no known issues in this release

== Updating BMC firmware on H610S nodes

Perform the following steps to update your BMC firmware version. The procedure to update the BMC firmware on H610S nodes can take approximately 30 minutes to complete.

.What you'll need
* You have checked for alerts by clicking *Reporting* > *Alerts* in the NetApp Element Software user interface (UI) to ensure that there are no errors.
* You have downloaded the BMC update file.

.Steps
. Log in to the BMC console using an internet browser: https://<BMC IP>/#login, where <BMC IP> is the IP address of the BMC.
. Select *Maintenance* > *Firmware Update*.
. On the firmware update screen, make sure that you select the *IPMI* and *Network* check boxes.
+
** The *IPMI* setting is used to preserve existing user accounts.
** The *Network* setting is used to preserve the DHCP assigned BMC IP address.
+
NOTE: Make sure that the *Preserve all configuration* check box is not selected.

. Choose the file and click *Start firmware update* to start the firmware update process.
+
The update process can take up to 5 minutes to complete if the BMC firmware file is in the node's network; otherwise the process will take longer.
. Verify the firmware version by looking at the version listed on the *Dashboard* > *More info* page.
. Perform this procedure for the remaining H610S storage nodes in your cluster.
