---
sidebar: docs_sidebar
permalink: docs/rn_storage_firmware_2.27.html
summary: Get links to release notes for the firmware packages that you can download and apply to NetApp HCI nodes.
keywords: netapp, hci, storage firmware
---
////
This file isn't included in the docs_sidebar nav system. It is only linked to from the rn_relatedrn.adoc file, and this is by design. It might be a totally poor design, but we're going to try it out. -MW, 6-3-2020
////
= Storage Firmware Bundle 2.27 Release Notes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware

[.lead]
The downloadable storage firmware update package contains firmware feature enhancements and bug fixes for NetApp storage nodes.

== What's New
The storage firmware bundle version 2.27 contains various bug fixes and new features. You can upgrade the storage firmware out-of-band; you can find upgrade instructions in <<Upgrading storage node BMC firmware>>.

=== Updated firmware components
This firmware package contains the following firmware versions for hardware components, with updated versions in bold:

|===
|Component |Dell R630 |H410S |H610S

|BIOS
|N/A
|NA2.1
|3B03

|BMC
|N/A
|*6.84.00*
|*3.84.07*

|NIC / Mellanox
|-
|*14.21.1000*
|*14.22.1002*

|RMS200
|ae3b8cc
|7d8422bc
|*14.25.1020*

|RMS300
|7d8422bc
|7d8422bc
|*14.25.1020*

|NVDIMM, Smart
|-
|-
|*14.25.1020*

|BPM, Smart
|-
|-
|*14.25.1020*

|NVDIMM, Micron Gen1
|-
|-
|*14.25.1020*

|NVDIMM, Micron Gen2
|-
|-
|*14.25.1020*

|PGEM, Micron
|-
|-
|*14.25.1020*

|PM863, SED
|GXT5404Q
|GXT5404Q
|-

|PM863, NSED
|GXT5103Q
|GXT5103Q
|-

|PM883, SED
|HXT7104Q
|HXT7104Q
|-

|Hawk-4, SED
|8ENP7101
|8ENP7101
|-

|Hawk-4, NSED
|8ENP6101
|8ENP6101
|-

|PM963, SED
|-
|-
|*14.25.1020*

|PM963, NSED
|-
|-
|*14.25.1020*

|CD5, SED
|-
|-
|*14.25.1020*

|CD5, NSED
|-
|-
|*14.25.1020*

|CD5, FIPS
|-
|-
|*14.25.1020*
|===

== New Features
The following are the new features and changes included in this release:

* Enabled INITRD support
* Updated SSL help message about X.509 certificates
* Disabled TLS 1.0 and 1.1 support
* Added Redfish remote media support
* Added the H5Viewer RKVM feature
* Added remote syslog support

== Resolved issues
The following are issues that have been resolved in this release:

|===
|Issue |Description

|N/A
|The debug user sysadmin can log in using SSH after resetting the BMC.

|N/A
|When you use the console to ping the BMC IP address, the BMC does not respond.

|N/A
|During an AC power cycle stress test, the access permissions of the SOLSSH config file are lost.

|CSESF-116
|During an AC power cycle stress test, "PROCHOT" CPU thermal warnings appear in the BMC logs.

|CSESF-121
|The create and update service account API takes longer than expected.

|CSD-3321 / CSESF-129
|The H610S BMC can hang and become inaccessible with the error "BMC Self Test Failed".

|CSESF-197
|The BMC web UI inventory API returns the wrong memory serial number format.
|===

== Known issues
There are no known issues in this release.

== Upgrading storage node BMC firmware
Perform the following steps to upgrade the BMC firmware version on your storage nodes. The procedure can take approximately 30 minutes to complete.

.What you'll need
* You have checked for alerts by selecting *Reporting* > *Alerts* in the NetApp Element software web UI to ensure that there are no errors.
* You have downloaded the BMC update file.

.Steps
. Log in to the BMC console using your web browser: `https://<BMC_IP>/#login`, where `<BMC_IP>` is the IP address of the BMC.
. Click *Maintenance* > *Firmware Update*.
. On the firmware update screen, ensure that you select the *IPMI* and *Network* checkboxes.
+
** The *IPMI* setting is used to preserve existing user accounts.
** The *Network* setting is used to preserve the DHCP assigned BMC IP address.
+
NOTE: Ensure that the *Preserve all configuration* checkbox is not selected.

. Choose the BMC update file you downloaded and click *Start firmware update* to start the upgrade process.
+
The process can take up to 5 minutes to complete if the BMC firmware file is in the node's network; otherwise the process will take longer.
. Verify the firmware version by looking at the version listed on the *Dashboard* > *More info* page.
. Perform this procedure for the remaining storage nodes in your cluster.
