---
sidebar: sidebar
permalink: docs/rn_whatsnew.html
summary: Learn what's new in this version of NetApp HCI.
keywords: netapp, hci, element, new, whatsnew
---

= What's new in NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help, element

[.lead]
NetApp periodically updates NetApp HCI to bring you new features, enhancements, and bug fixes. NetApp HCI 1.10 includes Element 12.5 for storage clusters.

* The <<NetApp HCI 1.10>> section describes new features and updates in NetApp HCI version 1.10.

* The <<Element 12.5>> section describes new features and updates in NetApp Element 12.5.

== NetApp HCI 1.10

NetApp HCI 1.10 includes security and stability improvements, and increases post deployment scaling flexibility.

=== Post deployment scaling flexibility
NetApp HCI 1.10 increases your flexibility to expand NetApp HCI compute resources by removing the requirement to meet the default deployment vmk and vmnic configuration settings on the compute nodes. Beginning with NetApp HCI 1.10, only general vmk configurations on the compute nodes are expected by NetApp HCI when you expand compute resources. link:task_nde_supported_net_changes.html[Learn more].

=== NetApp Element Plug-in for vCenter Server 4.9 availability
The NetApp Element Plug-in for vCenter Server 4.9 is available outside of the management node 12.5 and NetApp HCI 1.10 releases. To upgrade the plug-in, follow the instructions in the link:concept_hci_upgrade_overview.html[NetApp HCI Upgrades] documentation.

=== NetApp Hybrid Cloud Control enhancements
NetApp Hybrid Cloud Control is enhanced for version 1.10. link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[Learn more^].

=== Resolved issues and known issues

The NetApp Bugs Online tool contains resolved and known issues for NetApp HCI, Element, and other products. You can browse these issues using keywords or versions at https://mysupport.netapp.com/site/products/all/details/netapp-hci/bugsonline-tab[NetApp Bugs Online^].

== Element 12.5
Element 12.5 introduces improved storage node access, enhanced custom Protection Domains manageability, new and improved cluster faults and events, enhanced Cluster UI functionality, enhanced security, and automated upgrades using Ansible.

=== Improved storage node access
Element 12.5 brings improved remote access to individual nodes using signed SSH certificates. To provide secure remote access to storage nodes, a new, limited-privilege local user account called `sfreadonly` is now created during RTFI of a storage node. The `sfreadonly` account enables access to the storage node backend for basic maintenance or troubleshooting purposes. You can now configure the `supportAdmin` access type for a cluster administrator user to allow NetApp support access to the cluster on an as-needed basis.

=== Enhanced custom Protection Domains manageability
Element 12.5 features a new user interface that enables you to quickly and easily view existing custom Protection Domains and configure new custom Protection Domains.

=== New and improved cluster faults, events, and alerts
Element 12.5 enhances your system troubleshooting with the introduction of the new cluster fault codes `BmcSelfTestFailed` and `CpuThermalEventThreshold`.  Element 12.5 also contains robustness improvements for existing cluster events and alerts, such as `nodeOffline`, `volumeOffline`, `driveHealthFault`, `networkEvent`, and	`cSumEvent`.


=== Enable Software Encryption at Rest from the Create Cluster UI
With the addition of a new checkbox in the Create Cluster UI, Element 12.5 gives you the option to enable cluster-wide Software Encryption at Rest for SolidFire all-flash storage clusters during cluster creation.

=== Storage node firmware updates
Element 12.5 includes firmware updates for storage nodes. link:https://docs.netapp.com/us-en/element-software/concepts/concept_rn_relatedrn_element.html#storage-firmware[Learn more^].

=== Enhanced security
Element 12.5 contains the mitigation that closes the Element software exposure to the Apache Log4j vulnerability. NetApp SolidFire storage clusters with the Virtual Volumes (VVols) feature enabled are exposed to the Apache Log4j vulnerability. For information on the workaround for the Apache Log4j vulnerability in NetApp Element software, see the link:++https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Element_Software_-_Apache_Log4j_Vulnerability_-_Workaround++[KB article^].

If you're running Element 11.x, 12.0, or 12.2 or your storage cluster is already at Element 12.3 or 12.3.1 with the VVols feature enabled, upgrading to 12.5 is highly recommended.

Element 12.5 also includes more than 120 CVE security vulnerability remediations.

== Automated upgrades using Ansible
With Element 12.5, you can automate the Element upgrade workflow by using Ansible to perform a rolling upgrade of the entire storage cluster. To get started, navigate to the https://github.com/NetApp-Automation[NetApp Ansible repository^] on GitHub and download the `nar_solidfire_sds_upgrade` role and documentation.

[discrete]
== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[NetApp Hybrid Cloud Control and Management Services Release Notes^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software[Firmware and driver versions for NetApp HCI and NetApp Element software^]
