---
sidebar: docs_sidebar
permalink: docs/rn_whatsnew.html
summary: Learn what's new in this version of NetApp HCI.
keywords: netapp, hci, element, new, whatsnew
---

= What's new in NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help, element

[.lead]
NetApp periodically updates NetApp HCI to bring you new features, enhancements, and bug fixes.

* <<NetApp HCI 1.8>> describes new features and updates in NetApp HCI version 1.8.

* <<Element 12.0>> describes new features and updates in NetApp Element 12.0.

* <<Compute node firmware version 12.2.81>> describes improvements in the current release of NetApp HCI compute node firmware.

== NetApp HCI 1.8
NetApp HCI 1.8 introduces two-node and three-node storage cluster capability, multi-factor authentication, and NetApp Hybrid Cloud Control enhancements.

NOTE: NetApp HCI 1.8 includes NetApp Element software 12.0. http://docs.netapp.com/sfe-120/topic/com.netapp.ndc.sfe-home/GUID-D0719315-8ECA-44E8-994A-F2DAA3D1FABA.html[Learn more^] about what's new in Element 12.0.

=== Active IQ Config Advisor
Active IQ Config Advisor is a tool that helps streamline the installation experience and reduce networking failures during deployment. It validates that the configuration is ready for deployment and generates a report that you can use to resolve issues and send to NetApp Professional Services before hardware installation. See the https://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html[Deployment Guide^] for details.

=== NetApp HCI documentation enhancements
You can now access NetApp HCI upgrading, expansion, monitoring, and concepts information in an easy-to-navigate format link:index.html[here^].

=== NetApp Element Plug-in for vCenter Server 4.4 availability
The NetApp Element Plug-in for vCenter Server 4.4 is available outside of the management node 12.0 and NetApp HCI 1.8 releases. To upgrade the plug-in, follow the instructions in the link:concept_hci_upgrade_overview.html[NetApp HCI Upgrades^] documentation.

=== NetApp Hybrid Cloud Control enhancements
NetApp Hybrid Cloud Control is enhanced for version 1.8. https://kb.netapp.com/app/answers/answer_view/a_id/1087586[Learn more^].

=== Support for two-node and three-node storage clusters
With version 1.8, you can set up NetApp HCI to use a storage cluster with two or three storage nodes. When you deploy with a two-node or three-node storage cluster, the deployment process automatically configures two NetApp Witness Nodes as virtual machines. Witness Nodes are virtual nodes that enable storage node redundancy in the event of a storage node failure. NetApp HCI supports the H410S-0, H410S-1, and H610S-1 storage nodes in two-node or three-node storage clusters. link:concept_hci_clusters.html[Learn more^].

== Element 12.0
NetApp HCI 1.8 includes Element 12.0 for storage clusters. Element 12.0 introduces multi-factor authentication, session-based web UI logins, external key management (EKM) enhancements, faster upgrades, customizable protection domains, and contains stability and functionality improvements.

=== Element 12.0 firmware updates
The following firmware updates for H610S storage node hardware components are included with this release:

|===
|Component |Firmware version

|BIOS
|3B03

|NVDIMM Gen1
|3.1

|NVDIMM BPM
|2.16

|CPLD
|v122

|BMC
|3.78.07

|YafuFlash2
|4.16.21
|===

=== Multiple vCenter VASA support
VASA support for up to 10 vCenters is available as an upgrade patch if you have already registered a VASA provider with your vCenter. To install, follow the directions in the VASA39 manifest and download the .tar.gz file from the https://mysupport.netapp.com/products/element_software/VASA39/index.html[NetApp Software Downloads^] site.
NOTE: The NetApp Element VASA provider uses a NetApp certificate. With this patch, the certificate is used unmodified by vCenter to support multiple vCenters for VASA and VVols use. Do not modify the certificate. Custom SSL certificates are not supported by VASA.

=== Customizable Protection Domains
Beginning with Element 12.0, you can customize protection domain layouts to cover zones of storage nodes within a rack, or between multiple racks. This enables you to have more flexibility in data resiliency and to improve storage availability, especially in large scale installations. When you enable the feature, you must have at least 3 domains, and at least 2 storage nodes per domain.

The following are Element API methods related to Protection Domains (the http://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-api/home.html[Element API Reference Guide^] has more information):

* SetProtectionDomainLayout
* GetProtectionDomainLayout
* ListAllNodes
* ListActiveNodes
* ListPendingNodes
* AddDrives
* ListProtectionDomainLevels
* CheckProposedNodeAdditions
* CheckProposedCluster

=== Faster upgrades
Element 12.0 brings decreases in upgrade times. Upgrades from Element 12.0 to future Element releases are significantly faster than upgrades from previous versions.

=== Enhanced external key management
Element 12.0 external key management (EKM) now supports the following key management
services:

* Gemalto SafeNet KeySecure
* SafeNet AT KeySecure
* HyTrust KeyControl
* Vormetric Data Security Manager (new in Element 12.0)
* IBM Security Key Lifecycle Manager (new in Element 12.0)
http://docs.netapp.com/sfe-120/topic/com.netapp.doc.sfe-ug/GUID-057D852C-9C1C-458A-9161-328EDA349B00.html[Learn more.^]

=== Multi-factor authentication
With multi-factor authentication (MFA) support, you can now integrate the Element web UI and the storage per-node web UI with your single sign-on (SSO) infrastructure.
MFA supports the following SAML 2.0-based identity providers (IdPs):

* Microsoft Active Directory Federation Services (ADFS) 2016
* Shibboleth 3.4.4

The following are Element API methods related to MFA (the Element API Reference Guide has more information):

* CreateIdpConfiguration
* UpdateIdpConfiguration
* DeleteIdpConfiguration
* ListIdpConfigurations
* EnableIdpAuthentication
* DisableIdpAuthentication
* ListProtectionDomainLevels
* GetIdpAuthenticationState
* ListCurrentClusterAdmins
* DeleteAuthSession
* DeleteAuthSessionsByClusterAdmin
* DeleteAuthSessionsByUsername
* ListActiveAuthSessions
* ListAuthSessionsByClusterAdmin
* ListAuthSessionsByUsername

=== New storage node terminal user interface (TUI)
The Element TUI is now restructured and features easier to use navigation and input fields.

=== New storage per-node web UI
The Element 12.0 storage per-node web UI now uses the look and feel of NetApp Hybrid Cloud
Control. You can access this UI at https://<Node IP address>:442/hcc.

=== Security enhancements
Element 12.0 resolves many security vulnerabilities for storage nodes and the management node.
http://security.netapp.com/[Learn more^] about these security enhancements.

=== Session-based authentication
The Element API now supports token authentication and authorization, enabling you to log on to the Element web UI or individual storage per-node web UIs with either the local cluster admin credentials or LDAP-based cluster admin credentials. One browser login session token covers multiple web UI logins, so you can log in to the Element web UI and then log in to all individual storage per-node web UIs in that storage cluster and not have to re-authenticate with each one.

The following are Element API methods related to session-based authentication (the Element API Reference Guide has more information):

* ListAuthSessionsByClusterAdmin
* ListActiveAuthSessions
* ListAuthSessionsByUsername

== Compute node firmware version 12.2.81
This compute node firmware package contains the latest BIOS and BMC feature enhancements, bugfixes, and hardware support for NetApp HCI compute nodes. Download the firmware package from https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/1.8/downloads[the NetApp HCI downloads page^].

[discrete]
== Find more information
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* http://docs.netapp.com/sfe-120/index.jsp[SolidFire and Element Software Documentation Center^]
* https://kb.netapp.com/app/answers/answer_view/a_id/1088658[Firmware and driver versions for NetApp HCI and NetApp Element software^]
