---
sidebar: docs_sidebar
permalink: docs/rn_whatsnew.html
summary: Learn what's new in this version of NetApp HCI.
keywords: netapp, hci, element, new, whatsnew
---

= What's new in NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help, element

[.lead]
NetApp periodically updates NetApp HCI to bring you new features, enhancements, and bug fixes.

== NetApp HCI 1.8
NetApp HCI 1.8 introduces two-node and three-node storage cluster capability, multi-factor authentication, and NetApp Hybrid Cloud Control enhancements.

NOTE: NetApp HCI 1.8 includes NetApp Element software 12.0. http://docs.netapp.com/sfe-120/topic/com.netapp.ndc.sfe-home/GUID-D0719315-8ECA-44E8-994A-F2DAA3D1FABA.html[Learn more^] about what's new in Element 12.0.

=== Active IQ Config Advisor
Active IQ Config Advisor is a new tool that helps streamline the installation experience and reduce networking failures during deployment. It validates that the configuration is ready for NetApp HCI deployment. you to validate that your environment is ready for NetApp HCI deployment. Active IQ Config Advisor collects data and generates a report that you can use to resolve issues and send to NetApp Professional Services before hardware installation. See the https://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html[Deployment Guide^] for details.

=== NetApp HCI documentation enhancements
You can now access NetApp HCI upgrading, expansion, monitoring, and concepts information in an easy to navigate format link:index.html[here^].

=== NetApp Element Plug-in for vCenter Server 4.4 availability
The NetApp Element Plug-in for vCenter Server 4.4 is available outside of the management node 12.0 and NetApp HCI 1.8 releases. To upgrade the plug-in, follow the instructions in the link:concept_hci_upgrade_overview.html[NetApp HCI Upgrades^] documentation.

=== NetApp Hybrid Cloud Control enhancements
NetApp Hybrid Cloud Control is enhanced for version 1.8. https://kb.netapp.com/app/answers/answer_view/a_id/1087586[Learn more^].

=== Support for two-node and three-node storage clusters
With version 1.8, you can set up NetApp HCI to use a storage cluster with two or three storage nodes. When you deploy with a two-node or three-node storage cluster, the deployment process automatically configures two NetApp Witness Nodes as virtual machines. Witness Nodes are virtual nodes that enable storage node redundancy in the event of a storage node failure. NetApp HCI supports the H410S-0, H410S-1, and H610S-1 storage nodes in two-node or three-node storage clusters. link:concept_hci_clusters.html[Learn more^].

[discrete]
== Find more information
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* http://docs.netapp.com/sfe-120/index.jsp[SolidFire and Element Software Documentation Center^]
