---
sidebar: docs_sidebar
permalink: docs/rn_whatsnew.html
summary: Learn what's new in this version of NetApp HCI.
keywords: netapp, hci, element, new, whatsnew
---

= What's new in NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, cloud, onprem, documentation, help, element

[.lead]
NetApp periodically updates NetApp HCI to bring you new features, enhancements, and bug fixes. NetApp HCI 1.9 includes Element 12.3 for storage clusters.

* The <<NetApp HCI 1.9>> section describes new features and updates in NetApp HCI version 1.9.

* The <<Element 12.3>> section describes new features and updates in NetApp Element 12.3.

== NetApp HCI 1.9
NetApp HCI 1.8P1 includes security and stability improvements.

=== Import deployment configuration profiles
During deployment of NetApp HCI 1.9, you can import a deployment configuration profile. NetApp Deployment Engine uses the information in the profile to automatically populate information about your deployment. You can compile a configuration profile from your own installation information, or you can reuse an exported CSV file from a previous successful deployment.

=== Improved NetApp Deployment Engine network configuration
NetApp HCI 1.9 simplifies networking configuration during deployment. The network configuration step of the NetApp Deployment Engine is divided in to sections to make entering information easier.

=== Updated VMware ESXi for compute nodes
The version of VMware ESXi installed on compute nodes for new deployments has been updated to 6.7U3.

=== NetApp Element Plug-in for vCenter Server 4.6 availability
The NetApp Element Plug-in for vCenter Server 4.6 is available outside of the management node 12.3 and NetApp HCI 1.9 releases. To upgrade the plug-in, follow the instructions in the https://docs.netapp.com/us-en/hci/docs/concept_hci_upgrade_overview.html[NetApp HCI Upgrades] documentation.

=== NetApp Hybrid Cloud Control enhancements
NetApp Hybrid Cloud Control is enhanced for version 1.9. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[Learn more].

== Element 12.3
NetApp HCI 1.9 includes Element 12.3 for storage clusters. Element 12.3 introduces software encryption at rest enhancements, security enhancements, storage firmware updates, enhanced snapshot functionality, and improved behavior for failing drives.

=== NetApp Bugs Online contains known and resolved issues
Beginning with Element 12.3, known and resolved issues are now listed in the NetApp Bugs Online tool. You can browse these issues for Element and other products at https://mysupport.netapp.com/site/products/all/details/solidfire-elementos/bugsonline-tab[NetApp Bugs Online].

=== FIFO snapshot functionality
Element 12.3 enables you to create a First-In-First-Out (FIFO) queue for volume snapshots. Using the Element API, you can specify the minimum and maximum number of First-In-First-Out (FIFO) snapshot slots that should be reserved when you create a volume. When the FIFO snapshot queue for a volume is full, the next snapshot you create for that volume removes the oldest snapshot of that volume from the system. FIFO and non-FIFO snapshots both use the same pool of available snapshot slots on a volume.

The following are Element API methods related to FIFO snapshots (see the https://docs.netapp.com/us-en/element-software/api/index.html[Element API documentation] for details about each API method):

* CreateGroupSnapshot
* CreateSchedule
* CreateSnapshot
* CreateVolume
* ModifyGroupSnapshot
* ModifySchedule
* ModifySnapshot
* ModifyVolume
* ModifyVolumes

=== Snapshot serialization functionality
Element 12.3 supports serialized snapshot creation. When creating a new snapshot using the Element API, you can specify that the snapshot should not be created if a previous snapshot replication is still in progress.

The following are Element API methods related to snapshot serialization (see the https://docs.netapp.com/us-en/element-software/api/index.html[Element API documentation] for details about each API method):

* CreateGroupSnapshot
* CreateSchedule
* CreateSnapshot
* ModifySchedule

=== Snapshot retention functionality
Element 12.3 enables you to use the Element API to specify a retention time for snapshots. If you don't specify a retention time or an expiration time for a snapshot, it is retained forever.

The following are Element API methods related to snapshot retention (see the https://docs.netapp.com/us-en/element-software/api/index.html[Element API documentation] for details about each API method):

* CreateGroupSnapshot
* CreateSchedule
* CreateSnapshot
* ModifyGroupSnapshot
* ModifySchedule
* ModifySnapshot

=== Final NetApp HealthTools version
Element 12.3 is the final version that you can upgrade using NetApp HealthTools. If you are running Element 11.3 or newer, you should use NetApp Hybrid Cloud Control to upgrade Element software. You can upgrade Element versions 11.1 or earlier using NetApp HealthTools.

=== Software encryption at rest enhancements
Element 12.3 introduces enhancements for the software encryption at rest feature. You can enable software encryption at rest when you create a storage cluster (and is enabled by default when you create a SolidFire Enterprise SDS storage cluster). This feature encrypts all data stored on the SSDs in the storage nodes and causes only a very small (~2%) performance impact on client IO.

The following are Element API methods related to software encryption at rest (see the https://docs.netapp.com/us-en/element-software/api/index.html[Element API documentation] for details about each API method):

* CreateCluster
* DisableEncryptionAtRest
* EnableEncryptionAtRest
* GetSoftwareEncryptionAtRestInfo
* RekeySoftwareEncryptionAtRestMasterKey

=== Storage node firmware updates
Element 12.3 includes firmware updates for storage nodes. http://docs.netapp.com/us-en/hci/docs/rn_relatedrn.html[Learn more].

=== Security enhancements
Element 12.3 resolves security vulnerabilities for storage nodes and the management node. http://security.netapp.com/[Learn more] about these security enhancements.

=== Improved behavior for failing drives
Element 12.3 performs periodic health checks on SolidFire appliance drives using SMART health data from the drives. A drive that fails the SMART health check might be close to failure. If a drive fails the SMART health check, the drive is transitioned to the *Failed* state, and a critical severity cluster fault appears: `Drive with serial: <serial number> in slot: <node slot><drive slot> has failed the SMART overall health check. To resolve this fault, replace the drive`.

=== What's new in SolidFire Enterprise SDS
Here is what's new in SolidFire eSDS:

==== New server support
SolidFire eSDS is now available on Dell R640 servers. See the https://mysupport.netapp.com/matrix/imt.jsp?components=97283;&solution=1757&isHWU&src=IMT[NetApp Interoperability Matrix Tool (IMT)^] for more information about the supported configuration.

==== New documentation
The following new documentation is available for SolidFire eSDS:
* https://docs.netapp.com/us-en/element-software/esds/task_esds_r640_drive_repl.html[Replace drives for Dell R640^]: Provides steps for replacing the drives in Dell R640 servers.
* https://kb.netapp.com/Special:Search?query=solidfire+enterprise+SDS&type=wiki[Knowledge Base articles (login required)^]: Provides information about troubleshooting issues with your SolidFire eSDS system.

==== New location for known issues
You can now search for known issues on the https://mysupport.netapp.com/site/products/all/details/solidfire-enterprise-sds/bugsonline-tab[Bugs Online tool (login required)^].

[discrete]
== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes[NetApp Hybrid Cloud Control and Management Services Release Notes^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* http://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element Software Documentation Center^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software[Firmware and driver versions for NetApp HCI and NetApp Element software^]
