---
sidebar: sidebar
permalink: docs/task_nde_access_ui_fqdn.html
summary: Learn how to configure your system for FQDN access to the web UIs.
keywords: netapp, hci, fqdn, ui, access, web, administration
---

= Configure Fully Qualified Domain Name web UI access

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

NetApp HCI with Element 12.2 or later enables you to access storage cluster web interfaces using the Fully Qualified Domain Name (FQDN). If you want to use the FQDN to access web user interfaces such as the Element web UI, per-node UI, or management node UI, you must first add a storage cluster setting to identify the FQDN used by the cluster. This enables the cluster to properly redirect a login session and improves integration with external services such as key managers and identity providers for multi-factor authentication.

.What you'll need
* This feature requires Element 12.2 or later and management services version 2.15 or later.
* To use REST APIs, you must have deployed a management node running version 11.5 or later.

.Steps

. Ensure that the Element storage nodes and the management node have DNS configured correctly for the network environment so that FQDNs in the environment can be resolved. To set DNS, go to the per-node UI for storage nodes and to the management node, then select *Network Settings* > *Management Network*.
.. Per-node UI for storage nodes: `https://<storage_node_management_IP>:442`
.. Per-node UI for the management node: `https://<management_node_IP>:442`
. Access the Element API and create the following cluster interface preference using the `CreateClusterInterfacePreference` API method, and insert the cluster MVIP FQDN for the preference value:
+
* Name: `mvip_fqdn`
* Value: <Fully Qualified Domain Name for the Cluster MVIP>
+
For example, the FQDN here is `storagecluster.my.org`:
+
----
https://<Cluster_MVIP>/json-rpc/12.2?method=CreateClusterInterfacePreference&name=mvip_fqdn&value=storagecluster.my.org
----
. Change the management node settings using the REST API on the management node:
.. Access the REST API UI for the management node by entering the management node IP address followed by `/mnode/2/`. For example:
+
----
https://<management_node_IP>/mnode/2/
----
.. Click *Authorize* or any lock icon and enter the Element cluster user name and password.
.. Enter the client ID as `mnode-client`.
.. Click *Authorize* to begin a session.
.. Close the window.
.. Click *GET /settings*.
.. Click *Try it out*.
.. Click *Execute*.
.. Note whether or not the proxy is used as indicated in `"use_proxy"` by `true` or `false`.
.. Click *PUT /settings*.
.. Click *Try it out*.
.. In the request body area, enter the management node FQDN as the value for the `mnode_fqdn` parameter. Also specify whether the proxy should be used (`true` or `false` from the previous step) for the `use_proxy` parameter.
+
----
{
  "mnode_fqdn": "mnode.my.org",
  "use_proxy": false
}
----
.. Click *Execute*.

[discrete]
== Find more information
* https://docs.netapp.com/us-en/element-software/api/reference_element_api_createclusterinterfacepreference.html[CreateClusterInterfacePreference API information in the SolidFire and Element Documentation^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation^]
