---
sidebar: docs_sidebar
permalink: docs/task_mnode_manage_storage_clusters.html
summary: You can edit vCenter management node controllers using the REST API UI.
keywords: netapp, mnode, management node, rest api, hci
---

= Manage storage clusters

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can edit the stored credentials for existing storage clusters as well as delete storage clusters using the REST API.

.Before you begin
* Ensure that your cluster version is running NetApp Element software 11.3 or later.
* Ensure that you have deployed a management node running version 11.3 or later.

== Access the management services REST API
You need to authenticate with the REST API UI interface before working with the REST API.

.Steps
. Access the REST API UI for management services by entering the management node IP address
followed by `/mnode`:
+
----
https://[IP address]/mnode
----

. Click *Authorize* or any lock icon and complete the following:
+
.. Enter the cluster user name and password.
.. Enter the client ID as `mnode-client`.
.. Click *Authorize* to begin a session.
.. Close the window.

== Retrieve the storage cluster ID
You can use the REST API get the ID of the storage cluster, which you need to manage the cluster.

.Steps
. Click *GET /installations*.
. Click *Try it out*.
. Click *Execute*.
+
The API returns a list of all known storage cluster installations.
. From the code 200 response body, copy the value in the `id` field for the installation to your clipboard.
. Click *GET /clusters*.
. Click *Try it out*.
. Paste the value you copied earlier into the `installationId` parameter.
. Click *Execute*.
+
The API returns a list of all known storage clusters in this installation.
. From the code 200 response body, find the correct storage cluster and copy the value in the cluster's `storageId` field to your clipboard.

== Edit the stored credentials for a storage cluster
You can edit the stored credentials that NetApp Hybrid Cloud Control uses to log in to a storage cluster. The user you choose must have cluster admin access.

.Steps
. Click *PUT /clusters/{storageId}*.
. Click *Try it out*.
. Paste the storage cluster ID you copied earlier into the `storageId` parameter.
. Change one or both of the following parameters in the *Request body* field:
+
|===
|Parameter |Type |Description

|`userId`
|string
|The user ID used to communicate with the storage cluster (the user must have administrator privileges).

|`password`
|string
|The password used to communicate with the storage cluster.
|===
. Click *Execute*.

== Delete a storage cluster
You can delete a storage cluster if it is no longer in service.

.Steps
. Click *DELETE /clusters/{storageId}*.
. Click *Try it out*.
. Enter the storage cluster ID you copied earlier in the `storageId` parameter.
. Click *Execute*.
+
Upon success, the API returns an empty response.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
