---
sidebar: sidebar
permalink: docs/task_mnode_add_assets.html
summary: You can add compute and controller assets to the management node configuration using the REST API UI.
keywords: netapp, mnode, management node, rest api, hci
---

= Add compute and controller assets to the management node

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can add compute and controller assets to the management node configuration using the REST API UI.

You might need to add an asset if you recently scaled your installation and new assets were not added automatically to your configuration. Use these APIs to add assets that are recent additions to your installation.

.What you'll need
* Your cluster version is running NetApp Element software 11.3 or later.
* You have deployed a management node running version 11.3 or later.
* You have created a new NetApp HCC role in vCenter to limit the management node services view to NetApp-only assets. See link:task_mnode_create_netapp_hcc_role_vcenter.html[Create a NetApp HCC role in vCenter].

.About this task
(NetApp HCI only) If you do not see compute nodes in Hybrid Cloud Control (HCC) after scaling your NetApp HCI system, you can add a compute node using the `POST /assets/{asset_id}/compute-nodes` described in this procedure.

NOTE: When manually adding compute nodes, make sure that you also add the BMC assets otherwise an error is returned.

.Steps
. Get the base asset ID for the installation:
.. Open the inventory service REST API UI on the management node:
+
----
https://[management node IP]/inventory/1/
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the window.
.. From the REST API UI, select *GET ​/installations*.
.. Select *Try it out*.
.. Select *Execute*.
.. From the code 200 response body, copy the `id` for the installation.
+
[subs=+quotes]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+
NOTE: Your installation has a base asset configuration that was created during installation or upgrade.

.. From the REST API UI, select *GET /installations/{id}*.
.. Select *Try it out*.
.. Paste the installation asset ID into the *id* field.
.. Select *Execute*.
.. From the response, copy and save the cluster controller ID (`"controllerId"`) for use in a later step.
. (For compute nodes only) To locate the hardware tag for your compute node in vSphere, go to xref:task_mnode_locate_hardware_tag.adoc[How to locate a hardware tag for compute node].

. To add a compute node and the BMC assets, or a controller sub-asset, to an existing base asset, select one of the following.
+
[cols=2*,options="header",cols="40,60"]
|===
| Option
| Description
| POST /assets/{asset_id}/controllers
a| . Open the mNode service REST API UI on the management node:
+
----
https://[management node IP]/mnode
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the window.
. Select *POST /assets/{asset_id}/controllers*.
. Select *Try it out*.
. Enter the parent base asset ID in the *asset_id* field.
. Add the required values to the payload.
. Select *Execute*.
| POST /assets/{asset_id}/compute-nodes
a| . Open the mNode service REST API UI on the management node:
+
----
https://[management node IP]/mnode
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the window.
. Select *POST /assets/{asset_id}/compute-nodes*.
. Select *Try it out*.
. Enter the parent base asset ID you copied in an earlier step in the *asset_id* field.
. In the payload, do the following:
.. Enter the management IP for the node in the `ip` field.
.. For `hardwareTag`, enter the hardware tag value you saved in an earlier step.
.. Enter other values, as required.
. Select *Execute*.
|===

[discrete]
== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources Page^]
