---
sidebar: sidebar
permalink: docs/task_nde_hci_power_off_compute.html
summary: Learn how to power off NetApp HCI compute nodes.
keywords: netapp, hci, netapp deployment engine, deployment, vsphere
---

= Power off compute resources for a NetApp HCI system
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To power off NetApp HCI compute resources, you need to power off individual VMware ESXi hosts as well as the VMware vCenter Server Appliance in a certain order.

.Steps

. Log in to the vCenter instance controlling the NetApp HCI system and determine the ESXi machine hosting the vCenter Server Virtual Appliance (vCSA).
.  After you have determined the ESXi host running the vCSA, power down all other virtual machines other than the vCSA as follows:
.. Select a virtual machine.
.. Right-click and select *Power > Shut Down Guest OS*.
. Power off all ESXi hosts that are not the ESXi host running the vCSA.
.  Power off the vCSA.
+
This will cause the vCenter session to end because the vCSA disconnects during the power-off process. All virtual machines should now be shut down with only one ESXi host powered on.
. Log in to the running ESXi host.
. Verify that all virtual machines on the host are powered off.
. Shut down the ESXi host.
+
This disconnects any iSCSI sessions open to the NetApp HCI storage cluster.

[discrete]
== Find more information
* link:firmware_driver_versions.html[Supported firmware and ESXi driver versions for NetApp HCI and firmware versions for NetApp HCI storage nodes]
