---
sidebar: docs_sidebar
permalink: docs/task_fo_accessing.html
summary: You can log in to NetApp Fabric Orchestrator.
keywords: netapp, hci, on premise, cloud services
---

= Accessing NetApp Fabric Orchestrator
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can access NetApp Fabric Orchestrator directly with its own address or by selecting the product option from the Cloud Central product list.

== Steps

. Go to the https://fabric.netapp.io[NetApp Fabric Orchestrator^] Login page.
. Enter your Cloud Central login credentials and click *Login*.

TIP: If you do not see any systems listed, make sure that the NetApp HCI administrator is added to your NetApp Cloud Central account.

. If you do not have a Cloud Central account, on the Cloud Central Login page, click *Sign Up*.

+ Using Cloud Central, you can set up accounts either as individual accounts or as Federated accounts:
.. You can make a new account with name, email, and password and then you will be logged in. This is the simplest type of account.
.. If you are part of a Cloud Central Federated organization, you enter your email and are then routed to the organization login.
. From other Cloud Central products, select *Products* > *NetApp Fabric Orchestrator*.


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
