---
sidebar: sidebar
permalink: docs/task_upgrade_element_latest_healthtools.html
summary: As part of a system upgrade, you should upgrade to the latest HealthTools for NetApp Element software.
keywords: netapp, HealthTools upgrade, sfupdate-healthtools, element
---

= Upgrade to the latest HealthTools

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Before you begin an Element storage upgrade from 11.1 or earlier, you should upgrade your HealthTools suite. Upgrading HealthTools is only required if the management node and Element software you are running is 11.1 or earlier. HealthTools are not required for link:task_hcc_upgrade_element_software.html[performing Element upgrades using NetApp Hybrid Cloud Control].

IMPORTANT: Element software 12.3 is the final version that you can upgrade to using NetApp HealthTools. If you are running Element software 11.3 or later, you should use NetApp Hybrid Cloud Control to upgrade Element software. You can upgrade Element versions 11.1 or earlier using NetApp HealthTools.

.What you'll need

* You are running management node 11.0, 11.1 or later.
* You have upgraded your management services to at least version 2.1.326.
+
NetApp Hybrid Cloud Control upgrades are not available in earlier service bundle versions.
* You have downloaded the latest version of https://mysupport.netapp.com/site/products/all/details/element-healthtools/downloads-tab[HealthTools] and copied the installation file to the management node.
+
TIP: You can check the locally installed version of HealthTools by running the `sfupdate-healthtools -v` command.

* To use HealthTools with dark sites, you need to do these additional steps:
** Download a link:https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740[JSON file] from the NetApp Support Site on a computer that is not the management node and rename it to `metadata.json`.
** Have the management node up and running at the dark site.

.About this task

The commands in the HealthTools suite require escalated privileges to run. Either preface commands with `sudo` or escalate your user to root privileges.

NOTE: The HealthTools version you use might be more up to date than the sample input and response below.

.Steps

. Run the `sfupdate-healthtools <path to install file>` command to install the new HealthTools software.
+
Sample input:
+
----
sfupdate-healthtools /tmp/solidfire-healthtools-2020.03.01.09.tgz
----
+
Sample response:
+
----
Checking key signature for file /tmp/solidfirehealthtools-2020.03.01.09/components.tgz
installing command sfupdate-healthtools
Restarting on version 2020.03.01.09
sfupdate-healthtools /sf/bin/sfupdate-healthtools -r 2020.03.01.09
installing command sfupgradecheck
installing command sfinstall
installing command sfresetupgrade
----
. Run the `sfupdate-healthtools -v` command to verify the installed version has been upgraded.
+
Sample response:
+
----
Currently installed version of HealthTools:
2020.03.01.09
----

[discrete]
== Find more information

* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources Page^]
