---
sidebar: docs_sidebar
permalink: docs/task_nde_import_installation_profile.html
summary: Learn how to import a NetApp HCI installation profile that will enable NetApp HCI to automatically fill in fields of the NetApp Deployment Engine wizard.
keywords: netapp, hci, deployment, compatibility, nodes, installation, profile, import, settings, auto, fill
---

= Import an installation profile
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you obtained the NetApp https://configbuilder.netapp.com/[ConfigBuilder^] profile output for your installation, you can import it during the NetApp HCI installation process to automatically fill out the fields in the NetApp Deployment Engine. This is an optional step.

.Import a profile
. On the *Installation Profile* page, click *Browse* to search for and upload your installation profile.
. In the file dialog, select and open the profile JSON file.
. After the profile is successfully imported, click *Continue*.
+
You can step through each page of the deployment wizard and verify the settings that were imported from the installation profile.

.Continue without importing a profile
. To skip the import step, on the *Installation Profile* page, click *Continue*.

== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
