---
sidebar: docs_sidebar
permalink: docs/task_hcc_upgrade_all.html
summary: You can upgrade NetApp HCI and all of its components.
keywords: netapp, hci, on premise, cluster, upgrade, element
---

= Upgrade your entire NetApp HCI installation overview

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can keep the entire NetApp HCI installation up-to-date after deployment by sequentially upgrading all NetApp HCI software components.

These components include management services, management node, Element software, firmware, drivers, and the Element Plug-in for vCenter Server.

.What you'll need

* You are running management node 11.3 or later. To verify your management node version, log in to your management node and verify the Element version number in the login banner:
+
----
login as: <username>
SolidFire Element 11.0.0.781
----
* You have upgraded your management services to at least version 2.1.326.
+
Upgrades using NetApp Hybrid Cloud Control (HCC) is not available in earlier service bundle versions.


.Steps

. link:task_hcc_upgrade_management_services.html[Update management services from Hybrid Cloud Control].
. link:task_hcc_upgrade_element_determineversion.html[Determine the Element version].
. link:task_hcc_upgrade_element_healthtools.html[Use HealthTools to run pre-upgrade health checks].
. link:task_hcc_upgrade_element_software.html[Upgrade your Element software version].
. link:task_hcc_upgrade_management_node.html[Upgrade your management node].
. link:task_hcc_upgrade_compute_node_firmware.html[Update your compute node firmware].
. link:task_hcc_upgrade_compute_node_drivers.html[Update your compute node drivers].



[discrete]
== Find more information

* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
