---
sidebar: docs_sidebar
permalink: docs/task_mnode_change_storage_cluster_admin_password.html
summary: You can add compute and controller assets to the management node configuration using the REST API UI.
keywords: netapp, hci, mnode, management node, admin password
---

= Change the storage cluster administrator password

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can update the storage cluster administrator password by using the REST API UI.

.Before you begin
Ensure that you have changed the storage cluster administrator password by using the NetApp Element software UI.

.Steps
. From a browser, log into the management node REST API UI:
.. Go to the storage MVIP and log in.
+
Doing this causes the certificate to be accepted for the next step.
. Get the base asset ID for the installation:
.. Open the inventory service REST API UI on the management node:
+
----
https://[management node IP]/inventory/1
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the window.
.. From the REST API UI, click *GET ​/installations*.
.. Click *Try it out*.
.. Click *Execute*.
.. From the code 200 response body, copy the `id` for the installation.
+
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      "id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",
----
+
NOTE: A base asset and sub-assets were created when you ran the upgrade or setup scripts during management node installation or upgrade or deployed your NetApp HCI using the NetApp Deployment Engine.

. Get the storage asset ID:
.. From the REST API UI, click *GET ​/installations​/{id}*.
.. Click *Try it out*.
.. Enter the installation ID.
.. Click *Execute*.
.. From the code 200 response body, copy the storage cluster ID (`id`):
+
----
"storage": {
  "errors": [],
  "inventory": {
    "clusters": [
      {
        "clusterUuid": "a3db4306-1a1e-46xx-be6f-0d2513b1125e",
        "id": "ade5b2b1-1e3a-1111-bf81-c1a5d123b123",
        "installationId": "abcd01e2-dc30-4ccf-96ee-11f111bc1x0x",
----
. Update the storage asset:
.. Access the mnode service API UI on the management node by entering the management node IP address followed by `/mnode`:
+
----
https://[IP address]/mnode
----

.. Click *Authorize* or any lock icon and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the window.
.. Click *PUT /assets/{ASSET_ID}/storage-clusters/{STORAGE_ID}*.
.. Click *Try it out*.
.. Enter the installation base asset ID in the *asset_id* field.
.. Enter the storage asset ID in the *storage_id* field.
.. Update the required payload values for the storage asset as defined in the *Model* tab:
.. Remove the hostname and SSL certificate lines.
.. Enter the new password on the password line.
+
----
{
"username": "admin",
"password": "admin",
"ip": "10.10.1.111",
"config": {}
}
----
.. Click *Execute*.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
