---
sidebar: docs_sidebar
permalink: docs/task_hci_dimmcomputerepl.html
summary: You can replace a faulty dual inline memory module (DIMM) in NetApp HCI compute nodes instead of replacing the entire node.
keywords: netapp, hci, SSDs, drives, replace drives, H410S, H610S
---

= Replace DIMMs in compute nodes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can replace a faulty dual inline memory module (DIMM) in NetApp HCI compute nodes instead of replacing the entire node.

.What you'll need

* Before starting this procedure, you should have contacted NetApp Support and received a replacement part. Support will be involved during the installation of the replacement. If you have not done so already, contact https://www.netapp.com/us/contact-us/support.aspx[Support].
* You have planned for system downtime, because you need to power down or cycle the node and boot the node to NetApp Safe Mode to access the terminal user interface (TUI).

.About this task
This procedure applies to the following compute node models:

* H410C nodes. An H410C node is inserted into a 2U NetApp HCI chassis.
* H610C node. An H610C node is built into the chassis.
* H615C node. An H615C node is built into the chassis.
+
IMPORTANT: H410C and H615C nodes include DIMMs from different vendors. Ensure that you do not mix DIMMs from different vendors in one chassis.
+
NOTE: The terms "chassis" and "node" are used interchangeably in the case of H610C and H615C, because the node and chassis are not separate components.

Here are the steps involved in replacing DIMMs in compute nodes:

* <<Prepare to replace the DIMM>>
* <<Replace the DIMM from the chassis>>

== Prepare to replace the DIMM
When issues with the DIMM occur, VMware ESXi displays alerts, such as `Memory Configuration Error`, `Memory Uncorrectable ECC`, `Memory Transition to Critical`, and `Memory Critical Overtemperature`. Even if the alerts disappear after a while, the hardware problem might  persist. You should diagnose and address the faulty DIMM. You can get information about the faulty DIMM from vCenter Server. If you need more information than what is available from vCenter Server, you must run the hardware check in the TUI.

.Steps

. Access the node by logging in to vCenter Server.
. Right-click the node that is reporting the error, and select the option to place the node in maintenance mode.
. Migrate the virtual machines (VMs) to another available host.
+
NOTE: See the VMware documentation for the migration steps.

. Power down the compute node.
+
NOTE: If you have the information about which DIMM needs to be replaced and do not need to access the TUI, you can skip the following steps in this section.

. Plug in a keyboard, video, and mouse (KVM) to the back of the node that reported the error.
. Press the power button at the front of the node.
It takes approximately six minutes for the node to boot. The screen displays a boot menu.
. Use the keyboard to select *NetApp Safe Mode*.
+
IMPORTANT: You should do this in three seconds. If you miss the window, you should go through the boot process again.

. In the TUI window that opens, navigate to *Maintenance Tasks > Check Hardware*, and select *OK*.
A window opens with the results of the hardware check. If the check detects a DIMM issue, the results include a timestamp and a slot identifier.
. Record the CPU number and the DIMM slot number/ID.
This will help you identify the failed DIMM in the chassis.
. For H410C and H615C nodes, perform the steps to identify the DIMM manufacturer.
+
IMPORTANT: H410C and H615C nodes include DIMMs from different manufacturers. You should not mix different DIMM types in the same chassis. You should identify the manufacturer of the faulty DIMM and order a replacement of the same type.
+
.. Log in to the BMC to launch the console on the node.
.. Press *F2* on the keyboard to get to the Customize System/View Logs menu.
.. Enter the password when prompted.
+
NOTE: The password should match what you configured in the NetApp Deployment Engine when you set up NetApp HCI.

.. From the System Customization menu, press the down arrow to navigate to Troubleshooting Options, and press *Enter*.
.. From the Troubleshooting Mode Options menu, use the up or down arrow to enable ESXi shell and SSH, which are disabled by default.
.. Press the <Esc> key twice to exit Troubleshooting Options.
.. Run the `smbiosDump` command using one of the following options:
+
[%header,cols=2*]
|===
|Option
|Steps

|Option A
a|
. Connect to the ESXi host (compute node) using the IP address of the host and the root credentials that you defined.
. Run the `smbiosDump` command.
See the following sample output:
----
`Memory Device:#30
Location: "P1-DIMMA1"
Bank: "P0_Node0_Channel0_Dimm0"
Manufacturer:"Samsung"
Serial: "38EB8380"
Asset Tag: "P1-DIMMA1_AssetTag (date:18/15)"
Part Number: "M393A4K40CB2-CTD"
Memory Array: #29
Form Factor: 0x09(DIMM)
Type: 0x1a (DDR4)
Type Detail: 0x0080 (Synchronous)
Data Width: 64 bits (+8 ECC bits)
Size: 32 GB`
----

|Option B
a|
. Press *Alt + F1* to enter shell, and log in to the node to run the command.

|===

== Replace the DIMM from the chassis
Before you physically remove and replace the faulty DIMM in the chassis, ensure that you have performed all the link:task_hci_dimmcomputerepl.html#prepare-to-replace-the-dimm[preparatory steps].

.Steps

. Power down the chassis or node.
+
NOTE: For a H610C or H615C chassis, power down the chassis. For H410C nodes in a 2U, four-node chassis, power down only the node with the faulty DIMM.

. Remove the power cables and network cables, carefully slide the node or chassis out of the rack, and place it on a flat, antistatic surface.
+
TIP: Consider using twist ties for cables.

. Put on antistatic protection before you open the chassis cover to replace the DIMM.
. Perform the steps relevant to your node model:
+
[%header,cols=2*]
|===
|Node model
|Steps

|H410C
a|
. Find the failed DIMM by matching the slot number/ID you noted earlier with the numbering on the motherboard. The following sample images show you the location on the motherboard where you can find the DIMM slot numbers:
. Press the two retaining clips outward, and carefully pull the DIMM up. The following image shows the retaining clips:
. Install the replacement DIMM correctly. When you insert the DIMM into the slot correctly, the two clips lock in place.

+
IMPORTANT: Ensure that you touch only the rear ends of the DIMM. If you press on other parts of the DIMM, it might result in damage to the hardware.

. Install the node in the NetApp HCI chassis, ensuring that the node clicks when you slide it into place.

|H610C
a|
. Lift the cover as shown in the following image:
. Loosen the four blue lock screws at the back of the node. The following image shows the location of two lock screws; you will find the other two on the other side of the node:
. Remove both PCI card blanks.
. Remove the GPU and the airflow cover.
. Find the failed DIMM by matching the slot number/ID you noted earlier with the numbering on the motherboard. The following sample image shows you the location on the motherboard where you can find the DIMM slot numbers:
. Press the two retaining clips outward, and carefully pull the DIMM up.
. Install the replacement DIMM correctly. When you insert the DIMM into the slot correctly, the two clips lock in place.

+
IMPORTANT: Ensure that you touch only the rear ends of the DIMM. If you press on other parts of the DIMM, it might result in damage to the hardware.

. Replace all the components that you removed: GPU, airflow cover, and PCI blanks.
. Tighten the lock screws.
. Put the cover back on the node.
. Install the H610C chassis in the rack, ensuring that the chassis clicks when you slide it into place.

|H615C
a|
. Lift the cover as shown in the following image:
. Remove the GPU (if your H615C node has GPU installed) and the airflow cover.
. Find the failed DIMM by matching the slot number/ID you noted earlier with the numbering on the motherboard. The following sample image shows you the location on the motherboard where you can find the DIMM slot numbers:
. Press the two retaining clips outward, and carefully pull the DIMM up.
. Install the replacement DIMM correctly. When you insert the DIMM into the slot correctly, the two clips lock in place.

+
IMPORTANT: Ensure that you touch only the rear ends of the DIMM. If you press on other parts of the DIMM, it might result in damage to the hardware.

. Replace the airflow cover.
. Put the cover back on the node.
. Install the H610C chassis in the rack, ensuring that the chassis clicks when you slide it into place.

|===

. Insert the power cables and network cables.
Ensure that all the port lights turn on.
. Press the power button at the front of the node if it does not power on automatically when you install it.
. After the node is displayed in vSphere, right-click the name and take the node out of maintenance mode.
. Verify the hardware information as follows:
.. Log in to the baseboard management controller (BMC) UI.
.. Select *System > Hardware Information*, and check the DIMMs listed.

.What's next

After the node returns to normal operation, in vCenter, check the Summary tab to ensure that the memory capacity is as expected.

NOTE: If the DIMM is not installed correctly, the node will operate normally but with lower than expected memory capacity.

TIP: After the DIMM replacement procedure, you can clear the warnings and errors on the Hardware Status tab in vCenter. You can do this if you want to erase the history of errors related to the hardware that you replaced. https://kb.vmware.com/s/article/2011531[Learn more^].

== Find more information
* http://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* http://docs.netapp.com/sfe-122/index.jsp[SolidFire and Element Software Documentation Center^]
