---
sidebar: docs_sidebar
permalink: docs/task_nks_overview.html
summary: You can create Kubernetes clusters on NetApp HCI using the NetApp Kubernetes Service.
keywords: netapp, hci, on premise, cloud services, cloud volumes, kubernetes
---

= Managing Kubernetes clusters on NetApp HCI overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Using the NetApp Kubernetes Service (NKS) on Cloud Central, you can create and manage Kubernetes clusters anywhere using a single interface, whether you need them to reside on a private cloud or many public clouds.

== Prerequisites
Before you use the NetApp Kubernetes Service, you must enable it using the NetApp Hybrid Cloud Control.
See information on link:task_deploying_overview.html[deploying cloud services on NetApp HCI].

== Workflow overview
To create and manage clusters using the NetApp Kubernetes Service, do the following:
* link:task_nks_accessing.html[Access the NetApp Kubernetes Service] on NetApp Cloud Central.
* link:task_nks_create_cluster.html[Create a cluster on NetApp HCI] using the NetApp Kubernetes Service.
* link:task_nks_creating_projects.html[Create a project within a workspace] in the NetApp Kubernetes Service.
* link:task_nks_adding_applications.html[Add applications or solutions to your clusters] in the NetApp Kubernetes Service.

[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
* https://docs.netapp.com/us-en/kubernetes-service/[NetApp Kubernetes Service Documentation^]
