---
sidebar: sidebar
permalink: docs/task_nde_access_ui_fqdn.html
summary: Learn how to configure your system for FQDN access to the web UIs.
keywords: netapp, hci, fqdn, ui, access, web, administration
---

= Configure Fully Qualified Domain Name web UI access

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]

NetApp HCI with Element 12.2 or later enables you to access storage cluster web interfaces using the Fully Qualified Domain Name (FQDN). If you want to use the FQDN to access web user interfaces such as the Element web UI, per-node UI, or management node UI, you must first add a storage cluster setting to identify the FQDN used by the cluster. This enables the cluster to properly redirect a login session and improves integration with external services such as key managers and identity providers for multi-factor authentication.

.What you'll need
* This feature requires Element 12.2 or later.
* Configuring this feature using NetApp Hybrid Cloud Control REST APIs requires management services 2.15 or later.
* Configuring this feature using the NetApp Hybrid Cloud Control UI requires management services 2.19 or later.
* To use REST APIs, you must have deployed a management node running version 11.5 or later.
* You need fully qualified domain names for the management node and each storage cluster that resolve correctly to the management node IP address and each storage cluster IP address.

== Configure FQDN web UI access using NetApp Hybrid Cloud Control

.Steps

. Open a web browser and browse to the IP address of the management node:
+
----
https://<ManagementNodeIP>
----
. Log in to NetApp Hybrid Cloud Control by providing the storage cluster administrator credentials.
. Click the menu icon at the top right of the page.
. Select *Configure*.
. In the *Fully Qualified Domain Names* pane, click *Set Up*.
. In the resulting window, enter the FQDNs for the management node and each storage cluster.
. Click *Save*.
+
The *Fully Qualified Domain Names* pane lists each storage cluster with its associated MVIP and FQDN.

== Configure FQDN web UI access using the REST API

.Steps

. Ensure that the Element storage nodes and the management node have DNS configured correctly for the network environment so that FQDNs in the environment can be resolved. To set DNS, go to the per-node UI for storage nodes and to the management node, then select *Network Settings* > *Management Network*.
.. Per-node UI for storage nodes: `https://<storage_node_management_IP>:442`
.. Per-node UI for the management node: `https://<management_node_IP>:442`
. Access the Element API and create the following cluster interface preference using the `CreateClusterInterfacePreference` API method, and insert the cluster MVIP FQDN for the preference value:
+
* Name: `mvip_fqdn`
* Value: <Fully Qualified Domain Name for the Cluster MVIP>
+
For example, the FQDN here is `storagecluster.my.org`:
+
----
https://<Cluster_MVIP>/json-rpc/12.2?method=CreateClusterInterfacePreference&name=mvip_fqdn&value=storagecluster.my.org
----
. Change the management node settings using the REST API on the management node:
.. Access the REST API UI for the management node by entering the management node IP address followed by `/mnode/2/`. For example:
+
----
https://<management_node_IP>/mnode/2/
----
.. Click *Authorize* or any lock icon and enter the Element cluster user name and password.
.. Enter the client ID as `mnode-client`.
.. Click *Authorize* to begin a session.
.. Close the window.
.. Click *GET /settings*.
.. Click *Try it out*.
.. Click *Execute*.
.. Note whether or not the proxy is used as indicated in `"use_proxy"` by `true` or `false`.
.. Click *PUT /settings*.
.. Click *Try it out*.
.. In the request body area, enter the management node FQDN as the value for the `mnode_fqdn` parameter. Also specify whether the proxy should be used (`true` or `false` from the previous step) for the `use_proxy` parameter.
+
----
{
  "mnode_fqdn": "mnode.my.org",
  "use_proxy": false
}
----
.. Click *Execute*.

== Troubleshooting
If FQDNs are configured incorrectly, you might have problems accessing either the management node, a storage cluster, or both. Use the following information to help troubleshoot the issue.

|===
|Issue |Cause |Resolution

a|

* You get a browser error when attempting to access either the management node or the storage cluster using the FQDN.
* You cannot log in to either the management node or the storage cluster using an IP address.
|The management node FQDN and storage cluster FQDN are both incorrectly configured.
|Use the REST API instructions on this page to remove the FQDN settings and configure them again.

a|

* You get a browser error when attempting to access the storage cluster FQDN.
* You cannot log in to either the management node or the storage cluster using an IP address.
|The management node FQDN is correctly configured, but the storage cluster FQDN is incorrectly configured.
|Use the REST API instructions on this page to remove the FQDN settings and configure them again.

a|

* You get a browser error when attempting to access the management node FQDN.
* You can log in to the management node and storage cluster using an IP address.
|The management node FQDN is incorrectly configured, but the storage cluster FQDN is correctly configured.
|Log in to NetApp Hybrid Cloud Control to correct the FQDN settings in the UI, or use the REST API instructions on this page to correct the settings.
|===


[discrete]
== Find more information
* https://docs.netapp.com/us-en/element-software/api/reference_element_api_createclusterinterfacepreference.html[CreateClusterInterfacePreference API information in the SolidFire and Element Documentation^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation^]
