---
sidebar: docs_sidebar
permalink: docs/task_hcc_access.html
summary: You can log in to NetApp Hybrid Cloud Control.
keywords: netapp, hci, on premise, cloud services, hybrid cloud control, hcc
---

= Access NetApp HCI Hybrid Cloud Control
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp Hybrid Cloud Control enables you to manage NetApp HCI.

You log in to NetApp Hybrid Cloud Control by browsing to the IP address of the management node.

Using the Hybrid Cloud Control, you can do the following:

* link:concept_overview.html[Enable Cloud Services on NetApp HCI]
* link:task_hcc_dashboard.html[Monitor your NetApp HCI installation]
* link:concept_hci_upgrade_overview.html[Upgrade your NetApp HCI system]
* link:concept_hcc_expandoverview.html[Expand your NetApp HCI storage or compute resources]

*Steps*

. Open a web browser and browse to the IP address of the management node. For example:
+
https://_<ManagementNodeIP>_
. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI storage cluster administrator credentials.
+
The NetApp Hybrid Cloud Control interface appears.


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
* https://docs.netapp.com/us-en/kubernetes-service/[NetApp Kubernetes Service Documentation^]
