---
sidebar: docs_sidebar
permalink: docs/task_mnode_manage_storage_clusters.html
summary: You can edit vCenter management node controllers using the REST API UI.
keywords: netapp, mnode, management node, rest api, hci
---

= Manage storage clusters

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can create new storage clusters, edit the stored credentials for existing storage clusters, and delete storage clusters using the REST API.

.Before you begin
* Ensure that your storage cluster version is running NetApp Element software 11.3 or later.
* Ensure that you have deployed a management node running version 11.3 or later.

.Storage cluster management options

Choose one of the following options:

* <<Access the management services REST API>>
* <<Retrieve the installation ID and cluster ID of a storage cluster>>
* <<Add a new storage cluster>>
* <<Edit the stored credentials for a storage cluster>>
* <<Delete a storage cluster>>


== Access the management services REST API
You need to authenticate with the REST API UI interface before working with the REST API.

.Steps
. Access the REST API UI for management services by entering the management node IP address
followed by `/mnode`:
+
----
https://[IP address]/mnode
----

. Click *Authorize* or any lock icon and complete the following:
+
.. Enter the cluster user name and password.
.. Enter the client ID as `mnode-client`.
.. Click *Authorize* to begin a session.
.. Close the window.

== Retrieve the installation ID and cluster ID of a storage cluster
You can use the REST API get the installation ID and the ID of the storage cluster. You need the installation ID to add a new storage cluster, and the cluster ID to modify or delete a specific cluster.

NOTE: Ensure you have followed the steps in <<Access the management services REST API>> to authenticate with the REST API UI interface before continuing.

.Steps
. Click *GET /installations*.
. Click *Try it out*.
. Click *Execute*.
+
The API returns a list of all known storage cluster installations.
. From the code 200 response body, save the value in the `id` field for the installation.
. Click *GET /clusters*.
. Click *Try it out*.
. Paste the value you copied earlier into the `installationId` parameter.
. Click *Execute*.
+
The API returns a list of all known storage clusters in this installation.
. From the code 200 response body, find the correct storage cluster and copy the value in the cluster's `storageId` field to your clipboard.

== Add a new storage cluster
You can use the REST API to add a new storage cluster to the inventory of an installation.

NOTE: Ensure you have followed the steps in <<Access the management services REST API>> and <<Retrieve the installation ID and cluster ID of a storage cluster>> to authenticate with the REST API UI interface and copy the required cluster information before continuing.

.Steps
. Click *POST /clusters*.
. Click *Try it out*.
. Enter the new storage cluster's information in the following parameters in the *Request body* field:
+
|===
|Parameter |Type |Description

|`installationId`
|string
|The installation in which to create the new storage cluster. Enter the `id` you saved earlier into this parameter.

|`mvip`
|string
|The IPv4 management virtual IP address (MVIP) of the storage cluster.

|`userId`
|string
|The user ID used to communicate with the storage cluster (the user must have administrator privileges).

|`password`
|string
|The password used to communicate with the storage cluster.
|===
. Click *Execute*.
+
The API returns an object containing information about the newly created storage cluster, such as its name, version, and IP address information.

== Edit the stored credentials for a storage cluster
You can edit the stored credentials that NetApp Hybrid Cloud Control uses to log in to a storage cluster. The user you choose must have cluster admin access.

NOTE: Ensure you have followed the steps in <<Access the management services REST API>> and <<Retrieve the installation ID and cluster ID of a storage cluster>> to authenticate with the REST API UI interface and copy the required cluster information before continuing.

.Steps
. Click *PUT /clusters/{storageId}*.
. Click *Try it out*.
. Paste the storage cluster ID you copied earlier into the `storageId` parameter.
. Change one or both of the following parameters in the *Request body* field:
+
|===
|Parameter |Type |Description

|`userId`
|string
|The user ID used to communicate with the storage cluster (the user must have administrator privileges).

|`password`
|string
|The password used to communicate with the storage cluster.
|===
. Click *Execute*.

== Delete a storage cluster
You can delete a storage cluster if it is no longer in service.

NOTE: Ensure you have followed the steps in <<Access the management services REST API>> and <<Retrieve the installation ID and cluster ID of a storage cluster>> to authenticate with the REST API UI interface and copy the required cluster information before continuing.

.Steps
. Click *DELETE /clusters/{storageId}*.
. Click *Try it out*.
. Enter the storage cluster ID you copied earlier in the `storageId` parameter.
. Click *Execute*.
+
Upon success, the API returns an empty response.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
