---
sidebar: docs_sidebar
permalink: docs/task_nde_start_deployment.html
summary: Begin deploying NetApp HCI.
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access
---

= Create a node template with Trident networking support
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware

[.lead]
If your NetApp HCI environment does not have a route between the management and storage networks, and you deploy user clusters with Trident persistent storage support, you need to further configure your networks after installing Trident. You need to enable communication between the management and storage networks for the user clusters you deploy. You can do this by creating a new node template with storage networking support, and using the new template when you create Trident-enabled user clusters.

.Steps

. Open the Rancher IP address or domain name in a web browser, and log in to the web UI.
. At the top right of the page, click on the user menu.
. In the resulting menu, Select *Node Templates*.
. For the active template (vsphere-default), click the ellipses at the far right of the row.
. From the resulting menu, select *Clone*.
. On the *Clone node template from* page, scroll to the third section, *Instance Options*.
. Under the *Networks* heading, select the network labeled `NetApp HCI VDS 01-HCI_Internal_Storage_Data_Network` from the list.
. Near the bottom of the page, enter a name for the newly cloned template in the *Name* field.
. Click *Save*.

When you create new user clusters that use Trident, use the newly created node template.

1. Deploy a user cluster with existing default template
2. Connect storage network to the user cluster.
3. In Rancher, grab ssh private keys for each node in the user cluster, pairing with the IPs
(node steps for each node)
4. (if using default node template) ssh in to each node (ssh -i <private key filename> <ip address>), edit `/etc/netplan/50-cloud-init.yaml` file, and update the file so that it resembles this example:

----
network:
    ethernets:
        ens192:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:1d:41
            set-name: ens192
        ens224:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:5b:e9
            set-name: ens224
    version: 2
----

5. Run command `netplan try` and monitor the output. It should work with no further input
(end node steps)
6. You are good!

NOTE: You can make these changes as part of a custom node template if you like for future user clusters.
