---
sidebar: docs_sidebar
permalink: docs/task_mnode_install_add_storage_NIC.html
summary: If you are using an additional NIC for storage, you should set up that network interface.
keywords: netapp, element, management node, mnode, network, nic, storage nic
---

= Configure a storage Network Interface Controller (NIC)

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If you are using an additional NIC for storage, you can SSH in to the management node or use the vCenter console and run a curl command to set up that network interface.

.Before you begin

• You know your eth0 IP address.
• Your cluster version is running NetApp Element software 11.3 or later.
• You have deployed a management node 11.3 or later.

.Steps
. Open an SSH or vCenter console.
. Replace the values in the following command template and run the command:
+
NOTE: Values are represented by `$` for each of the required parameters for your new storage network interface. The `cluster` object in the following template is required and can be used for management node host name renaming. The `--insecure` or `-k` options should not be used in production environments.

+
----
curl -u $mnode_user_name:$mnode_password --insecure -X POST \
https://$mnode_IP:442/json-rpc/10.0 \
-H 'Content-Type: application/json' \
-H 'cache-control: no-cache' \
-d ' {
     "params": {
               "network": {
                          "$eth1": {
                                   "#default" : false,
                                   "address" : "$storage_IP",
                                   "auto" : true,
                                   "family" : "inet",
                                   "method" : "static",
                                   "mtu" : "9000",
                                   "netmask" : "$subnet_mask",
                                   "status" : "Up"
                                   }
                          },
              "cluster": {
                         "name": "$mnode_host_name"
                         }
             },
    "method": "SetConfig"
}
'
----

[discrete]
== Find more Information
* link:task_mnode_add_assets.html[Add an asset to the management node]
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
