---
sidebar: docs_sidebar
permalink: docs/task_mnode_add_assets.html
summary: You can add compute and controller assets to the management node configuration using the REST API UI.
keywords: netapp, mnode, management node, rest api, hci
---

= Add an asset to the management node

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can add compute and controller assets to the management node configuration using the REST API UI.

You might need to add an asset if you recently scaled your installation and new assets were not added automatically to your configuration. Use these APIs to add assets that are recent additions to your installation.


.Before you begin
* Ensure that your cluster version is running NetApp Element software 11.3 or later.
* Ensure that you have deployed a management node running version 11.3 or later.

.Steps
. Access the REST API UI for management services by entering the management node IP address
followed by /mnode:
+
----
https://[IP address]/mnode
----

. Click *Authorize* or any lock icon and complete the following:
+
.. Enter the cluster user name and password.
.. Enter the client ID as `mnode-client`.
.. Click *Authorize* to begin a session.
. To add a compute node or controller sub-asset to an existing base asset, click one of the following.
+
Your installation has a base asset configuration that was created during installation or upgrade.
+
[cols=2*,options="header",cols="40,60"]
|===
| Option
| Description
| POST /assets/{asset_id}/
controllers | Run this command to create a controller sub-asset.
| POST /assets/{asset_id}/
compute-nodes | Run this command to create a compute node sub-asset.
|===

. Click *Try it out*.
. Enter the required payload values as defined in the *Model* tab.
+
IMPORTANT: For compute node assets, remove the "hardware_tag" parameter suggested in the
payload example.

. Enter the parent base asset ID in the *asset_id* field.
. Click *Execute*.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
