---
sidebar: docs_sidebar
permalink: docs/task_hcc_add_vol_access_group.html
summary: Learn how to add a volume access group.
keywords: netapp, hci, on premise, cluster, element
---

= Add a volume access group

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
As part of a NetApp HCI or SolidFire storage system upgrade, you upgrade NetApp Element software.

You must use HealthTools suite of tools to upgrade storage node software.

.What you'll need

* You are running management node 12.2 or later.
* You have upgraded your management services to at least version 2.15.28.
* Ensure you have a logical naming scheme for volume access groups.
+
NetApp Hybrid Cloud Control storage management is not available in earlier service bundle versions.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. Select the *Create Access Group* button.
. In the resulting dialog, enter a name for the new volume access group (this is required).
. (Optional) In the *Initiators* section, select one or more initiators to associate with the new volume access group.
. (Optional) In the *Volumes* section, select one or more volumes to include in this volume access group.
. Select *Create Access Group*.

[discrete]
== Find more information

* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
