---
sidebar: docs_sidebar
permalink: docs/task_hcc_manage_vol_access_groups.html
summary: Learn how to add new a volume access groups to work with NetApp HCI storage volumes, remove volume access groups from the system, edit existing volume access groups, and view details of volume access groups.
keywords: netapp, hci, on premise, cluster, element
---

= Manage volume access groups

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can add new volume access groups, delete existing volume access groups, edit the details of a volume access group, and view the details of a volume access group using NetApp Hybrid Cloud Control.

[NOTE]
======================
Volume access groups have the following limits:

* A maximum of 64 IQNs or WWPNs are allowed in an access group.
* An access group can be made up of a maximum of 2000 volumes.
* An IQN or WWPN can belong to only one access group.
* A single volume can belong to a maximum of four access groups.
======================

.What you'll need

* You have administrator credentials for this NetApp HCI system.
* You are running management node 12.2 or later.
* You have upgraded your management services to at least version 2.15.28. NetApp Hybrid Cloud Control storage management is not available in earlier service bundle versions.
* Ensure you have a logical naming scheme for volume access groups.

== Add a volume access group
You can add a volume access group to NetApp HCI using NetApp Hybrid Cloud Control.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. Select the *Create Access Group* button.
. In the resulting dialog, enter a name for the new volume access group.
. (Optional) In the *Initiators* section, select one or more initiators to associate with the new volume access group.
+
If you associate an initiator with the volume access group, that initiator can access each volume in the group without the need for authentication.
. (Optional) In the *Volumes* section, select one or more volumes to include in this volume access group.
. Select *Create Access Group*.

== Delete a volume access group
You can remove a volume access group from NetApp HCI using NetApp Hybrid Cloud Control, and at the same time remove the initiators associated with this access group from the system.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to delete.
. In the options menu, select *Delete*.
+
The *Delete Access Group* dialog appears.
. If you do not wish to delete the initiators that are associated with the access group, deselect the *Delete initiators in this access group* checkbox.
. Confirm the delete operation by selecting *Yes*.

== Edit a volume access group
You can edit the properties of an existing NetApp HCI volume access group using NetApp Hybrid Cloud Control.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to edit.
. In the options menu, select *Edit*.
+
The *Edit Access Group* dialog appears.
. Make any needed changes to the name, associated initiators, or associated volumes.
. Confirm your changes by selecting *Save*.
. In the *Access Groups* table, verify that the access group reflects your changes.

== View details of a volume access group
You can view the details of an existing NetApp HCI volume access group, such as attached volumes and initiators, using NetApp Hybrid Cloud Control.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to edit.
. In the options menu, select *Details*.
+
The *Volume Access Group Details* dialog appears.

[discrete]
== Find more information
* http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-ug/GUID-EBCB1031-1B2D-472C-92E3-E0CB52B4156C.html[Working with volume access groups and initiators^]
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
