---
sidebar: sidebar
permalink: docs/task_trident_configure_networking.html
summary: Enable Trident support for user clusters.
keywords: netapp, hci, netapp, networking, clusters, user, trident, rancher
---

= Enable Trident support for user clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If your NetApp HCI environment does not have a route between the management and storage networks, and you deploy user clusters that need Trident support, you need to further configure your user cluster networks after installing Trident. For each user cluster, you need to enable communication between the management and storage networks. You can do this by modifying the networking configuration for each node in the user cluster.

.About this task
Follow these general steps to modify the networking configuration for each node in the user cluster. These steps assume that you created the user cluster with the default node template that is installed with Rancher on NetApp HCI.

NOTE: You can make these changes as part of a custom node template to use for future user clusters.

.Steps

. Deploy a user cluster with existing default template.
. Connect the storage network to the user cluster.
.. Open the VMware vSphere web client for the connected vCenter instance.
.. In the Hosts and Clusters inventory tree, select a node in the newly deployed user cluster.
.. Edit the node's settings.
.. In the settings dialog, add a new network adapter.
.. In the *New Network* drop down list, browse for a network and select *HCI_Internal_Storage_Data_Network*.
.. Expand the network adapter section and record the MAC address for the new network adapter.
.. Click *OK*.
. In Rancher, download the SSH private key file for each node in the user cluster.
. Connect using SSH to a node in the user cluster, using the private key file that you have downloaded for that node:
+
----
ssh -i <private key filename> <ip address>
----
. As the superuser, edit and save the `/etc/netplan/50-cloud-init.yaml` file so that it includes the `ens224` section, similar to the following example. Replace `<MAC address>` with the MAC address you recorded earlier:
+
----
network:
    ethernets:
        ens192:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:1d:41
            set-name: ens192
        ens224:
            dhcp4: true
            match:
                macaddress: <MAC address>
            set-name: ens224
    version: 2
----
. Use the following command to reconfigure the network:
+
----
`netplan try`
----
. Repeat steps 4 through 6 for each remaining node in the user cluster.
. When you have reconfigured the network for each node in the user cluster, you can deploy applications in the user cluster that utilize Trident.
