---
sidebar: docs_sidebar
permalink: docs/task_hcc_upgrade_element_software.html
summary: As part of the entire NetApp HCI upgrade, you also upgrade NetApp Element software.
keywords: netapp, hci, on premise, cluster, element
---

= Upgrade Element software

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To upgrade the NetApp Element software, you must use the `sfinstall` file included in the HealthTools suite of tools.


.What you'll need

IMPORTANT: Before you upgrade Element software, check upgrade path information for the Element version you are upgrading to and verify that the upgrade path is valid.
https://kb.netapp.com/app/answers/answer_view/a_id/1088254[NetApp KB 1088254: Upgrade matrix for storage clusters running NetApp Element Software]

* The management node in your environment is running version 11.0, 11.1 or later.
* You have the latest version of HealthTools.
* You verified that the cluster is ready to be upgraded See link:task_hcc_upgrade_element_prechecks.html[Run Element storage health checks prior to upgrading storage].

== Upgrade Element software at connected sites

.Steps

. For NetApp HCI systems, go to the NetApp HCI software https://mysupport.netapp.com/products/p/hci.html[download page]. For standalone SolidFire storage systems, go to the Element software https://mysupport.netapp.com/products/p/element_software.html[download page].
. Select the correct software release and download the latest storage node image to a computer that is not the management node.
. Copy the ISO file to the management node in an accessible location like `/tmp`.
+
TIP: You can do this by using, for example, SCP.

+
When you upload the ISO file, make sure that the name of the file does not change, otherwise later steps will fail.

. *Optional*: Download the ISO from the management node to the cluster nodes before the upgrade.
+
This step reduces the upgrade time by pre-staging the ISO on the storage nodes and running additional internal checks to ensure that the cluster is in a good state to be upgraded. Performing this operation will not put the cluster into "upgrade" mode or restrict any of the cluster operations.
+
----
sfinstall -u <cluster_username> -p <cluster_password> <MVIP> <path-toinstall-file-ISO> --stage
----
+
NOTE: For passwords that contain special characters, add a backslash (`\`) before each special character. For example, `mypass!@1` should be entered as `mypass\!\@`. Alternatively, omit the password from the command line to allow `sfinstall` to prompt for the information.

+
*Example*
See the following sample input:
+
----
sfinstall 10.117.0.244 -u admin -p admin
/tmp/solidfire-rtfisodium-11.0.0.345.iso --stage
----
+
The output for the sample shows that `sfinstall` attempts to verify if a newer version of `sfinstall` is available:
+
----
sfinstall 10.117.0.244 -u admin -p admin
/tmp/solidfire-rtfisodium-11.0.0.345.iso 2018-10-01 16:52:15:
Newer version of sfinstall available.
This version: 2018.09.01.130, latest version: 2018.06.05.901.
The latest version of the HealthTools can be downloaded from:
https:// mysupport.netapp.com/NOW/cgi-bin/software/
or rerun with --skip-version-check
----
See the following sample excerpt from a successful pre-stage operation:
+
NOTE: When staging completes, the message will display `Storage Node Upgrade Staging Successful` after the upgrade event.

+
----
flabv0004 ~ # sfinstall -u admin -p admin
10.117.0.87 solidfire-rtfi-sodium-patch3-11.3.0.14171.iso --stage
2019-04-03 13:19:58: sfinstall Release Version: 2019.01.01.49 Management Node Platform:
Ember Revision: 26b042c3e15a Build date: 2019-03-12 18:45
2019-04-03 13:19:58: Checking connectivity to MVIP 10.117.0.87
2019-04-03 13:19:58: Checking connectivity to node 10.117.0.86
2019-04-03 13:19:58: Checking connectivity to node 10.117.0.87
...
2019-04-03 13:19:58: Successfully connected to cluster and all nodes
...
2019-04-03 13:20:00: Do you want to continue? ['Yes', 'No']: Yes
...
2019-04-03 13:20:55: Staging install pack on cluster nodes
2019-04-03 13:20:55: newVersion: 11.3.0.14171
2019-04-03 13:21:01: nodeToStage: nlabp2814, nlabp2815, nlabp2816, nlabp2813
2019-04-03 13:21:02: Staging Node nlabp2815 mip=[10.117.0.87] nodeID=[2] (1 of 4 nodes)
2019-04-03 13:21:02: Node Upgrade serving image at
http://10.117.0.204/rtfi/solidfire-rtfisodium-
patch3-11.3.0.14171/filesystem.squashfs
...
2019-04-03 13:25:40: Staging finished. Repeat the upgrade command without the --stage option to start the upgrade.
----

+
The staged ISOs will be automatically deleted after the upgrade completes. However, if the upgrade has not started and needs to be rescheduled, ISOs can be manually de-staged using the command:
+
`sfinstall -u <cluster_username> -p <cluster_password> <MVIP> --destage`

+
After the upgrade has started, the de-stage option is no longer available.

. Start the upgrade with the `sfinstall` command and the path to the ISO file:
+
`sfinstall -u <cluster_username> -p <cluster_password> <MVIP> <path-toinstall-file-ISO>`

+
*Example*
+
See the following sample input command:
+
----
sfinstall 10.117.0.244 -u admin -p admin /tmp/solidfire-rtfi-sodium-11.0.0.345.iso
----
+
The output for the sample shows that `sfinstall` attempts to verify if a newer version of `sfinstall` is available:
+
----
sfinstall 10.117.0.244 -u admin -p admin /tmp/solidfire-rtfi-sodium-11.0.0.345.iso
2018-10-01 16:52:15: Newer version of sfinstall available.
This version: 2018.09.01.130, latest version: 2018.06.05.901.
The latest version of the HealthTools can be downloaded from:
https://mysupport.netapp.com/NOW/cgi-bin/software/ or rerun with --skip-version-check
----
+
See the following sample excerpt from a successful upgrade. Upgrade events can be used to monitor the progress of the upgrade.
+
----
# sfinstall 10.117.0.161 -u admin -p admin solidfire-rtfi-sodium-11.0.0.761.iso
2018-10-11 18:28
Checking connectivity to MVIP 10.117.0.161
Checking connectivity to node 10.117.0.23
Checking connectivity to node 10.117.0.24
...
Successfully connected to cluster and all nodes
###################################################################
You are about to start a new upgrade
10.117.0.161
10.3.0.161
solidfire-rtfi-sodium-11.0.0.761.iso
Nodes:
10.117.0.23 nlabp1023 SF3010 10.3.0.161
10.117.0.24 nlabp1025 SF3010 10.3.0.161
10.117.0.26 nlabp1027 SF3010 10.3.0.161
10.117.0.28 nlabp1028 SF3010 10.3.0.161
###################################################################
Do you want to continue? ['Yes', 'No']: yes
...
Watching for new network faults. Existing fault IDs are set([]).
Checking for legacy network interface names that need renaming
Upgrading from 10.3.0.161 to 11.0.0.761 upgrade method=rtfi
Waiting 300 seconds for cluster faults to clear
Waiting for caches to fall below threshold
...
Installing mip=[10.117.0.23] nodeID=[1] (1 of 4 nodes)
Starting to move primaries.
Loading volume list
Moving primary slice=[7] away from mip[10.117.0.23] nodeID[1] ssid[11] to new ssid[15]
Moving primary slice=[12] away from mip[10.117.0.23] nodeID[1] ssid[11] to new ssid[15]
...
Installing mip=[10.117.114.24] nodeID=[2] (2 of 4 nodes)
Starting to move primaries.
Loading volume list
Moving primary slice=[5] away from mip[10.117.114.24] nodeID[2] ssid[7] to new ssid[11]
...
Install of solidfire-rtfi-sodium-11.0.0.761 complete.
Removing old software
No staged builds present on nodeID=[1]
No staged builds present on nodeID=[2]
...
Starting light cluster block service check
----



== Upgrade Element software at dark sites
You must use the HealthTools suite of tools to update NetApp Element software at a dark site.

.What you'll need

. For NetApp HCI systems, go to the NetApp HCI software https://mysupport.netapp.com/products/p/hci.html[download page]. For standalone SolidFire storage systems, go to the Element software https://mysupport.netapp.com/products/p/element_software.html[download page].
. Select the correct software release and download the latest storage node image to a computer that is not the management node.
. Download this https://library.netapp.com/ecm/ecm_get_file/ECMLP2840740[JSON file] from the NetApp Support Site on a computer that is not the management node and rename it to `metadata.json`.
. Copy the ISO file to the management node in an accessible location like `/tmp`.
+
TIP: You can do this by using, for example, SCP. When you upload the ISO file, make sure that the name of the file does not change, otherwise later steps will fail.

.Steps

. Run the `sfupdate-healthtools` command:
+
----
sfupdate-healthtools <path-to-healthtools-package>
----
. Check the installed version:
+
----
sfupdate-healthtools -v
----
. Check the latest version against the metadata JSON file:
+
----
sfupdate-healthtools -l --metadata=<path-to-metadata-json>
----
. Ensure that the cluster is ready:
+
----
sudo sfupgradecheck -u <cluster_username> -p <cluster_password> MVIP --metadata=<path-to-metadata-json>
----
. Run the `sfinstall` command with the path to the ISO file and the metadata JSON file:
+
----
sfinstall -u <cluster_username> -p <cluster_password> <MVIP> <path-toinstall-file-ISO> --metadata=<path-to-metadata-json-file>
----
+
See the following sample input command:
+
----
sfinstall -u admin -p admin 10.117.78.244 /tmp/solidfire-rtfi-11.3.0.345.iso --metadata=/tmp/metadata.json
----
+
*Optional* You can add the `--stage` flag to the `sfinstall` command to pre-stage the upgrade in advance.


== What happens if an upgrade fails
If the software upgrade fails, you can pause the upgrade.

TIP: You should pause an upgrade only with Ctrl-C. This enables the system to clean itself up.

When `sfinstall` waits for cluster faults to clear and if any failure causes the faults to remain, `sfinstall` will not proceed to the next node.

.Steps
. You should stop `sfinstall` with Ctrl+C.
. Contact NetApp Support to assist with the failure investigation.
. Resume the upgrade with the same `sfinstall` command.
. When an upgrade is paused by using Ctrl+C, if the upgrade is currently upgrading a node, choose one of these options:

* *Wait*: Allow the currently upgrading node to finish before resetting the cluster constants.
* *Continue*: Continue the upgrade, which cancels the pause.
* *Abort*: Reset the cluster constants and abort the upgrade immediately.
+
NOTE: Aborting the cluster upgrade while a node is being updated might result in the drives being ungracefully removed from the node. If the drives are ungracefully removed, adding the drives back during an upgrade will require manual intervention by NetApp Support. The node might be taking longer to do firmware updates or postupdate syncing activities. If the upgrade progress seems stalled, contact NetApp Support for assistance.




[discrete]
== Find more information

* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
