---
sidebar: docs_sidebar
permalink: docs/task_hcc_dashboard.html
summary: You can view storage and compute resources on the NetApp Hybrid Cloud Control Dashboard.
keywords: netapp, hci, on premise, hcc, hybrid cloud control
---

= View storage and compute resources on the HCC Dashboard

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
With the NetApp Hybrid Control Dashboard, you can view all your storage and compute resources at a glance.

*Steps*

. Open a web browser and browse to the IP address of the management node. For example:
+ https://_management_node_IP_
. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI storage cluster administrator credentials.
. View the Dashboard:
* *Storage*: Displays the number of storage clusters, storage nodes, and total volumes.
* *Compute*: Displays the number of compute clusters and total compute nodes.

TIP: To view cluster health, look at the SolidFire Active IQ Dashboard. See link:task_hcc_activeiq.html[Viewing performance, capacity, and cluster health in SolidFire Active IQ].

You can view storage and compute resources at a glance on the Hybrid Cloud Control Dashboard.

== Steps

. Go to the https://fabric.netapp.io[NetApp Fabric Orchestrator^] Login page.
. Enter your Cloud Central login credentials and click *Login*.
+
TIP: If you do not see any systems listed, make sure that the NetApp HCI administrator is added to your NetApp Cloud Central account.

. If you do not have a Cloud Central account, on the Cloud Central Login page, click *Sign Up*.

+
Using Cloud Central, you can set up accounts either as individual accounts or as Federated accounts:

.. You can make a new account with name, email, and password and then you will be logged in. This is the simplest type of account.
.. If you are part of a Cloud Central Federated organization, you enter your email and are then routed to the organization login.
. From other Cloud Central products, select *Products* > *NetApp Fabric Orchestrator*.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
