---
sidebar: sidebar
permalink: docs/task_hci_manage_overview.html
summary: You can configure the FQDM and manage credentials for NetApp HCI, user accounts, storage clusters, volumes, volume access groups, initiators, volume QoS policies and the management node.
keywords: netapp, hci, install, deploy, get started, configure, fqdn, fully qualified domain name
---

= NetApp HCI management overview

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can configure the Fully Qualified Domain Name and manage credentials for NetApp HCI, user accounts, storage clusters, volumes, volume access groups, initiators, volume QoS policies and the management node.

Here are the items you can work with:

* link:task_nde_access_ui_fqdn.html[Configure Fully Qualified Domain Name web UI access]
* link:task_post_deploy_credentials.html[Change credentials in NetApp HCI]
* link:task_hci_credentials_vcenter_esxi.html[Update vCenter and ESXi credentials]
* link:task_hcc_manage_storage_overview.html[Manage NetApp HCI storage assets]
* link:task_mnode_work_overview.html[Work with the management node]
* link:concept_nde_hci_power_off_on.html[Power your NetApp HCI system off or on]



[discrete]
== Find more information
*	https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources page^]
