---
sidebar: sidebar
permalink: docs/task_rancher_config_anti_affinity.html
summary: Learn about how to configure anti-affinity rules for Rancher VMs to help with host resiliency.
keywords: netapp, hci, rancher, deploy, cluster, kubernetes, anti, affinity, resiliency
---

= Improve Rancher VM resiliency
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
After you deploy Rancher on NetApp HCI, your vSphere environment will contain three new nodes as virtual machines to host the Rancher environment. The Rancher web UI is available from each of these nodes. For full resiliency, each of the three virtual machines along with the corresponding virtual disks should reside on a different physical host after events like power cycles and failovers.

To ensure that each VM and its resources remain on a different physical host, you can create VMware vSphere Distributed Resource Scheduler (DRS) anti-affinity rules. This is not automated as part of Rancher on NetApp HCI deployment.

For instructions on how to configure DRS anti-affinity rules, see the following VMware documentation resources:

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.resmgmt.doc/GUID-FBE46165-065C-48C2-B775-7ADA87FF9A20.html[Create VM Anti-Affinity Rules]

https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.avail.doc/GUID-E137A9F8-17E4-4DE7-B986-94A0999CF327.html[vSphere HA and DRS Affinity Rules]

[discrete]
== Find more information
* https://rancher.com/docs/rancher/v2.x/en/overview/architecture/[Rancher documentation about architecture^]
* https://rancher.com/docs/rancher/v2.x/en/overview/concepts/[Kubernetes terminology for Rancher]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
