---
sidebar: docs_sidebar
permalink: docs/task_hcc_add_vol_access_group.html
summary: Learn how to add a volume access group.
keywords: netapp, hci, on premise, cluster, element
---

= Add a volume access group

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can add a volume access group to NetApp HCI using NetApp Hybrid Cloud Control.

.What you'll need

* You have administrator credentials for this NetApp HCI system.
* You are running management node 12.2 or later.
* You have upgraded your management services to at least version 2.15.28. NetApp Hybrid Cloud Control storage management is not available in earlier service bundle versions.
* Ensure you have a logical naming scheme for volume access groups.

[NOTE]
======================
Volume access groups have the following limits:

* A maximum of 64 IQNs or WWPNs are allowed in an access group.
* An access group can be made up of a maximum of 2000 volumes.
* An IQN or WWPN can belong to only one access group.
* A single volume can belong to a maximum of four access groups.
======================

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. Select the *Create Access Group* button.
. In the resulting dialog, enter a name for the new volume access group.
. (Optional) In the *Initiators* section, select one or more initiators to associate with the new volume access group.
+
If you associate an initiator with the volume access group, that initiator can access each volume in the group without the need for authentication.
. (Optional) In the *Volumes* section, select one or more volumes to include in this volume access group.
. Select *Create Access Group*.

[discrete]
== Find more information
* http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-ug/GUID-EBCB1031-1B2D-472C-92E3-E0CB52B4156C.html[Working with volume access groups and initiators^]
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
