---
sidebar: docs_sidebar
permalink: docs/task_hcc_edit_bmc_info.html
summary: You can use NetApp Hybrid Cloud Control to edit Baseboard Management Controller (BMC) connection information so that NetApp HCI can connect to it.
keywords: netapp, hci, BMC, connection, credentials, monitor
---

= Edit Baseboard Management Controller connection information

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can store Baseboard Management Controller (BMC) administrator credentials in NetApp Hybrid Cloud Control for each of your compute nodes. This enables you to use NetApp Hybrid Cloud Control or teh REST API to seamlessly upgrade BMC firmware.

.Edit BMC connection information options

Choose one of the following options:

* <<Use NetApp Hybrid Cloud Control to edit BMC information>>
* <<Use the REST API to edit BMC information>>

== Use NetApp Hybrid Cloud Control to edit BMC information
You can add and edit the stored BMC credentials using the NetApp Hybrid Cloud Control Dashboard.

.Steps
. Open a web browser and browse to the IP address of the management node. For example:
+
----
https://[management node IP address]
----
. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI storage cluster administrator credentials.
. In the left navigation blue box, select the NetApp HCI installation.
+
The NetApp Hybrid Cloud Control Dashboard appears.
. In the left navigation, click *Nodes*.
. To view compute inventory information, click *Compute*.
+
A list of your compute nodes appears. The *BMC Connection Status* column shows the result of BMC connection attempts for each compute node. If the connection attempt fails for a compute node, an error message is displayed in this column for that node.
. To add or edit the stored BMC credentials for a compute node with BMC connection errors, click *Edit connection settings* in the error message text.
. In the dialog that appears, add the correct administrator user name and password for the BMC of this compute node.
. Click *Save*.
. Repeat steps 5 through 7 for any compute node that has missing or incorrect stored BMC credentials.

== Use the REST API to edit BMC information
You can use REST API to collect NetApp HCI logs.

.Steps
. Locate the storage cluster ID:
.. Open the management node REST API UI on the management node:
+
----
https://[management node IP]/logs/1
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client` if the value is not already populated.
... Click *Authorize* to begin a session.
. Collect logs from NetApp HCI:
.. Click *POST /bundle*.
.. Click *Try it out*.
.. Change the values of the following parameters in the *Request body* field depending on which type of logs you need to collect and for what time range:
+
|===
|Parameter |Type |Description

|`modifiedSince`
|Date string
|Only include logs modified after this date and time. For example, the value "2020-07-14T20:19:00.000Z" defines a start date of July 14, 2020 at 20:19 UTC.

|`computeLogs`
|Boolean
|Set this parameter to `true` to include compute node logs.

|`computeIds`
|UUID array
|If `computeLogs` is set to `true`, populate this parameter with the management node asset IDs of compute nodes to limit log collection to those specific compute nodes. Use the `GET https://[management node IP]/logs/1/bundle/options` endpoint to see all possible node IDs you can use.

|`mnodeLogs`
|Boolean
|Set this parameter to `true` to include management node logs.

|`storageCrashDumps`
|Boolean
|Set this parameter to `true` to include storage node crash debug logs.

|`storageLogs`
|Boolean
|Set this parameter to `true` to include storage node logs.

|`storageNodeIds`
|UUID array
|If `storageLogs` is set to `true`, populate this parameter with the storage cluster node IDs to limit log collection to those specific storage nodes. Use the `GET https://[management node IP]/logs/1/bundle/options` endpoint to see all possible node IDs you can use.
|===
.. Click *Execute* to begin log collection.
The response should return a response similar to the following:
+
----
{
  "_links": {
    "self": "https://10.1.1.5/logs/1/bundle"
  },
  "taskId": "4157881b-z889-45ce-adb4-92b1843c53ee",
  "taskLink": "https://10.1.1.5/logs/1/bundle"
}
----
. Check on the status of the log collection task:
.. Click *GET /bundle*.
.. Click *Try it out*.
.. Click *Execute* to return a status of the collection task.
.. Scroll to the bottom of the response body.
+
You should see a `percentComplete` attribute detailing the progress of the collection. If the collection is complete, the `downloadLink` attribute contains the full download link including the file name of the log package.

.. Copy the file name at the end of the `downloadLink` attribute.
. Download the collected log package:
.. Click *GET /bundle/{filename}*.
.. Click *Try it out*.
.. Paste the file name you copied earlier into the `filename` parameter text field.
.. Click *Execute*.
+
After execution, a download link appears in the response body area.

.. Click *Download file* and save the resulting file to your computer.
+
The log package is in a compressed UNIX .tgz file format.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
