---
sidebar: sidebar
permalink: docs/task_hcc_upgrade_element_software.html
summary: As part of a NetApp HCI system upgrade, you upgrade NetApp Element software.
keywords: netapp, hci, cluster, element, H610S upgrade, hcc
---

= Upgrade Element software

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To upgrade NetApp Element software, you can use the NetApp Hybrid Cloud Control UI or REST API. Certain operations are suppressed during an Element software upgrade, such as adding and removing nodes, adding and removing drives, and commands associated with initiators, volume access groups, and virtual networks, among others.

NOTE: Beginning with Element 12.5, NetApp HealthTools is no longer supported for Element software upgrades. If you are running Element 11.0 or 11.1, you must first link:https://docs.netapp.com/us-en/hci19/docs/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools[upgrade to Element 12.3 using HealthTools^] and then upgrade to Element 12.5 or later using NetApp Hybrid Cloud Control.

.What you'll need

* *Admin privileges*: You have storage cluster administrator permissions to perform the upgrade.
* *Valid upgrade path*: You have checked upgrade path information for the Element version you are upgrading to and verified that the upgrade path is valid. See https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_is_the_upgrade_matrix_for_storage_clusters_running_NetApp_Element_software%3F[NetApp KB: Upgrade matrix for storage clusters running NetApp Element Software^]
* *System time sync*: You have ensured that the system time on all nodes is synced and that NTP is correctly configured for the storage cluster and nodes. Each node must be configured with a DNS nameserver in the per-node web UI (`https://[IP address]:442`) with no unresolved cluster faults related to time skew.
* *System ports*: If you are using NetApp Hybrid Cloud Control for upgrades, you have ensured that the necessary ports are open. See link:hci_prereqs_required_network_ports.html[Network ports] for more information.
* *Management node*: For NetApp Hybrid Cloud Control UI and API, the management node in your environment is running version 11.3.
* *Management services*: You have updated your management services bundle to the latest version.

IMPORTANT: You must upgrade to the latest management services bundle before upgrading your Element software to version 12.5 or later. If you are updating your Element software to version 12.5 or later, you need management services 2.21.61 or later to proceed.

* *Cluster health*: You have verified that the cluster is ready to be upgraded. See link:task_hcc_upgrade_element_prechecks.html[Run Element storage health checks prior to upgrading storage].
* *Updated baseboard management controller (BMC) for H610S nodes*: You have upgraded the BMC version for your H610S nodes. See the link:rn_H610S_BMC_3.84.07.html[release notes and upgrade instructions].
[[element-upgrade-time]]
include::../_include/element_software_and_storage_firmware_upgrade_time.adoc[]
* *End User License Agreement (EULA)*: Beginning with management services 2.20.69, you must accept and save the EULA before using the NetApp Hybrid Cloud Control UI or API to upgrade Element software:
+
. Open the IP address of the management node in a web browser:
+
----
https://<ManagementNodeIP>
----
. Log in to NetApp Hybrid Cloud Control by providing the storage cluster administrator credentials.
. Select *Upgrade* near the top right of the interface.
. The EULA pops up. Scroll down, select *I accept for current and all future updates*, and select *Save*.

.Upgrade options
Choose one of the following Element software upgrade options:

* <<Use NetApp Hybrid Cloud Control UI to upgrade Element storage>>
* <<Use NetApp Hybrid Cloud Control API to upgrade Element storage>>

IMPORTANT: If you are upgrading an H610S series node to Element 12.5 or later and the node is running a version of Element software earlier than 11.8, you will need to perform the additional upgrade steps in this https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure[KB article^] for each storage node. If you are running Element 11.8 or later, the additional upgrade steps are not required.

== Use NetApp Hybrid Cloud Control UI to upgrade Element storage

Using the NetApp Hybrid Cloud Control UI, you can upgrade a storage cluster.

.What you'll need
If your management node is not connected to the internet, you have downloaded the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[NetApp HCI software package for NetApp HCI storage clusters^].

CAUTION: For potential issues while upgrading storage clusters using NetApp Hybrid Cloud Control and their workarounds, see this https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control[KB article^].

.Steps

. Open the IP address of the management node in a web browser:
+
----
https://<ManagementNodeIP>
----
. Log in to NetApp Hybrid Cloud Control by providing the storage cluster administrator credentials.
. Select *Upgrade* near the top right of the interface.
. On the *Upgrades* page, select *Storage*.
+
The *Storage* tab lists the storage clusters that are part of your installation. If a cluster is inaccessible by NetApp Hybrid Cloud Control, it will not be displayed on the *Upgrades* page.
. Choose from the following options and perform the set of steps that are applicable to your cluster:
+
[%header,cols=2*]
|===
|Option
|Steps

|??
a|
. Select *Browse* to upload the upgrade package that you downloaded.
. Wait for the upload to complete. A progress bar shows the status of the upload.

CAUTION: The file upload will be lost if you navigate away from the browser window.

An on-screen message is displayed after the file is successfully uploaded and validated. Validation might take several minutes. If you navigate away from the browser window at this stage, the file upload is preserved.

|You are upgrading an H610S cluster running Element version earlier than 11.8.
a|
. Select the drop-down arrow next to the cluster you are upgrading, and select from the upgrade versions available.
. Select *Begin Upgrade*.
After the upgrade is complete, the UI prompts you to perform additional upgrade steps.
. Complete the additional steps required in the https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure[KB article^], and acknowledge in the UI that you have completed them.

You can download logs after the upgrade is complete. For information about the various upgrade status changes, see <<Upgrade status changes>>.
|===

=== Upgrade status changes

Here are the different states that the *Upgrade Status* column in the UI shows before, during, and after the upgrade process:

[%header,cols=2*]
|===
|Upgrade state
|Description

|Up to Date
|The cluster was upgraded to the latest Element version available.

|Versions Available
|Newer versions of Element and/or storage firmware are available for upgrade.

|In Progress
|The upgrade is in progress. A progress bar shows the upgrade status. On-screen messages also show node-level faults and display the node ID of each node in the cluster as the upgrade progresses. You can monitor the status of each node using the Element UI or the NetApp Element plug-in for vCenter Server UI.

|Upgrade Pausing
|You can choose to pause the upgrade. Depending on the state of the upgrade process, the pause operation can succeed or fail. You will see a UI prompt asking you to confirm the pause operation. To ensure that the cluster is in a safe spot before pausing an upgrade, it can take up to two hours for the upgrade operation to be completely paused. To resume the upgrade, select *Resume*.

|Paused
|You paused the upgrade. Select *Resume* to resume the process.

|Error
|An error has occurred during the upgrade. You can download the error log and send it to NetApp Support. After you resolve the error, you can return to the page, and select *Resume*.  When you resume the upgrade, the progress bar goes backwards for a few minutes while the system runs the health check and checks the current state of the upgrade.

|Unable to Detect
|NetApp Hybrid Cloud Control shows this status instead of *Versions Available* when it does not have external connectivity to reach the online software repository. If you have external connectivity but still see this message, check your link:task_mnode_configure_proxy_server.html[proxy configuration].

|Complete with Follow-up
|Only for H610S nodes upgrading from Element version earlier than 11.8. After phase 1 of the upgrade process is complete, this state prompts you to perform additional upgrade steps (see the https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure[KB article^]). After you complete these additional steps and acknowledge that you have completed it, the status changes to *Up to Date*.
|===

== Use NetApp Hybrid Cloud Control API to upgrade Element storage

You can use APIs to upgrade storage nodes in a cluster to the latest Element software version. You can use an automation tool of your choice to run the APIs. The API workflow documented here uses the REST API UI available on the management node as an example.

.Steps

. Download the storage upgrade package to a device that is accessible to the management node; go to the NetApp HCI software https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[downloads page^] and download the latest storage node image.

. Upload the storage upgrade package to the management node:
.. Open the management node REST API UI on the management node:
+
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the authorization window.
.. From the REST API UI, select *POST /packages*.
.. Select *Try it out*.
.. Select *Browse* and select the upgrade package.
.. Select *Execute* to initiate the upload.
.. From the response, copy and save the package ID (`"id"`) for use in a later step.
. Verify the status of the upload.
.. From the REST API UI, select *GET​ /packages​/{id}​/status*.
.. Select *Try it out*.
.. Enter the package ID you copied in the previous step in *id*.
.. Select *Execute* to initiate the status request.
+
The response indicates `state` as `SUCCESS` when complete.

. Locate the storage cluster ID:
.. Open the management node REST API UI on the management node:
+
----
https://<ManagementNodeIP>/inventory/1/
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the authorization window.
.. From the REST API UI, select *GET /installations*.
.. Select *Try it out*.
.. Select *Execute*.
.. From the response, copy the installation asset ID (`"id"`).
.. From the REST API UI, select *GET /installations/{id}*.
.. Select *Try it out*.
.. Paste the installation asset ID into the *id* field.
.. Select *Execute*.
.. From the response, copy and save the storage cluster ID (`"id"`) of the cluster you intend to upgrade for use in a later step.
. Run the storage upgrade:
.. Open the storage REST API UI on the management node:
+
----
https://<ManagementNodeIP>/storage/1/
----
.. Select *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Select *Authorize* to begin a session.
... Close the authorization window.
.. Select *POST /upgrades*.
.. Select *Try it out*.
.. Enter the upgrade package ID in the parameter field.
.. Enter the storage cluster ID in the parameter field.
+
The payload should look similar to the following example:
+
----
{
  "config": {},
  "packageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4",
  "storageId": "884f14a4-5a2a-11e9-9088-6c0b84e211c4"
}
----
.. Select *Execute* to initiate the upgrade.
+
The response should indicate the state as `initializing`:
+
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055`-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  "state": "initializing",
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copy the upgrade ID (`"upgradeId"`) that is part of the response.
. Verify the upgrade progress and results:
.. Select *GET ​/upgrades/{upgradeId}*.
.. Select *Try it out*.
.. Enter the upgrade ID from the previous step in *upgradeId*.
.. Select *Execute*.
.. Do one of the following if there are problems or special requirements during the upgrade:
+
[%header,cols=2*]
|===
|Option
|Steps

|You need to correct cluster health issues due to `failedHealthChecks` message in the response body.
a|
. Go to the specific KB article listed for each issue or perform the specified remedy.
. If a KB is specified, complete the process described in the relevant KB article.
. After you have resolved cluster issues, reauthenticate if needed and select *PUT ​/upgrades/{upgradeId}*.
. Select *Try it out*.
. Enter the upgrade ID from the previous step in *upgradeId*.
. Enter `"action":"resume"` in the request body.
+
----
{
  "action": "resume"
}
----
. Select *Execute*.

|You need to pause the upgrade because the maintenance window is closing or for another reason.
a|
. Reauthenticate if needed and select *PUT ​/upgrades/{upgradeId}*.
. Select *Try it out*.
. Enter the upgrade ID from the previous step in *upgradeId*.
. Enter `"action":"pause"` in the request body.
+
----
{
  "action": "pause"
}
----
. Select *Execute*.

|If you are upgrading an H610S cluster running an Element version earlier than 11.8, you see the state `finishedNeedsAck` in the response body. You must perform additional upgrade steps for each H610S storage node.
a|
. Complete the additional upgrade steps in this https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure[KB article^] for each node.
. Reauthenticate if needed and select *PUT ​/upgrades/{upgradeId}*.
. Select *Try it out*.
. Enter the upgrade ID from the previous step in *upgradeId*.
. Enter `"action":"acknowledge"` in the request body.
+
----
{
  "action": "acknowledge"
}
----
. Select *Execute*.
|===
.. Run the *GET ​/upgrades/{upgradeId}* API multiple times, as needed, until the process is complete.
+
During the upgrade, the `status` indicates `running` if no errors are encountered. As each node is upgraded, the `step` value changes to `NodeFinished`.
+
The upgrade has finished successfully when the `percent` value is `100` and the `state` indicates `finished`.

== What happens if an upgrade fails using NetApp Hybrid Cloud Control
If a drive or node fails during an upgrade, the Element UI will show cluster faults. The upgrade process does not proceed to the next node, and waits for the cluster faults to resolve. The progress bar in the UI shows that the upgrade is waiting for the cluster faults to resolve. At this stage, selecting *Pause* in the UI will not work, because the upgrade waits for the cluster to be healthy. You will need to engage NetApp Support to assist with the failure investigation.

NetApp Hybrid Cloud Control has a pre-set three-hour waiting period, during which one of the following scenarios can happen:

* The cluster faults get resolved within the three-hour window, and upgrade resumes. You do not need to take any action in this scenario.
* The problem persists after three hours, and the upgrade status shows *Error* with a red banner. You can resume the upgrade by selecting *Resume* after the problem is resolved.
* NetApp Support has determined that the upgrade needs to be temporarily aborted to take corrective action before the three-hour window. Support will use the API to abort the upgrade.

CAUTION: Aborting the cluster upgrade while a node is being updated might result in the drives being ungracefully removed from the node. If the drives are ungracefully removed, adding the drives back during an upgrade will require manual intervention by NetApp Support. The node might be taking longer to do firmware updates or post update syncing activities. If the upgrade progress seems stalled, contact NetApp Support for assistance.


[discrete]
== Find more information

* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources Page^]
