---
sidebar: docs_sidebar
permalink: docs/task_hcc_view_vol_access_group.html
summary: Learn how to view details of volume access groups.
keywords: netapp, hci, on premise, cluster, element
---

= View details of a volume access group

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can edit the properties of an existing NetApp HCI volume access group using NetApp Hybrid Cloud Control.

.What you'll need

* You have administrator credentials for this NetApp HCI system.
* You are running management node 12.2 or later.
* You have upgraded your management services to at least version 2.15.28. NetApp Hybrid Cloud Control storage management is not available in earlier service bundle versions.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to edit.
. In the options menu, select *Details*.
+
The *Volume Access Group Details* dialog appears.

[discrete]
== Find more information
* http://docs.netapp.com/sfe-122/topic/com.netapp.doc.sfe-ug/GUID-EBCB1031-1B2D-472C-92E3-E0CB52B4156C.html[Working with volume access groups and initiators^]
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
