---
sidebar: sidebar
permalink: docs/task_nde_configure_credentials.html
summary: Learn how to configure VMware vSphere during NetApp HCI deployment.
keywords: netapp, hci, netapp deployment engine, deployment, vsphere
---

= Configuring NetApp HCI credentials
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere, vcenter, credentials, user accounts, administrator

[.lead]
During deployment, you define a set of credentials to be used across the newly deployed VMware vSphere environment, the NetApp HCI compute and storage resources, and the management node. If you are deploying NetApp HCI into an existing vSphere environment, these credentials are not applied to the existing vCenter Server.

.About this task
Remember the following points about the credentials you set in the NetApp HCI Deployment Engine:

* *NetApp Hybrid Cloud Control (HCC) or Element UI*: To log in to NetApp HCC or the Element user interface upon successful deployment, use the user name and password specified in this deployment step.
* *VMware vCenter*: To log in to vCenter (if installed as part of deployment), use user name with the suffix `@vsphere.local` or the built-in `Administrator@vsphere.local` user account, and the password specified in this deployment step.
* *VMware ESXi*: To log in to ESXi on the compute nodes, use the user name `root` and the same password specified in this deployment step.

For interaction with VMware vCenter instances, NetApp Hybrid Cloud Control will use one of the following:

* The built-in `Administrator@vsphere.local` user account on the vCenter instance that was installed as part of the deployment.
* The vCenter credentials that were used to connect the NetApp HCI deployment to an existing VMware vCenter Server.

.Steps
. On the *Credentials* page, enter a user name in the *User Name* field.
. Enter a password in the *Password* field. The password must conform to the password criteria visible in the *Password must contain* box.
. Confirm the password in the *Re-enter Password* field.
. Click *Continue*.

[discrete]
== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software[Firmware and driver versions in NetApp HCI and NetApp Element software^]
* To update vCenter and ESXi credentials later, see link:task_hci_credentials_vcenter_esxi.html[Update vCenter or ESXi credentials].
