---
sidebar: sidebar
permalink: docs/task_nde_configure_net_settings.html
summary: Learn how to configure NetApp HCI deployment network settings.
keywords: netapp, hci, deployment, compatibility, nodes
---

= Configure network settings
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
NetApp HCI provides a network settings page with several sections to simplify network configuration. You can proceed through each section and enter information or assign IP addresses for hosts and nodes in each network.

.What you'll need
* You have obtained the following information:
** The planned naming prefix for the hosts and storage cluster
** All planned subnet mask, starting IP address, default gateway, and VLAN IDs for the management, iSCSI, and vMotion networks
** The subnet mask, IP address, default gateway, and VLAN IDs for any planned VMware vCenter deployment
** The Network Time Protocol (NTP) server address for NetApp HCI
** The DNS server IP address information for NetApp HCI
* If you are deploying a vSphere Distributed Switch, you have a vSphere Enterprise Plus license ready to apply after deployment is complete.
* If you assigned VLAN IDs to node ports during terminal user interface (TUI) configuration, you have configured those ports with the same VLAN ID during network configuration. You do not need to configure tagged host ports as access ports or native VLANs on the connected switch ports.
* You have verified that your network switch configuration is correct. Incorrect switch configurations (such as incorrect VLANs or MTU size) will cause deployment errors.

.About this task
If you selected the two-cable network topology for compute nodes, you need to use VLAN IDs for the vMotion and storage networks for all compute and storage nodes in the deployment (VLAN IDs are optional for the management networks). Note that NetApp HCI validates the IP addresses you enter during these steps, but you can disable this validation with the *Live network validation is* button. NetApp HCI also performs checks on other information that you enter during these steps, such as ensuring that no subnets overlap, ensuring that no VLAN IDs are assigned to multiple networks, and other basic validations.

NOTE: In environments that require host-side VLAN tagging before deployment, if you have configured VLAN IDs on compute and storage nodes so they are discoverable by the NetApp Deployment Engine, ensure you use the correct VLANs when configuring network settings in the NetApp Deployment Engine.

If you are deploying a two-node or three-node storage cluster, you can complete IP address information for Witness Nodes on the *Network Settings* page.

NOTE: In the IP address assignment pages, information you enter in the *Automatically assign IP addresses* mode does not affect information entered in the *Manually assign IP addresses* mode, and vice versa. If you enter IP addresses in both modes, NetApp HCI uses the IP address information in whatever mode is active when you click *Continue* at the bottom of the page.

.Troubleshooting common problems
NetApp HCI performs checks on the information you enter on these pages. Here are some common problems and workarounds:

|===
|Problem |Workaround

|In automatic IP address assignment mode, after you enter a starting IP address, you see the message `IPs in the range are in use:` with a scrollable drop-down list of the in-use IP addresses.
|NetApp HCI has assigned a contiguous range of IP addresses, but one or more of those IP addresses is already in use. Free the in-use IP addresses and try again, or use manual IP address assignment mode to assign specific IP addresses.

|After entering a default gateway, you see the message `The gateway is not valid`.
a|The default gateway IP address either does not match the subnet you provided, or there is an issue with the network or server you need to resolve. See the following NetApp Knowledge Base articles for more information:

* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Troubleshoot_Invalid_Gateway_in_NDE[Troubleshoot an invalid gateway in the NetApp Deployment Engine^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/%22The_gateway_is_not_valid%22_during_NDE[The gateway is not valid in the NetApp Deployment Engine^]

|You complete several *Network Settings* configuration pages and realize that there is incorrect information on one of the previous pages in the sequence.
|Using the numbered page sequence at the top of the page, you can select a page that you have previously completed and change information there. When finished, you can click *Continue* on the completed pages to return to the current page.
|===

== Configure DNS and NTP settings

.Steps

.  On the *DNS/NTP* page, enter the DNS and NTP server information for NetApp HCI in the following fields:
+
|===
|Field |Description

|*DNS Server IP Address 1*
|The IP address of the primary DNS server for NetApp HCI. If you specified a DNS server on the vCenter Configuration page, this field is populated and read-only.

|*DNS Server IP Address 2 (Optional)*
|An optional IP address of a secondary DNS server for NetApp HCI.

|*NTP Server Address 1*
|The IP address or fully qualified domain name of the primary NTP server for this infrastructure.

|*NTP Server Address 2 (Optional)*
|An optional IP address or fully qualified domain name of the secondary NTP server for this infrastructure.
|===

== Assign VLAN IDs
On the *VLAN IDs* page, you can assign VLAN IDs to NetApp HCI networks. You can also choose to not use VLAN IDs. If you selected the two-cable network topology for compute nodes, you need to use VLAN IDs for the vMotion and storage networks for all compute and storage nodes in the deployment (VLAN IDs are optional for the management networks).

NOTE: When you assign VLAN IDs, you are configuring VLAN tags that NetApp HCI will apply to the network traffic. You do not need to enter your native VLAN as a VLAN ID; to use the native VLAN for a network, leave the appropriate field empty.

.Steps
Choose one of the following options:
|===
|Option |Steps

|Assign VLAN IDs
a|
. Select *Yes* for the *Will you assign VLAN IDs* option.
. In the *VLAN ID* column, enter a VLAN tag to use for each type of network traffic you want to assign to a VLAN.
+
Both compute vMotion traffic and iSCSI traffic must use an unshared VLAN ID.
. Click *Continue*.

|Do not assign VLAN IDs
a|
. Select *No* for the *Will you assign VLAN IDs* option.
. Click *Continue*.
|===

== Configure the management network
On the *Management* page, you can choose to have NetApp HCI automatically populate IP address ranges for the management networks based on a starting IP address, or you can choose to manually enter all IP address information.

.Steps
Choose one of the following options:
|===
|Option |Steps

|Automatically assign IP addresses
a|
. Select the *Automatically assign IP addresses* option.
. In the *Subnet* column, enter a subnet definition in CIDR format for each VLAN.
. In the *Default Gateway* column, enter a default gateway for each VLAN.
. In the *Subnet* column, enter a starting IP address to use for each VLAN and node type.
+
NetApp HCI automatically populates the ending IP addresses for each host or group of hosts.
. Click *Continue*.

|Manually assign IP addresses
a|
. Select the *Manually assign IP addresses* option.
. In the *Subnet* column, enter a subnet definition in CIDR format for each VLAN.
. In the *Default Gateway* column, enter a default gateway for each VLAN.
. In the row for each host or node, enter the IP address for that host or node.
. Enter the Management Virtual IP (MVIP) address for the management network.
. Click *Continue*.
|===

== Configure the vMotion network
On the *vMotion* page, you can choose to have NetApp HCI automatically populate IP address ranges for the vMotion network based on a starting IP address, or you can choose to manually enter all IP address information.

.Steps
Choose one of the following options:
|===
|Option |Steps

|Automatically assign IP addresses
a|
. Select the *Automatically assign IP addresses* option.
. In the *Subnet* column, enter a subnet definition in CIDR format for each VLAN.
. (Optional) In the *Default Gateway* column, enter a default gateway for each VLAN.
. In the *Subnet* column, enter a starting IP address to use for each VLAN and node type.
+
NetApp HCI automatically populates the ending IP addresses for each host or group of hosts.
. Click *Continue*.

|Manually assign IP addresses
a|
. Select the *Manually assign IP addresses* option.
. In the *Subnet* column, enter a subnet definition in CIDR format for each VLAN.
. (Optional) In the *Default Gateway* column, enter a default gateway for each VLAN.
. In the row for each host or node, enter the IP address for that host or node.
. Click *Continue*.
|===

== Configure the iSCSI network
On the *iSCSI* page, you can choose to have NetApp HCI automatically populate IP address ranges for the iSCSI network based on a starting IP address, or you can choose to manually enter all IP address information.

.Steps
Choose one of the following options:
|===
|Option |Steps

|Automatically assign IP addresses
a|
. Select the *Automatically assign IP addresses* option.
. In the *Subnet* column, enter a subnet definition in CIDR format for the iSCSI network.
. (Optional) In the *Default Gateway* column, enter a default gateway for the iSCSI network.
. In the *Subnet* column, enter a starting IP address to use for each node type.
+
NetApp HCI automatically populates the ending IP addresses for each host or group of hosts.
. Click *Continue*.

|Manually assign IP addresses
a|
. Select the *Manually assign IP addresses* option.
. In the *Subnet* column, enter a subnet definition in CIDR format for the iSCSI network.
. (Optional) In the *Default Gateway* column, enter a default gateway for the iSCSI network.
. In the *Management Node* section, enter an IP address for the management node.
. For each node in the *Compute Nodes* section, enter the iSCSI A and iSCSI B IP addresses.
. In the *Storage Virtual IP (SVIP)* row, enter the SVIP IP address for the iSCSI network.
. In the remaining rows, for each host or node, enter the IP address for that host or node.
. Click *Continue*.
|===

== Assign cluster and host names
On the *Naming* page, you can choose to have NetApp HCI automatically populate the cluster name and the names of the nodes in the cluster, based on a naming prefix, or you can choose to manually enter all of the names for the cluster and nodes.

.Steps
Choose one of the following options:
|===
|Option |Steps

|Automatically assign cluster and host names
a|
. Select the *Automatically assign cluster / host names* option.
. In the *Installation Prefix* section, enter a naming prefix to use for all of the node host names in the cluster (including the management node and witness nodes).
+
NetApp HCI automatically populates the host names based on the type of node, as well as suffixes for common node names (such as the compute and storage nodes).
. (Optional) In the *Naming Scheme* column, modify any of the resulting names for the hosts.
. Click *Continue*.

|Manually assign cluster and host names
a|
. Select the *Manually assign cluster / host names* option.
. In the *Host / Cluster Name* column, enter the host name for each host, and a cluster name for the storage cluster.
. Click *Continue*.
|===

== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation^]
