---
sidebar: sidebar
permalink: docs/task_hcc_upgrade_compute_node_drivers.html
summary: As part of a NetApp HCI system upgrade, you upgrade compute node drivers.
keywords: netapp, hci, on premise, cluster, element, compute node
---

= Update compute node drivers

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
For any H-series compute node, you can update the drivers used on the nodes using VMware Update Manager.

.What you'll need

See the firmware and driver matrix for your hardware at https://docs.netapp.com/us-en/hci/docs/firmware_driver_versions.html[Supported firmware and ESXi driver versions^].

.About this task

Perform only one of these update operations at a time.

You should check the current ESXi driver version before you attempt compute firmware upgrades. If the driver is out of date, upgrade the driver first. Then upgrade the compute firmware for your compute nodes.

.Steps

. Browse to the https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[NetApp HCI software downloads^] page and select the download link for correct version of NetApp HCI.
. Select *ESXI_drivers* from the drop-down list.
. Accept the End User License Agreement.
. Download the driver package for your node type and ESXi version.
. Extract the downloaded driver bundle on your local computer.
+
NOTE: The NetApp driver bundle includes one or more VMware Offline Bundle ZIP files; do not extract these ZIP files.

. Go to *VMware Update Manager* in VMware vCenter.

. Import the driver offline bundle file for the compute nodes into the *Patch Repository*.
+
For VMware ESXi 6.x and 7.0 to 7.0 U3,  perform the following steps to import the driver offline bundle file:
+
.. Select the *Updates* tab.
.. Select *UPLOAD FROM FILE*.
.. Browse to the offline bundle that was previously downloaded and select *IMPORT*.
. Create a new host baseline for the compute node.
. Choose *Host Extension* for Name and Type and select all imported driver packages to be included in the new baseline.
. In the *Host and Clusters* menu in vCenter, select the cluster with the compute nodes you would like to update and navigate to the *Update Manager* tab.
. Select *Remediate* and the select the newly created host baseline. Ensure that drivers included in the baseline are selected.
. Proceed through the wizard to the *Host Remediation Options* and ensure that the *Do Not Change VM Power State* option is selected to keep virtual machines online during the driver update.
+
NOTE: If VMware Distributed Resource Scheduler (DRS) is enabled on the cluster (this is the default in NetApp HCI installations), virtual machines will automatically be migrated to other nodes in the cluster.

. Proceed to the *Ready to Complete* page in the wizard and select *Finish*.
+
The drivers for all compute nodes in the cluster are updated one node at a time while virtual machines stay online.

[discrete]
== Find more information

* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/hybrid-cloud/hci-documentation/[NetApp HCI Resources Page^]
