---
sidebar: docs_sidebar
permalink: docs/task_mnode_change_storage_cluster_admin_password.html
summary: You can add compute and controller assets to the management node configuration using the REST API UI.
keywords: netapp, hci, mnode, management node, admin password
---

= Change the storage cluster administrator password

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can update the storage cluster administrator password by using the REST API UI.


.Before you begin
Ensure that you have changed the storage cluster administrator password by using the NetApp Element software UI.


.Steps
. From a browser, log into the management node REST API UI:
.. Go to the storage MVIP and log in.
+
Doing this causes the certificate to be accepted for the next step.

.. Access the REST API UI on the management node by entering the management node IP address followed by `/mnode`:
+
----
https://[IP address]/mnode
----

. Click *Authorize* or any lock icon and complete the following:
+
.. Enter the cluster user name and password.
.. Enter the client ID as `mnode-client`.
.. Click *Authorize* to begin a session.
.. Close the window.
. Run *GET /assets* to find the base asset ID that you will need for the next steps:
.. Click *GET /assets*
.. Click *Try it out*.
.. Click *Execute*.
. Copy the value for `id` for the base asset to your clipboard.
+
NOTE: A base asset and sub-assets were created when you ran the upgrade or setup scripts during management node installation or upgrade or deployed your NetApp HCI using the NetApp Deployment Engine.

. Retrieve the storage asset:
.. Click *GET /assets/{ASSET_ID}/storage-clusters*.
.. Click *Try it out*.
.. Enter the ID from the base asset step in asset_ID.
.. Click *Execute*.
. Update the storage asset:
.. Click *PUT /assets/{ASSET_ID}/storage-clusters/{STORAGE_ID}*.
.. Click *Try it out*.
. Update the required payload values for the storage asset as defined in the *Model* tab:
.. Remove the hostname and SSL certificate lines.
.. Enter the new password on the password line.
+
----
{
"username": "admin",
"password": "admin",
"ip": "10.10.1.124",
"config": {}
}
----
.. Enter the parent base asset ID in the *asset_id* field.
.. Click *Execute*.

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
