---
sidebar: docs_sidebar
permalink: docs/task_getting_a_netapp_kubernetes_service_api_token.html
summary: Enabling cloud services for NetApp HCI requires a NetApp Kubernetes Service API token that is associated with your NetApp Cloud Central account.
keywords: netapp, hci, on premise, cloud services
---

= Get a NetApp Kubernetes Service API token
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Enabling cloud services for NetApp HCI requires a NetApp Kubernetes Service API token that is associated with your NetApp Cloud Central account.

You can complete these steps before enabling cloud services or during the process, when a wizard displays a link to get the API token.

== Steps

. Open a web browser and browse to NetApp Cloud Central for NetApp Kubernetes Service. https://nks.netapp.io
. Log in by providing the NetApp HCI storage cluster administrator credentials.
+
If you do not have an account, click *Sign Up* and provide the account information.
. Click *Go to Cloud Data Services* and select *NetApp HCI*.
. Click the user icon at the top right of the screen and select *Edit Profile*.
. In the API Tokens section, click *Add Token*, enter a token name, and click *Create*.
. Copy the token and save it in a file so that you can later paste it when needed.



[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
* https://nks.netapp.io[NetApp Kubernetes Service^]
* https://docs.netapp.com/us-en/kubernetes-service/[NetApp Kubernetes Service Documentation^]
