---
sidebar: docs_sidebar
permalink: docs/task_mnode_enable_alerts.html
summary: You can configure settings to monitor alerts on your NetApp HCI system.
keywords: netapp, element, management node, mnode, ui, alerts, alert monitoring
---

= Configure alert monitoring on NetApp HCI

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can configure settings to monitor alerts on your NetApp HCI system.

NetApp HCI alert monitoring forwards NetApp HCI storage cluster system alerts to vCenter Server, enabling you to view all alerts for NetApp HCI from the vSphere Web Client interface.

NOTE: These tools are not configured or used for storage-only clusters, such as SolidFire all-flash storage. Running the tools for these clusters results in the following 405 error, which is expected given the configuration: webUIParseError : Invalid response from server. 405

. Open the per-node management node UI.
. Click the *Alert Monitor* tab.
. Configure the alert monitoring options.

[discrete]
== Find more Information

* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
