---
sidebar: sidebar
permalink: docs/task_nde_review_deploy.html
summary: Learn how to review your final configuration and deploy NetApp HCI with these settings.
keywords: netapp, hci, deployment, review, deploy
---

= Review and deploy the configuration
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can review the information you provided before beginning deployment. You can also correct any incorrect or incomplete information before you proceed.

NOTE: During deployment, the management node installation process creates volumes with names beginning with `NetApp-HCI-` in the Element storage cluster, and a SolidFire account beginning with the name `tenant_`. Do not delete these volumes or accounts; doing so will cause a loss in management functionality.

.Steps
. Optional: Select the *Download* icon to download installation information in CSV format. You can save this file and refer to it later for configuration information.
+
NOTE: You can import the CSV file as an installation profile on the *Installation Profile* page of the NetApp Deployment Engine (NDE) if needed during a future installation.

. Expand each section and review the information. To expand all sections at once, select *Expand All*.
. Optional: To make changes to information in any displayed section:
.. Select *Edit* in the corresponding section.
.. Make the necessary changes.
.. Select *Continue* until you reach the *Review* page. Your previous settings are saved on each page.
.. Repeat steps 2 and 3 to make any other necessary changes.
. If you do not want to send cluster statistics and support information to NetApp-hosted SolidFire Active IQ servers, clear the final checkbox.
+
This disables real-time health and diagnostic monitoring for NetApp HCI. Disabling this feature removes the ability for NetApp to proactively support and monitor NetApp HCI to detect and resolve problems before production is affected.
. If all information is correct, select *Start Deployment*.
+
A dialog box appears. In the event of network connectivity issues or power loss during the final setup process, or if your browser session is lost, you can copy the URL displayed in the dialog and use it to browse to the final setup progress page.

. Review the information in the dialog and select *Copy to Clipboard* to copy the URL to your clipboard.
. Save the URL to a text file on your computer.
. When you are ready to proceed with deployment, select *OK*.
+
Deployment begins and a progress page is displayed. Do not close the browser window or navigate away from the progress page until deployment is complete. If your browser session is lost for any reason, you can browse to the URL you copied earlier (and accept any security warnings that appear) to regain access to the final setup progress page.
+
NOTE: If the deployment fails, save any error message text and contact NetApp Support.

+
After deployment is complete, the compute nodes might reboot more than once before becoming ready for service.

.After you finish
Begin using NetApp HCI by selecting *Launch vSphere*.

[NOTE]
====
* For NetApp HCI installations using vSphere 6.7, this link launches the HTML5 vSphere web interface. For installations using vSphere 6.5, this link launches the Adobe Flash vSphere web interface.

* In two storage or three storage node configurations, the NDE configures the Witness Nodes to use the local datastore on the compute nodes. As a result, your vSphere Client displays two *Datastore usage on disk* warnings. To continue, select the *Reset To Green* link in each warning.
====

== Find more information
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
* https://docs.netapp.com/us-en/element-software/index.html[SolidFire and Element Software Documentation^]
