---
sidebar: docs_sidebar
permalink: docs/task_hcc_upgrade_all.html
summary: You can upgrade NetApp HCI and all of its components.
keywords: netapp, hci, on premise, cluster, upgrade, element
---

= Upgrade your entire NetApp HCI installation for version 1.8

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can keep the entire NetApp HCI installation up-to-date after deployment by sequentially upgrading all NetApp HCI software components.

These components include management services, NetApp Hybrid Cloud Control (HCC), Element software, management node, compute firmware, compute drivers, and the Element Plug-in for vCenter Server.

.What you'll need

* You are running management node 11.3 or later.
+
TIP: To check the version of your management node, log in to your management node and view the Element version number in the login banner.

* You have upgraded your management services to at least version 2.1.326.
+
Upgrades using HCC are not available in earlier service bundle versions.


.Steps

. link:task_hcc_upgrade_management_services.html[Update management services from Hybrid Cloud Control].
+
IMPORTANT: You must upgrade to the latest management services bundle before upgrading your
Element software to version 12.

. link:task_hcc_upgrade_element_prechecks.html[Run Element storage health checks prior to upgrading storage].
. link:task_hcc_upgrade_element_software.html[Upgrade your Element software version].
. link:task_hcc_upgrade_management_node.html[Upgrade your management node].
. link:task_hcc_upgrade_compute_node_firmware.html[Update your compute node firmware].
. link:task_hcc_upgrade_compute_node_drivers.html[Update your compute node drivers].



[discrete]
== Find more information

* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
