---
sidebar: docs_sidebar
permalink: docs/task_mnode_add_assets.html
summary: You can add compute and controller assets to the management node configuration using the REST API UI.
keywords: netapp, mnode, management node, rest api, hci
---

= Add an asset to the management node

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can add compute and controller assets to the management node configuration using the REST API UI.

You might need to add an asset if you recently scaled your installation and new assets were not added automatically to your configuration. Use these APIs to add assets that are recent additions to your installation.

.What you'll need
* Your cluster version is running NetApp Element software 11.3 or later.
* You have deployed a management node running version 11.3 or later.

.About this task
(NetApp HCI only) If you do not see compute nodes in Hybrid Cloud Control (HCC) after scaling your NetApp HCI system, you can add a compute node using the `POST /assets/{asset_id}/compute-nodes` described in this procedure.

.Steps
. Open the inventory service REST API UI on the management node:
+
----
https://[management node IP]/inventory/1
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the window.
.. From the REST API UI, click *GET ​/installations*.
.. Click *Try it out*.
.. Click *Execute*.
.. From the code 200 response body, copy the `id` for the installation.
.. From the REST API UI, click *GET ​/installations​/{id}*.
.. Click *Try it out*.
.. Enter the installation ID.
.. Click *Execute*.
.. From the code 200 response body, copy the base ID (`id`) for the cluster:
+
Your installation has a base asset configuration that was created during installation or upgrade.
+
----
},
  "id": "abcd01e2-ab00-4xxx-12ee-12x111aa1a0a",
  "management": {
    "errors": [],
    "inventory": {
      "authoritativeClusterMvip": "10.111.111.111",
      "bundleVersion": "2.14.19",
      "managementIp": "10.111.111.111",
      "version": "1.4.12"
    }
  },
----
. To add a compute node or controller sub-asset to an existing base asset, click one of the following.
+
Your installation has a base asset configuration that was created during installation or upgrade.
+
[cols=2*,options="header",cols="40,60"]
|===
| Option
| Description
| POST /assets/{asset_id}/controllers
a| . Open the mNode service REST API UI on the management node:
+
----
https://[management node IP]/mnode
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the window.
. Click *POST /assets/{asset_id}/controllers*.
. Click *Try it out*.
. Enter the parent base asset ID in the *asset_id* field.
. Click *Execute*.
| POST /assets/{asset_id}/compute-nodes
a| . Open the mNode service REST API UI on the management node:
+
----
https://[management node IP]/mnode
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the window.
. Click *POST /assets/{asset_id}/controllers*.
. Click *Try it out*.
. Enter the management IP for the node in the `ip` field.
. For `hardwareTag`, enter the BIOS UUID of the hardware.  Use the Redfish API to find the value under the `UUID` property name:
* Type A: `https://<bmc ip>/redfish/v1/Systems/1`
* Type B: `https://<bmc ip>/redfish/v1/Systems/Self`
+
NOTE: If the BIOS UUID is not available, the chassis serial number can be used instead.

. Enter the parent base asset ID you copied in an earlier step in the *asset_id* field.
. Click *Execute*.
|===

[discrete]
== Find more information
* https://docs.netapp.com/hci/index.jsp[NetApp HCI Documentation Center^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
