---
sidebar: docs_sidebar
permalink: docs/task_logging_in.html
summary: You can log in to NetApp HCI from any web browser that has a connection to the NetApp HCI system.
keywords: netapp, hci, on premise, cloud services
---

= Logging in to NetApp Cloud Data Services for NetApp HCI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can log in to NetApp Cloud Data Services to access the NetApp HCI service from any web browser that has a connection to the NetApp HCI system. You should log in using a NetApp Cloud Central user account.

== Steps

. Open a web browser and log in to https://cloud.netapp.com[NetApp Cloud Central^].
. Click *Go to Cloud Data Services* and select *NetApp HCI*.
+TIP: If you do not see any systems listed, make sure that the NetApp HCI administrator is added to your NetApp Cloud Central account.



*	nnn
*	mmm
*	nnn
*	nnn
*	abc
*	nnn

== What happens behind the scenes?

Behind the scenes, NetApp HCI creates a bootstrap agent that establishes the initial communication tunnel to the NetApp Kubernetes Service Controller, builds a temporary bootstrap cluster, and creates a service cluster. The service cluster, connected to NetApp Kubernetes Service, acts as a service orchestrator to deploy services and update itself.

The NetApp Kubernetes Service agent maintains the tunnel, creates user clusters, and maintains previously deployed services.




[discrete]
== Top Links
* link:task_deploying_overview.html[Deploying cloud services on NetApp HCI overview]
* link:concept_architecture_cloudinsights.html[Real-time analytics with NetApp Cloud Insights]


[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation]
* https://docs.netapp.com/us-en/hybridcloudsolutions/[Hybrid Cloud Solutions documentation^]
* https://docs.netapp.com/us-en/cloudinsights/[Cloud Insights documentation^]
