---
sidebar: docs_sidebar
permalink: docs/task_nde_configure_credentials.html
summary: Learn how to configure VMware vSphere during NetApp HCI deployment.
keywords: netapp, hci, netapp deployment engine, deployment, vsphere
---

= Configure credentials
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: netapp, hci, netapp deployment engine, deployment, vsphere

[.lead]
During deployment, you define a common set of credentials to be used for the newly deployed VMware vSphere environment, the NetApp HCI compute and storage resources, and the management node. If you are joining an existing vSphere environment, these credentials are not applied to the existing vCenter Server.

.About this task
Remember the following points about the credentials you set in the NetApp HCI Deployment Engine:

* To log in to a vSphere environment installed as part of deployment, use the same user name that you enter on this page with the following suffix:
----
@vsphere.local
----
* To log in to ESXi after deployment, use root as the user name and the same password you enter on this page.

.Steps
. On the *Credentials* page, enter a user name in the *User Name* field.
. Enter a password in the *Password* field. The password must conform to the password criteria visible in the *Password must contain* box.
. Confirm the password in the *Re-enter Password* field.
. Click *Continue*.

[discrete]
== Find more information
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Firmware_and_driver_versions_in_NetApp_HCI_and_NetApp_Element_software[Firmware and driver versions in NetApp HCI and NetApp Element software^]
