---
sidebar: docs_sidebar
permalink: docs/task_hcc_manage_initiators.html
summary: Learn how to add create and manage initiators that enable communication between external clients and Element storage volumes.
keywords: netapp, hci, initiator, storage, element, access group
---

= Create and manage initiators

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can use link:concept_hci_initiators.html[initiators] for CHAP-based rather than account-based access to volumes. You can create and delete initiators, and give them friendly aliases to simplify administration and volume access. When you add an initiator to a volume access group, that initiator enables access to all volumes in the group.

.What you'll need

* You have administrator credentials for this NetApp HCI system.
* You are running management node 12.2 or later.
* You have upgraded your management services to at least version 2.17.xx. NetApp Hybrid Cloud Control initiator management is not available in earlier service bundle versions.

.Options
* <<Create an initiator>>

== Create an initiator
You can add a volume access group to a storage cluster by using NetApp Hybrid Cloud Control.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Initiators* tab.
. Select the *Create Initiator* button.
. To create a single initiator:
.. Select Create a Single Initiator.
.. Enter the IQN or WWPN for the initiator in the IQN/WWPN field.
* The accepted format of an initiator IQN is iqn.yyyy-mm where y and m are digits followed by text which must only contain digits, lower-case alphabetic characters, a period (`.`), colon (`:`) or dash (`-`).
A sample of the format is as follows:
`iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b`
* The accepted format of a Fibre Channel initiator WWPN is `:Aa:bB:CC:dd:11:22:33:44` or `AabBCCdd11223344`.
A sample of the format is as follows:
`5f:47:ac:c0:5c:74:d4:02`
.. Enter a friendly name for the initiator in the Alias field.
. To create multiple initiators:
.. Select Create Multiple Initiators.
.. Do one of the following:
* Click Scan Hosts to scan vSphere hosts for initiator values not defined in the NetApp Element cluster.
* Enter a list of IQNs or WWPNs in the text box, and click Add Initiators.
.. (Optional) Under the Alias heading, click the field for each entry to add an alias.
.. (Optional) Remove an initiator from the list, as required.
. Select *Create Initiator*.

== Edit a volume access group
You can edit the properties of an existing volume access group by using NetApp Hybrid Cloud Control.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to edit.
. In the options menu, select *Edit*.
+
The *Edit Access Group* dialog appears.
. Make any needed changes to the name, associated initiators, or associated volumes.
. Confirm your changes by selecting *Save*.
. In the *Access Groups* table, verify that the access group reflects your changes.

== Delete a volume access group
You can remove a volume access group by using NetApp Hybrid Cloud Control, and at the same time remove the initiators associated with this access group from the system.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to delete.
. In the options menu, select *Delete*.
+
The *Delete Access Group* dialog appears.
. If you do not wish to delete the initiators that are associated with the access group, deselect the *Delete initiators in this access group* checkbox.
. Confirm the delete operation by selecting *Yes*.

////
== View details of a volume access group
You can view the details of an existing NetApp HCI volume access group, such as attached volumes and initiators, using NetApp Hybrid Cloud Control.

.Steps

. Log in to NetApp Hybrid Cloud Control by providing the NetApp HCI or Element storage cluster administrator credentials.
. From the Dashboard, expand the name of your storage cluster on the left navigation menu.
. Select *Volumes*.
. Select the *Access Groups* tab.
. In the *Actions* column of the table of access groups, expand the options menu for the access group you need to edit.
. In the options menu, select *Details*.
+
The *Volume Access Group Details* dialog appears.
////

[discrete]
== Find more information
* link:concept_hci_initiators.html[Learn about initiators]
* link:concept_hci_volume_access_groups.html[Learn about volume access groups]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
