---
sidebar: docs_sidebar
permalink: docs/task_mnode_ssh_management.html
summary: You can enable, disable, or determine the status of SSH support connection capability on the management node using the REST API UI.
keywords: netapp, mnode, management node, rest api, hci
---

= Manage SSH support functionality on the management node

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
You can enable, disable, or determine the status of the SSH support connection capability on the management node (mNode) using the REST API. By default, SSH capability is enabled until you disable it.

.Before you begin
* *Authoritative cluster administrator permissions*: You have permissions as administrator on the link:concept_hci_clusters.html#authoritative-storage-clusters[authoritative storage cluster].
* *Element software*: Your cluster is running NetApp Element software 11.3 or later.
* *Management node*: You have deployed a management node running version 11.3 or later.
* *Management services updates*: You have updated your https://mysupport.netapp.com/products/p/mgmtservices.html[management services bundle] to the version 2.17.

.Options
You can do any of the following tasks after you link:task_mnode_api_get_authorizationtouse.html[authenticate].
* <<Disable the SSH support capability on the management node>>
* <<Enable the SSH support capability on the management node>>
* <<Determine status of the SSH support capability on the management node>>

== Disable the SSH support capability on the management node
You can edit the stored user name or password for any of the existing vCenter controllers registered with the management node. You cannot edit the stored IP address of an existing vCenter controller.

.Steps
. Click *PUT /compute/controllers/{controller_id}*.
. Enter the controller ID of a vCenter controller in the `controller_id` parameter.
. Click *Try it out*.
. Change either of the following parameters in the *Request body* field:
+
|===
|Parameter |Type |Description

|`userId`
|string
|Change the user ID used to communicate with the vCenter controller (the user must have administrator privileges).

|`password`
|string
|Change the password used to communicate with the vCenter controller.
|===
. Click *Execute*.
+
The API returns updated controller information.

== Enable the SSH support capability on the management node
You can edit the stored user name or password for any of the existing vCenter controllers registered with the management node. You cannot edit the stored IP address of an existing vCenter controller.

.Steps
. Click *PUT /compute/controllers/{controller_id}*.
. Enter the controller ID of a vCenter controller in the `controller_id` parameter.
. Click *Try it out*.
. Change either of the following parameters in the *Request body* field:
+
|===
|Parameter |Type |Description

|`userId`
|string
|Change the user ID used to communicate with the vCenter controller (the user must have administrator privileges).

|`password`
|string
|Change the password used to communicate with the vCenter controller.
|===
. Click *Execute*.
+
The API returns updated controller information.

== Determine status of the SSH support capability on the management node
You can list existing vCenter controllers that are registered with the management node and view stored information about them using the REST API.

.Steps
. Click *GET /compute/controllers*.
. Click *Try it out*.
. Click *Execute*.
+
The API returns a list of all known vCenter controllers, along with the IP address, controller ID, hostname, and user ID used to communicate with each controller.
. If you want the connection status of a particular controller, copy the controller ID from the `id` field of that controller to your clipboard and see <<View the status of an existing controller>>.

[discrete]
== Find more information
* link:task_mnode_add_assets.html[Add an asset to the management node]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
