---
sidebar: docs_sidebar
permalink: docs/task_cv_managing.html
summary: You can create cloud volumes with Cloud Volumes on NetApp HCI.
keywords: netapp, hci, on premise, cloud services, cloud volumes,
---

= Managing data with Cloud Volumes on NetApp HCI overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Using Fabric Orchestrator, you can create and manage cloud volumes anywhere using a single interface, whether you need them to reside on a private cloud or many public clouds.

NOTE: Fabric Orchestrator is in Preview mode. When you enable Cloud Volumes on NetApp HCI, you automatically have access to the Preview environment.

== Prerequisites
Before you use Cloud Volumes on NetApp HCI, you must enable the service using the NetApp Hybrid Cloud Control.
See information on link:task_deploying_overview.html[deploying cloud services on NetApp HCI].

== Workflow overview
To create and manage cloud volumes using Fabric Orchestrator, do the following:
* link:task_fo_accessing.html[Access Fabric Orchestrator] on NetApp Cloud Central.
* link:task_dfo_creating_cloud_volumes.html[Create Cloud Volumes on NetApp HCI] using Fabric Orchestrator.

[discrete]
== Find more information
* https://cloud.netapp.com/home[NetApp Cloud Central^]
* https://docs.netapp.com/us-en/cloud/[NetApp Cloud Documentation^]
