---
sidebar: sidebar
permalink: docs/task_rancher_createcluster.html
summary: After Rancher deployment, you can create Kubernetes user clusters using the Rancher UI.
keywords: netapp, hci, rancher, kubernetes clusters, create cluster
---

= Create user clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
After Rancher deployment, you can create Kubernetes user clusters using the Rancher UI. You can either create clusters that are hosted by various Kubernetes providers (for example, Google Kubernetes Engine) or the Rancher Kubernetes Engine (RKE), which is Rancher's Kubernetes installer.

TIP: For more information about requirements for creating clusters, see the https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/[Rancher documentation^].

.What you'll need

* You have installed Rancher on NetApp HCI.
* You have the necessary static IP addresses. Each user cluster requires three static IP addresses.
* You have familiarized yourself with the requirements listed in the https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/[Rancher documentation^].

.Steps

. In NetApp Hybrid Cloud Control, select the URL provided to you at the end of the Rancher deployment.
. In the Rancher UI, create the user cluster.

[discrete]
== Find more information
* https://rancher.com/docs/rancher/v2.x/en/overview/architecture/[Rancher documentation about architecture^]
* https://rancher.com/docs/rancher/v2.x/en/overview/concepts/[Kubernetes terminology for Rancher^]
* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://www.netapp.com/us/documentation/hci.aspx[NetApp HCI Resources page^]
