---
sidebar: docs_sidebar
permalink: docs/task_rancher_upgrades.html
summary: You can use NetApp Hybrid Cloud Control to upgrade components of your Rancher deployment that you installed previously using HCC.
keywords: netapp, hci, rancher, upgrade, hcc
---

= Upgrade Rancher on NetApp HCI

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
To upgrade Rancher software, you can use the NetApp Hybrid Cloud Control (HCC) UI or REST API. HCC provides an easy button process to upgrade the components of your Rancher deployment, including Rancher server, Rancher Kubernetes Engine (RKE), and the management cluster's node OS (for security updates). You can alternatively use the API to help automate upgrades.

Upgrades are available by component instead of a cumulative package. As such, some component upgrades such as the Ubuntu OS come available on a more rapid cadence. Upgrades affect only your Rancher server instance and the management cluster that Rancher Server is deployed on. Upgrades to the management cluster node's Ubuntu OS are for critical security patches only and do not upgrade the operating system. User clusters cannot be upgraded from NetApp Hybrid Cloud Control.

.What you'll need

* *Admin privileges*: You have storage cluster administrator permissions to perform the upgrade.
* *Management node*: For NetApp Hybrid Cloud Control UI and API, the management node in your environment is running version 11.3.
* *Management services*: You have updated your management services bundle to the latest version.

IMPORTANT: You must upgrade to the latest management services bundle 2.17.xx or later for Rancher functionality.

* *System ports*: If you are using NetApp Hybrid Cloud Control for upgrades, you have ensured that the necessary ports are open. See link:hci_prereqs_required_network_ports.html[Network ports] for more information.
* *Backup your VM*: It is highly recommended that you create snapshots of your Rancher cluster VMs at a known good state before attempting upgrades.

.Upgrade options

Choose one of the following upgrade processes:

* <<Use NetApp Hybrid Cloud Control UI to upgrade a Rancher deployment>>
* <<Use NetApp Hybrid Cloud Control API to upgrade a Rancher deployment>>

== Use NetApp Hybrid Cloud Control UI to upgrade a Rancher deployment

Using the NetApp Hybrid Cloud Control UI, you can upgrade any of these components in your Rancher deployment:

* Rancher server
* Rancher Kubernetes Engine (RKE)
* Node OS security updates

.What you'll need
* If your management node is not connected to the internet, you have downloaded the package from the relevant location:
** https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab[Storage firmware package for NetApp HCI storage clusters^]??Rancher??

CAUTION: For potential issues during upgrade using NetApp Hybrid Cloud Control, see the https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control[KB article^].

TIP: The upgrade process takes approximately xx minutes per component.

.Steps

. Open a web browser and browse to the IP address of the management node:
+
----
https://<ManagementNodeIP>
----
. Log in to NetApp Hybrid Cloud Control by providing the storage cluster administrator credentials.
. Click *Upgrade* near the top right of the interface.
. On the *Upgrades* page, select *Rancher*.
. Select the *Actions* menu for the software you want to upgrade.

* Rancher server
* Rancher Kubernetes Engine (RKE)
* Node OS security updates

. Select *Upgrade* for Rancher server or RKE upgrades or *Apply Upgrade* for Node OS security updates.
+
NOTE: For node OS, unattended upgrades for security patches are run on a daily basis but the node is not rebooted automatically. By applying upgrades, you are rebooting each node for the security updates to take effect.

A banner appears indicating the component upgrade is successful. There could be up to a 15 minute delay before NetApp Hybrid Cloud Control UI shows the updated version number.

== Use NetApp Hybrid Cloud Control API to upgrade a Rancher deployment

You can use APIs to upgrade any of these components in your Rancher deployment:

* Rancher server
* Rancher Kubernetes Engine (RKE)
* Node OS security updates

You can use an automation tool of your choice to run the APIs. The API workflow documented here uses the REST API UI available on the management node as an example.

.Options
* <<Upgrade Rancher Server>>
-Check for latest upgrade packages `POST /upgrade​/rancher-versions` /test connection
-Download package, if dark site
-`PUT /upgrade​/rancher​/{version}`
* <<Upgrade RKE>>
-Check for latest upgrade packages `POST /upgrade​/rke-versions`/test connection
-Download package, if dark site
-`PUT /upgrade​/rke​/{version}`
* <<Apply Node OS security updates>>
NOTE: Node upgrades happen automatically. However, you need to reboot the nodes sequentially to apply upgrades.

-Check for latest upgrade packages `GET /upgrade​/checkNodeUpdates`/test connection
-Download package, if dark site
-`POST ​/upgrade​/applyNodeUpdates`

=== Upgrade Rancher Server
. Open the management node REST API UI on the management node:
+
----
https://[management node IP]//k8sdeployer/api/
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the authorization window.
. Check for the latest upgrade packages:
+
----
curl -X POST "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher-versions" -H "accept: application/json" -H "Authorization: Bearer <ID>"
----
. From the REST API UI, click *POST /upgrade​/rancher-versions*.
.. Click *Try it out*.
.. Click *Execute*.
.. From the response, copy the latest version number.
. Run the Rancher Server upgrade:
+
----
curl -X PUT "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher/x.x.x" -H "accept: application/json" -H "Authorization: Bearer"
----
. From the REST API UI, click *PUT /upgrade​/rancher​/{version}*.
.. Click *Try it out*.
.. Enter the version number from the previous step.
.. Click *Execute*.
.. The response indicates that the request was initiated (`"stage": "init"`). Copy the task ID from the response. Wait up to 15 minutes before performing the next step.
. Verify the upgrade was successful:
+
----
curl -X GET "https://<mNodeID>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer <ID>"
----
. From the REST API UI, click *GET /task​/{taskID}*.
.. Click *Try it out*.
.. Enter the task ID from the previous step.
.. Click *Execute*.

The upgrade has finished successfully when the `PercentComplete` indicates `100` and `results` indicates the upgrade version number.

=== Upgrade RKE
. Open the management node REST API UI on the management node:
+
----
https://[management node IP]//k8sdeployer/api/
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the authorization window.
. Check for the latest upgrade packages:
+
----
curl -X POST "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher-versions" -H "accept: application/json" -H "Authorization: Bearer <ID>"
----
. From the REST API UI, click *POST /upgrade​/rancher-versions*.
.. Click *Try it out*.
.. Click *Execute*.
.. From the response, copy the latest version number.
. Run the Rancher Server upgrade:
+
----
curl -X PUT "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher/x.x.x" -H "accept: application/json" -H "Authorization: Bearer"
----
. From the REST API UI, click *PUT /upgrade​/rancher​/{version}*.
.. Click *Try it out*.
.. Enter the version number from the previous step.
.. Click *Execute*.
.. The response indicates that the request was initiated (`"stage": "init"`). Copy the task ID from the response. Wait up to 15 minutes before performing the next step.
. Verify the upgrade was successful:
+
----
curl -X GET "https://<mNodeID>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer <ID>"
----
. From the REST API UI, click *GET /task​/{taskID}*.
.. Click *Try it out*.
.. Enter the task ID from the previous step.
.. Click *Execute*.

The upgrade has finished successfully when the `PercentComplete` indicates `100` and `results` indicates the upgrade version number.

=== Apply Node OS security updates
. Open the management node REST API UI on the management node:
+
----
https://[management node IP]//k8sdeployer/api/
----
.. Click *Authorize* and complete the following:
... Enter the cluster user name and password.
... Enter the client ID as `mnode-client`.
... Click *Authorize* to begin a session.
... Close the authorization window.
. Check for the latest upgrade packages:
+
----
curl -X POST "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher-versions" -H "accept: application/json" -H "Authorization: Bearer <ID>"
----
. From the REST API UI, click *POST /upgrade​/rancher-versions*.
.. Click *Try it out*.
.. Click *Execute*.
.. From the response, copy the latest version number.
. Run the Rancher Server upgrade:
+
----
curl -X PUT "https://<mNodeIP>/k8sdeployer/1/upgrade/rancher/x.x.x" -H "accept: application/json" -H "Authorization: Bearer"
----
. From the REST API UI, click *PUT /upgrade​/rancher​/{version}*.
.. Click *Try it out*.
.. Enter the version number from the previous step.
.. Click *Execute*.
.. The response indicates that the request was initiated (`"stage": "init"`). Copy the task ID from the response. Wait up to 15 minutes before performing the next step.
. Verify the upgrade was successful:
+
----
curl -X GET "https://<mNodeID>/k8sdeployer/1/task/<taskID>" -H "accept: application/json" -H "Authorization: Bearer <ID>"
----
. From the REST API UI, click *GET /task​/{taskID}*.
.. Click *Try it out*.
.. Enter the task ID from the previous step.
.. Click *Execute*.

The upgrade has finished successfully when the `PercentComplete` indicates `100` and `results` indicates the upgrade version number.

[discrete]
== Find more information

* https://docs.netapp.com/us-en/vcp/index.html[NetApp Element Plug-in for vCenter Server^]
* https://docs.netapp.com/us-en/documentation/hci.aspx[NetApp HCI Resources Page^]
