---
sidebar: sidebar
permalink: docs/task_nde_start_deployment.html
summary: Begin deploying NetApp HCI.
keywords: netapp, hci, netapp deployment engine, deployment, engine, deploy, access
---

= Start your deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/
:keywords: hci, release notes, vcp, element, management services, firmware

[.lead]
Before continuing with your NetApp HCI deployment, you need to read and understand the end user license agreements.

.Steps

. On the *Welcome to NetApp HCI* page, click *Get Started*.
. On the *Prerequisites* page, do the following:
.. Ensure each prerequisite is met, and click each associated checkbox to confirm.
.. Click *Continue*.
. On the *End User Licenses* page, do the following:
.. Read the NetApp End User License Agreement.
.. If you accept the terms, click *I accept* at the bottom of the agreement text.
.. Read the VMware End User License Agreement.
.. If you accept the terms, click *I accept* at the bottom of the agreement text.
.. Click *Continue*.

[discrete]
== Find more information
* link:firmware_driver_versions.html[Supported firmware and ESXi driver versions for NetApp HCI and firmware versions for NetApp HCI storage nodes]
