---
sidebar: docs_sidebar
permalink: docs/task_trident_enable_networking.html
summary: Enable Trident support for user clusters.
keywords: netapp, hci, netapp, networking, clusters, user, trident, rancher
---

= Enable Trident support for user clusters
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
If your NetApp HCI environment does not have a route between the management and storage networks, and you deploy user clusters with Trident persistent storage support, you need to further configure your networks after installing Trident. You need to enable communication between the management and storage networks for the user clusters you deploy. You can do this by modifying the networking configuration for each node in the user cluster.

.About this task
Follow these general steps to modify the networking configuration for each node in the user cluster. These steps assume that you created the user cluster with the default node template that is installed with Rancher on NetApp HCI.

.Steps

. Deploy a user cluster with existing default template.
. Connect storage network to the user cluster. (how?)
. In Rancher, record the SSH private key for each node in the user cluster.
. Connect using SSH to a node in the user cluster, using the private key that you have recorded for that node:
+
----
ssh -i <private key filename> <ip address>
----
. As the superuser, edit the `/etc/netplan/50-cloud-init.yaml` file so that it resembles this example (the `ens224` section has been added):
+
----
network:
    ethernets:
        ens192:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:1d:41
            set-name: ens192
        ens224:
            dhcp4: true
            match:
                macaddress: 00:50:56:91:5b:e9
            set-name: ens224
    version: 2
----
. Use the following command to reconfigure the network with the changed file:
----
`netplan try`
----
. Repeat steps 4-6 for each remaining node in the user cluster.
. When complete, your apps deployed in the user cluster should be able to make use of persistent storage.

NOTE: You can make these changes as part of a custom node template if you like for future user clusters.
